add('skos:broader'('a26:Category:Cyclists_from_Western_Australia', 'a26:Category:Sportspeople_from_Western_Australia_by_sport')).
add('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Islands_of_the_North_Atlantic_Ocean')).
add('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Islands_by_ocean_or_sea')).
add('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_and_colleges_in_Ottawa')).
add('skos:broader'('a26:Category:American_Airlines_people', 'a26:Category:American_Airlines')).
add('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Irish_Sea')).
add('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_in_Ontario')).
add('skos:broader'('a26:Category:Rulers_of_Baden', 'a26:Category:German_monarchs')).
add('skos:broader'('a26:Category:Ministry_band_members', 'a26:Category:Ministry_band')).
add('skos:broader'('a26:Category:Roman_Catholic_Church_in_Slovakia', 'a26:Category:Roman_Catholic_Church_in_Europe')).
delete('skos:broader'('a26:Category:Compositions_in_E_minor', 'a26:Category:Compositions_by_key')).
delete('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Computer_languages')).
delete('skos:broader'('a26:Category:Explosions_in_England', 'a26:Category:Disasters_in_England')).
delete('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Software_engineering')).
delete('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Peruvian_sportspeople')).
delete('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
delete('skos:broader'('a26:Category:Association_football_international_competitions_squad_navigational_boxes', 'a26:Category:Association_football_international_competitions_navigational_boxes')).
delete('skos:broader'('a26:Category:Screenshots_of_Windows_Server', 'a26:Category:Windows_Server')).
delete('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:Centuries_in_Staffordshire')).
delete('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Romani_in_Italy')).
