add('skos:broader'('a26:Category:Arab_people_of_the_Arab_Byzantine_wars', 'a26:Category:People_of_the_Arab_Byzantine_wars')).
add('skos:broader'('a26:Category:KMFDM', 'a26:Category:Wikipedia_categories_named_after_German_musical_groups')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Historic_districts_in_Pennsylvania_by_county')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Analysis')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Geography_of_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_sports_competitions_hosted_by_France')).
add('skos:broader'('a26:Category:Buddhist_titles', 'a26:Category:Titles')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:History_of_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:Edmonton_Oilers_broadcasters', 'a26:Category:National_Hockey_League_broadcasters')).
delete('skos:broader'('a26:Category:Conspiracy_theories', 'a26:Category:Conspiracy')).
delete('skos:broader'('a26:Category:Hungarian_people_of_Slovenian_descent', 'a26:Category:Hungarian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:Altötting_district', 'a26:Category:Upper_Bavaria')).
delete('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
delete('skos:broader'('a26:Category:French_silent_short_films', 'a26:Category:Silent_short_films')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_the_South_Region_Brazil')).
delete('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:English_businesspeople_by_city')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Geography_of_Rio_Grande_do_Sul')).
delete('skos:broader'('a26:Category:Advanced_Micro_Devices', 'a26:Category:Manufacturing_companies_of_the_United_States')).
delete('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:British_businesspeople')).
