add('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
add('skos:broader'('a26:Category:Cyclists_from_Western_Australia', 'a26:Category:Sportspeople_from_Western_Australia_by_sport')).
add('skos:broader'('a26:Category:Soap_opera_actors_by_nationality', 'a26:Category:Categories_by_nationality')).
add('skos:broader'('a26:Category:Aguadilla_Isabela_San_Sebastián_metropolitan_area', 'a26:Category:Metropolitan_areas_of_Puerto_Rico')).
add('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Topology')).
add('skos:broader'('a26:Category:Dukes_of_Choiseul', 'a26:Category:Dukes_of_France')).
add('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Local_government_in_Somerset')).
add('skos:broader'('a26:Category:Peers', 'a26:Category:British_people_by_rank')).
add('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Abstract_algebra')).
add('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:British_businesspeople')).
delete('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Italian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:2009_in_Catalan_sport', 'a26:Category:2009_in_Spanish_sport')).
delete('skos:broader'('a26:Category:People_from_Perth-Andover', 'a26:Category:People_from_Victoria_County_New_Brunswick')).
delete('skos:broader'('a26:Category:Nama_people', 'a26:Category:Namibian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_Brazil_by_state')).
delete('skos:broader'('a26:Category:Organizations_based_in_the_United_States_by_state', 'a26:Category:Organizations_by_country_subdivision')).
delete('skos:broader'('a26:Category:Professional_Indoor_Football_League_teams', 'a26:Category:Indoor_American_football_teams_in_the_United_States_by_league')).
delete('skos:broader'('a26:Category:Turkish_Football_Federation_presidents', 'a26:Category:Turkish_Football_Federation')).
delete('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Buildings_and_structures_in_Midlothian')).
delete('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Scottish_architecture')).
