add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent340')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent386')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent388')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent116')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent56')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent173')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent346')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent196')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent10')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent125')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent231')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent273')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent86')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent48')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent73')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent21')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent23')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent201')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent247')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent201')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent50')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent136')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent9')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent322')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent155')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent405')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent428')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent219')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent136')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent197')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent322')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent77')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent17')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse23')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent5')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse13')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent167')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse15')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent106')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent439')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent394')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent42')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent26')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent318')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent288')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent129')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse38')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent31')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent70')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent58')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent56')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse9')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent277')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent279')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent233')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse33')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent124')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent228')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent124')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent313')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent372')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent289')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse40')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent226')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent29')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse44')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent30')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent95')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent138')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent407')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent130')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent12')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent153')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent259')).
add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor9')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent274')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent418')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent99')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent20')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent335')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent86')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent206')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent240')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent263')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent221')).
