add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent42')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent50')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent111')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent244')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent17')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse22')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent335')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent233')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent138')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent36')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent6')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse4')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent80')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent10')).
