add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent278')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent124')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent30')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent287')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent26')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse11')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse36')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent274')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent9')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor0')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent31')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent246')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent33')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent235')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent206')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent130')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
