add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent51')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent126')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse0')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent97')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent80')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse13')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent190')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse19')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent42')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent147')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer0')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent56')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent428')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent187')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent105')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse38')).
delete('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer1')).
