add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent233')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent30')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent106')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent325')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent54')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent313')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent316')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent129')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent418')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent386')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent70')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer0')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent226')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent117')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent175')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse38')).
