add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent427')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent10')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent197')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse4')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent27')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent39')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent258')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent79')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse22')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent2')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent188')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent128')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent125')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent164')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent220')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent249')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse23')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent284')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent431')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent347')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent38')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent218')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent153')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent382')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent343')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent232')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent299')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent93')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent68')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent126')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
delete('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor8')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent336')).
delete('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor6')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent186')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
