add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent135')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent32')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent60')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent174')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent12')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent383')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent173')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse9')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent74')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse10')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent59')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent271')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent294')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent351')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent416')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent336')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent140')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent391')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent47')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent222')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent47')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent242')).
add('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor0')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent68')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent280')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent203')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent281')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent79')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent33')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent155')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent347')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent41')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent75')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent54')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent78')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent18')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent383')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent256')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent75')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse0')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent100')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent334')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse13')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent186')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent161')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent91')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent46')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent264')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent269')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent89')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse32')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent319')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent51')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse19')).
