add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse19')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent88')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent345')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent382')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent384')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent424')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse37')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse29')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent168')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent45')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent126')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent70')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent128')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent336')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent186')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent180')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent249')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent16')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor3')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse48')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent431')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent385')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent85')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent92')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent7')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent127')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent216')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent324')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent259')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent100')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent100')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent188')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent379')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent11')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent168')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent107')).
delete('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent186')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent318')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent104')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent19')).
