add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent130')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent155')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent347')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent216')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent27')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent258')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent46')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent68')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent419')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent80')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent111')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent70')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent33')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent310')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent14')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse46')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse23')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent428')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent90')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent38')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent278')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent128')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent94')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent90')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse29')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent11')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent107')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent206')).
delete('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent186')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor4')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse20')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
