add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent134')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent139')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent368')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse11')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent107')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent323')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent320')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent15')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent307')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent215')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent276')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent214')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent1')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent47')).
add('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor1')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent376')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent333')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent126')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent167')).
add('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor7')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent25')).
add('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor6')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent61')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent83')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent265')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent269')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent264')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent46')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent45')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent246')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent85')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent6')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent78')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent5')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent2')).
add('a1:AssistantProfessor'('http://www.Department1.University0.edu/AssistantProfessor7')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent56')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent343')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent138')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse16')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent115')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent30')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent76')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent428')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent58')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent56')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent71')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent176')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent322')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent26')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent54')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent98')).
delete('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent97')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent46')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent117')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent251')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent297')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent290')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent46')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent165')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent31')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse23')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent20')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent40')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent312')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent23')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor5')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent266')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent0')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent24')).
delete('a1:Lecturer'('http://www.Department2.University0.edu/Lecturer3')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse23')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent202')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent9')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent261')).
