add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent351')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent57')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent426')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent79')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent59')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent54')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent24')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent91')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent274')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent70')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent33')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent75')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse32')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent74')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse33')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent359')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent29')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent152')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent194')).
