add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent385')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent71')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent90')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent64')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent386')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent54')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent156')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent64')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent310')).
