add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent54')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent264')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent347')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent87')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor4')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent268')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent379')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent199')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent206')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent37')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent180')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
