add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent111')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse25')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent369')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent90')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent127')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent6')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent382')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent210')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent385')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent23')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent80')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent94')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent186')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
