add('skos:broader'('a26:Category:Injuries_of_ankle_and_foot', 'a26:Category:Injuries_by_region_of_body')).
add('skos:broader'('a26:Category:University_of_Belgrade_Faculty_of_Philosophy_alumni', 'a26:Category:Philosophy_academics')).
add('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_American_people')).
add('skos:broader'('a26:Category:Altötting_district', 'a26:Category:Upper_Bavaria')).
add('skos:broader'('a26:Category:Austrian_Football_Bundesliga_players', 'a26:Category:Association_football_players_by_competition')).
add('skos:broader'('a26:Category:Professional_Indoor_Football_League_teams', 'a26:Category:Indoor_American_football_teams_in_the_United_States_by_league')).
add('skos:broader'('a26:Category:Graphemes', 'a26:Category:Units_of_morphological_analysis')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs_in_Asia')).
add('skos:broader'('a26:Category:MCG_objects', 'a26:Category:MCG_objects')).
add('skos:broader'('a26:Category:Documentary_films_about_homelessness_in_the_United_States', 'a26:Category:Documentary_films_about_poverty_in_the_United_States')).
add('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Italian_people_by_ethnic_or_national_origin')).
add('skos:broader'('a26:Category:North_American_culture_by_country', 'a26:Category:North_American_culture')).
add('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Visitor_attractions_in_South_Korea_by_city')).
add('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Local_government_in_Somerset')).
add('skos:broader'('a26:Category:South_African_people_of_Zimbabwean_descent', 'a26:Category:South_Africa_Zimbabwe_relations')).
add('skos:broader'('a26:Category:Northwest_Territories_territorial_electoral_districts', 'a26:Category:Canadian_provincial_and_territorial_electoral_districts')).
add('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Geography_of_Los_Angeles_County_California')).
add('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Visitor_attractions_in_Midlothian')).
add('skos:broader'('a26:Category:Fashion_events_in_the_United_Kingdom', 'a26:Category:British_fashion')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Middle_Eastern_monarchs')).
add('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_and_colleges_in_Ottawa')).
add('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publishing_company_of_the_United_States')).
add('skos:broader'('a26:Category:Census-designated_places_in_Tennessee', 'a26:Category:Populated_places_in_Tennessee')).
add('skos:broader'('a26:Category:Theatres_in_New_York_City', 'a26:Category:Visitor_attractions_in_New_York_City')).
add('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Parma_FC')).
add('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Sport_shooters_by_nationality')).
add('skos:broader'('a26:Category:Populated_places_in_Galikash_County', 'a26:Category:Populated_places_in_Golestan_Province')).
add('skos:broader'('a26:Category:People_from_the_Las_Vegas_Valley', 'a26:Category:People_by_populated_place_in_Nevada')).
add('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Woodwind_musicians')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs')).
add('skos:broader'('a26:Category:Pirate_Party_Germany', 'a26:Category:Liberal_parties_in_Germany')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Geography_of_Rio_Grande_do_Sul')).
add('skos:broader'('a26:Category:Companies_based_in_Atlanta_Georgia', 'a26:Category:Companies_based_in_Georgia_U.S._state_by_city')).
add('skos:broader'('a26:Category:Advanced_Micro_Devices', 'a26:Category:Manufacturing_companies_of_the_United_States')).
add('skos:broader'('a26:Category:Ministry_band_members', 'a26:Category:Ministry_band')).
delete('skos:broader'('a26:Category:Works_set_on_the_London_Underground', 'a26:Category:London_Underground')).
delete('skos:broader'('a26:Category:Iowa_Libertarians', 'a26:Category:Iowa_politicians_by_party')).
delete('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
delete('skos:broader'('a26:Category:Mythological_sword_fighters', 'a26:Category:Mythological_characters')).
delete('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Archaeological_sites_in_Egypt')).
delete('skos:broader'('a26:Category:Table_tennis_in_North_America', 'a26:Category:Sport_in_North_America_by_sport')).
delete('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
delete('skos:broader'('a26:Category:Transport_in_Greater_Moncton', 'a26:Category:Transport_in_New_Brunswick_by_city')).
delete('skos:broader'('a26:Category:Adaptations_of_works_by_Luigi_Pirandello', 'a26:Category:Adaptations_of_works_by_writer')).
delete('skos:broader'('a26:Category:Woody_Guthrie', 'a26:Category:Guthrie_family')).
delete('skos:broader'('a26:Category:Literary_motifs', 'a26:Category:Fiction_by_topic')).
delete('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_water_polo_competitions_by_host')).
delete('skos:broader'('a26:Category:Five-year_plans', 'a26:Category:Economic_planning')).
delete('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1285_in_Europe')).
delete('skos:broader'('a26:Category:610_mm_gauge_railway_locomotives', 'a26:Category:2_ft_gauge_locomotives')).
delete('skos:broader'('a26:Category:University_of_Benghazi_faculty', 'a26:Category:Faculty_by_university_or_college_in_Libya')).
delete('skos:broader'('a26:Category:Songwriters_from_Texas', 'a26:Category:Musicians_from_Texas')).
delete('skos:broader'('a26:Category:Literary_motifs', 'a26:Category:Elements_of_fiction')).
delete('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Cinema_of_Brazil')).
delete('skos:broader'('a26:Category:Soap_opera_actors_by_nationality', 'a26:Category:Categories_by_nationality')).
delete('skos:broader'('a26:Category:2nd_millennium_in_South_Carolina', 'a26:Category:2nd_millennium_in_the_United_States')).
delete('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_sculptors')).
delete('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Abstract_algebra')).
delete('skos:broader'('a26:Category:Defunct_American_football_teams', 'a26:Category:Defunct_sports_teams')).
delete('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Housing_in_the_United_Kingdom')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_the_South_Region_Brazil')).
delete('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Universities_and_colleges_in_California_by_county')).
delete('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:History_of_Adams_County_Pennsylvania')).
delete('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Footballers_in_Italy_by_club')).
delete('skos:broader'('a26:Category:Roman_Catholic_Church_in_Slovakia', 'a26:Category:Roman_Catholic_Church_in_Europe')).
delete('skos:broader'('a26:Category:Films_shot_in_Hong_Kong', 'a26:Category:Hong_Kong_culture')).
delete('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
delete('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:Establishments_in_British_Columbia_by_year')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Clarinets')).
