add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent254', 'http://www.Department0.University0.edu/Course11')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor2/Publication3', 'http://www.Department2.University0.edu/GraduateStudent100')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent47', 'http://www.University183.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent213', 'http://www.Department0.University0.edu/Course23')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent88', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent14', 'http://www.Department0.University0.edu/GraduateCourse29')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent245', '"UndergraduateStudent245@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent61', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication2', 'http://www.Department0.University0.edu/GraduateStudent94')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent16', 'http://www.Department2.University0.edu/FullProfessor4')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent32', 'http://www.University914.edu')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent80', 'http://www.Department2.University0.edu/FullProfessor2')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent5', 'http://www.Department1.University0.edu/Course18')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent113', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent186', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent80', 'http://www.Department1.University0.edu/Course22')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent73', 'http://www.Department0.University0.edu/Course12')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor5', 'http://www.Department2.University0.edu/Course37')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent169', 'http://www.Department0.University0.edu/Course6')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent48', 'http://www.Department1.University0.edu/Course23')).
