add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent124', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent277', 'http://www.Department1.University0.edu/Course20')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent80', 'http://www.Department2.University0.edu/FullProfessor2')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent57', 'http://www.Department2.University0.edu/Course25')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor3/Publication6', 'http://www.Department2.University0.edu/GraduateStudent5')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent42', 'http://www.Department0.University0.edu/GraduateCourse4')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor6/Publication10', 'http://www.Department0.University0.edu/GraduateStudent73')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent250', 'http://www.Department2.University0.edu/Course35')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent144', 'http://www.Department1.University0.edu/Course49')).
add('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor10', 'http://www.Department0.University0.edu/Course27')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent146', '"UndergraduateStudent146@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent71', '"UndergraduateStudent71@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent226', 'http://www.Department2.University0.edu/Course21')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent69', 'http://www.Department0.University0.edu/Course25')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent61', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication2', 'http://www.Department0.University0.edu/GraduateStudent94')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent90', 'http://www.Department1.University0.edu/Course32')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent16', 'http://www.Department2.University0.edu/FullProfessor4')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent56', 'http://www.Department0.University0.edu/Course2')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication0', 'http://www.Department2.University0.edu/AssociateProfessor3')).
