add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent63', 'http://www.Department1.University0.edu/Course28')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent146', '"UndergraduateStudent146@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent71', '"UndergraduateStudent71@Department1.University0.edu"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent34', 'http://www.University828.edu')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent296', 'http://www.Department1.University0.edu/Course40')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent345', 'http://www.Department1.University0.edu/Course6')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent186', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent251', '"UndergraduateStudent251@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent182', 'http://www.Department2.University0.edu/Course19')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent48', 'http://www.Department1.University0.edu/Course23')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent32', 'http://www.University914.edu')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent80', 'http://www.Department2.University0.edu/Course42')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent69', 'http://www.Department0.University0.edu/Course25')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent40', 'http://www.Department0.University0.edu/GraduateCourse34')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent113', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent154', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent49', 'http://www.University460.edu')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication0', 'http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor10', 'http://www.Department0.University0.edu/Course27')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent9', '"xxx-xxx-xxxx"^^xsd:string')).
