add('skos:broader'('a26:Category:Works_set_on_the_London_Underground', 'a26:Category:London_Underground')).
add('skos:broader'('a26:Category:Injuries_of_ankle_and_foot', 'a26:Category:Injuries_by_region_of_body')).
add('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_American_people')).
add('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Historic_districts_in_Pennsylvania_by_county')).
add('skos:broader'('a26:Category:Buildings_and_structures_in_Teton_County_Wyoming', 'a26:Category:Buildings_and_structures_in_Wyoming_by_county')).
add('skos:broader'('a26:Category:Long-distance_footpaths_in_Wales', 'a26:Category:Footpaths_in_Wales')).
add('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Topology')).
add('skos:broader'('a26:Category:Culture_by_language', 'a26:Category:Cultures')).
add('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Non-metropolitan_districts_of_Somerset')).
add('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:American_sculptors_by_century')).
add('skos:broader'('a26:Category:Buddhist_titles', 'a26:Category:Titles')).
add('skos:broader'('a26:Category:2012_television_films', 'a26:Category:2012_films')).
add('skos:broader'('a26:Category:People_from_Perth-Andover', 'a26:Category:People_from_Victoria_County_New_Brunswick')).
add('skos:broader'('a26:Category:Census-designated_places_in_Tennessee', 'a26:Category:Populated_places_in_Tennessee')).
add('skos:broader'('a26:Category:Organizations_based_in_the_United_States_by_state', 'a26:Category:Society_of_the_United_States_by_state')).
add('skos:broader'('a26:Category:Arab_people_of_the_Arab_Byzantine_wars', 'a26:Category:People_of_the_Arab_Byzantine_wars')).
add('skos:broader'('a26:Category:Austrian_Football_Bundesliga_players', 'a26:Category:Austrian_Football_Bundesliga')).
add('skos:broader'('a26:Category:Landforms_of_Petersburg_Borough_Alaska', 'a26:Category:Geography_of_Petersburg_Borough_Alaska')).
add('skos:broader'('a26:Category:Balé_Province', 'a26:Category:Provinces_of_Burkina_Faso')).
add('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
add('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Dogs')).
add('skos:broader'('a26:Category:Scots_law_formal_titles', 'a26:Category:Scottish_titles')).
add('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
add('skos:broader'('a26:Category:Albums_by_Ugandan_artists', 'a26:Category:Works_by_Ugandan_people')).
add('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1280s_in_England')).
add('skos:broader'('a26:Category:Mythological_sword_fighters', 'a26:Category:Mythological_characters')).
add('skos:broader'('a26:Category:Rulers_of_Baden', 'a26:Category:German_monarchs')).
add('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Mammal_breeds')).
add('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Scottish_architecture')).
add('skos:broader'('a26:Category:Dukes_of_Choiseul', 'a26:Category:Dukes_of_France')).
add('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Visitor_attractions_in_South_Korea_by_city')).
add('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Local_government_in_Somerset')).
add('skos:broader'('a26:Category:610_mm_gauge_railway_locomotives', 'a26:Category:2_ft_gauge_locomotives')).
add('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Tourism_in_Ulsan')).
add('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Buildings_and_structures_in_Midlothian')).
add('skos:broader'('a26:Category:People_from_Madrid', 'a26:Category:Madrilenian_people')).
add('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Ptolemaic_colonies')).
add('skos:broader'('a26:Category:African_culture_by_nationality', 'a26:Category:African_culture')).
add('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_and_colleges_in_Ottawa')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Heads_of_state_in_the_Middle_East')).
add('skos:broader'('a26:Category:Blackened_death_metal_musical_groups', 'a26:Category:Blackened_death_metal')).
add('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Universities_and_colleges_in_California_by_county')).
add('skos:broader'('a26:Category:British_tubists', 'a26:Category:Tubists_by_nationality')).
add('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Parma_FC')).
add('skos:broader'('a26:Category:People_from_the_Las_Vegas_Valley', 'a26:Category:People_by_populated_place_in_Nevada')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs')).
add('skos:broader'('a26:Category:Graphemes', 'a26:Category:Writing_systems')).
add('skos:broader'('a26:Category:Treaties_of_the_Grand_Duchy_of_Hesse', 'a26:Category:Treaties_of_Germany')).
add('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Romani_in_Italy')).
delete('skos:broader'('a26:Category:American_Airlines_people', 'a26:Category:American_Airlines')).
delete('skos:broader'('a26:Category:Chantilly_Racecourse', 'a26:Category:Wikipedia_categories_named_after_sports_venues')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs_in_Asia')).
delete('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Dog_breeding')).
delete('skos:broader'('a26:Category:Aguadilla_Isabela_San_Sebastián_metropolitan_area', 'a26:Category:Metropolitan_areas_of_Puerto_Rico')).
delete('skos:broader'('a26:Category:Literary_motifs', 'a26:Category:Fiction_by_topic')).
delete('skos:broader'('a26:Category:Five-year_plans', 'a26:Category:Economic_planning')).
delete('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1285_in_Europe')).
delete('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Education_in_Alameda_County_California')).
delete('skos:broader'('a26:Category:Transportation_in_Maine_by_county', 'a26:Category:Maine_counties')).
delete('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_in_Ontario')).
delete('skos:broader'('a26:Category:Peers', 'a26:Category:British_people_by_rank')).
delete('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Abstract_algebra')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_the_South_Region_Brazil')).
delete('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Chemistry')).
delete('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:Racquetball_players_by_nationality')).
delete('skos:broader'('a26:Category:Companies_based_in_Atlanta_Georgia', 'a26:Category:Companies_based_in_Georgia_U.S._state_by_city')).
delete('skos:broader'('a26:Category:Ministry_band_members', 'a26:Category:Ministry_band')).
delete('skos:broader'('a26:Category:Edmonton_Oilers_broadcasters', 'a26:Category:National_Hockey_League_broadcasters')).
delete('skos:broader'('a26:Category:Austrian_Football_Bundesliga_players', 'a26:Category:Association_football_players_by_competition')).
delete('skos:broader'('a26:Category:Philippine_society', 'a26:Category:Philippines')).
delete('skos:broader'('a26:Category:Table_tennis_in_North_America', 'a26:Category:Sport_in_North_America_by_sport')).
delete('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Geography_of_Adams_County_Pennsylvania')).
delete('skos:broader'('a26:Category:Woody_Guthrie', 'a26:Category:Guthrie_family')).
delete('skos:broader'('a26:Category:Bender_Moldova', 'a26:Category:Districts_of_Moldova')).
delete('skos:broader'('a26:Category:MCG_objects', 'a26:Category:Astronomical_catalogues')).
delete('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Italian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:Conglomerate_companies_of_France', 'a26:Category:Conglomerate_companies_by_country')).
delete('skos:broader'('a26:Category:African_culture_by_nationality', 'a26:Category:Culture_by_nationality')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Musicians_by_instrument')).
delete('skos:broader'('a26:Category:Third_Doctor_stories', 'a26:Category:Doctor_Who_stories')).
delete('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:British_businesspeople')).
delete('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_sculptors')).
delete('skos:broader'('a26:Category:British_adventure_films', 'a26:Category:British_films_by_genre')).
delete('skos:broader'('a26:Category:Defunct_American_football_teams', 'a26:Category:Defunct_sports_teams')).
delete('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publishing_company_of_the_United_States')).
delete('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publisher')).
delete('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Films_by_country')).
delete('skos:broader'('a26:Category:Conglomerate_companies_of_France', 'a26:Category:Companies_of_France')).
delete('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:History_of_Adams_County_Pennsylvania')).
delete('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:Water_polo_competitions_in_France')).
delete('skos:broader'('a26:Category:Populated_places_in_Galikash_County', 'a26:Category:Populated_places_in_Golestan_Province')).
delete('skos:broader'('a26:Category:Films_shot_in_Hong_Kong', 'a26:Category:Hong_Kong_culture')).
delete('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Computer_languages')).
delete('skos:broader'('a26:Category:Irish_entertainers', 'a26:Category:Irish_people_by_occupation')).
delete('skos:broader'('a26:Category:Geography_of_Greene_County_New_York', 'a26:Category:Geography_of_the_Hudson_Valley')).
delete('skos:broader'('a26:Category:Member_states_of_the_United_Nations', 'a26:Category:United_Nations')).
delete('skos:broader'('a26:Category:The_Football_League_representative_players', 'a26:Category:The_Football_League_players')).
delete('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
delete('skos:broader'('a26:Category:Screenshots_of_Windows_Server', 'a26:Category:Windows_Server')).
