add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent421', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent197', '"UndergraduateStudent197@Department2.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent51', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent98', 'http://www.Department1.University0.edu/GraduateCourse6')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent39', 'http://www.University915.edu')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent415', 'http://www.Department2.University0.edu/Course0')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent192', 'http://www.Department1.University0.edu/Course49')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent99', 'http://www.Department1.University0.edu/GraduateCourse11')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent275', '"UndergraduateStudent275@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent50', 'http://www.Department2.University0.edu/Course30')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent74', 'http://www.Department1.University0.edu/GraduateCourse42')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent234', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent38', '"GraduateStudent38@Department1.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent229', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent127', 'http://www.Department2.University0.edu/Course4')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent289', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/AssociateProfessor1', '"AssociateProfessor1@Department0.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent147', '"UndergraduateStudent147@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent37', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent301', 'http://www.Department1.University0.edu/Course48')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent206', 'http://www.Department0.University0.edu/Course28')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor4/Publication11', 'http://www.Department1.University0.edu/FullProfessor4')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent384', 'http://www.Department2.University0.edu/Course47')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent314', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent0', 'http://www.Department2.University0.edu/Course21')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent220', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent77', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent79', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/AssociateProfessor6', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent79', 'http://www.Department2.University0.edu/AssistantProfessor5')).
delete('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/Lecturer1', 'http://www.University453.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent408', 'http://www.Department1.University0.edu/Course9')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor5/Publication3', 'http://www.Department1.University0.edu/AssistantProfessor5')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent345', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent99', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent122', 'http://www.Department1.University0.edu/Course15')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent282', '"UndergraduateStudent282@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent18', 'http://www.Department0.University0.edu/Course23')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent255', 'http://www.Department0.University0.edu/Course8')).
