add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent162', '"UndergraduateStudent162@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department1.University0.edu/AssociateProfessor1')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent92', 'http://www.Department1.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent321', 'http://www.Department1.University0.edu/Course7')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent442', 'http://www.Department1.University0.edu/Course26')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor1')).
add('a1:mastersDegreeFrom'('http://www.Department1.University0.edu/AssociateProfessor6', 'http://www.University812.edu')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent214', 'http://www.Department1.University0.edu/Course34')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent122', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent75', 'http://www.Department2.University0.edu/Course33')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent60', 'http://www.Department1.University0.edu/Course13')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent219', 'http://www.Department0.University0.edu/Course38')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssistantProfessor3', 'http://www.University803.edu')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent65', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/Lecturer2/Publication1', 'http://www.Department0.University0.edu/GraduateStudent97')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent420', 'http://www.Department1.University0.edu/Course20')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent300', '"UndergraduateStudent300@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor7/Publication3', 'http://www.Department1.University0.edu/GraduateStudent10')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication6', 'http://www.Department1.University0.edu/FullProfessor5')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication6', 'http://www.Department0.University0.edu/GraduateStudent94')).
delete('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent97', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor1/Publication8', 'http://www.Department0.University0.edu/AssistantProfessor1')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent421', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent235', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent12', 'http://www.Department2.University0.edu/AssociateProfessor12')).
delete('a1:telephone'('http://www.Department2.University0.edu/Lecturer2', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent12', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent414', 'http://www.Department1.University0.edu/Course10')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent139', 'http://www.Department1.University0.edu/Course52')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication10', 'http://www.Department0.University0.edu/AssociateProfessor12')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent51', 'http://www.Department2.University0.edu/Course43')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent234', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent362', 'http://www.Department2.University0.edu/Course1')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent125', 'http://www.University885.edu')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor8/Publication6', 'http://www.Department1.University0.edu/AssociateProfessor8')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor9/Publication7', 'http://www.Department2.University0.edu/AssociateProfessor9')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent362', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent5', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication7', 'http://www.Department0.University0.edu/FullProfessor5')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent207', '"xxx-xxx-xxxx"^^xsd:string')).
