add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent61', '"UndergraduateStudent61@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent164', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent146', 'http://www.Department2.University0.edu/Course18')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent259', 'http://www.Department0.University0.edu/Course35')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent310', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent81', 'http://www.Department0.University0.edu/Course30')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent274', 'http://www.Department2.University0.edu/Course8')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent433', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor6/Publication1', 'http://www.Department2.University0.edu/GraduateStudent56')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication5', 'http://www.Department1.University0.edu/GraduateStudent28')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent122', 'http://www.University431.edu')).
add('a1:doctoralDegreeFrom'('http://www.Department0.University0.edu/AssistantProfessor2', 'http://www.University326.edu')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent181', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent46', 'http://www.Department0.University0.edu/FullProfessor7')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor8/Publication7', 'http://www.Department2.University0.edu/GraduateStudent2')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent46', 'http://www.Department2.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent44', 'http://www.Department0.University0.edu/Course19')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent267', 'http://www.Department0.University0.edu/Course39')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent396', '"UndergraduateStudent396@Department1.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent43', 'http://www.Department2.University0.edu/AssociateProfessor10')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication8', 'http://www.Department2.University0.edu/FullProfessor3')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent261', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent422', 'http://www.Department1.University0.edu/Course12')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent85', 'http://www.Department2.University0.edu/GraduateCourse3')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent23', '"GraduateStudent23@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent257', 'http://www.Department1.University0.edu/Course22')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent92', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent44', 'http://www.Department2.University0.edu/FullProfessor2')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent10', '"GraduateStudent10@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent272', 'http://www.Department1.University0.edu/Course47')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent391', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent219', 'http://www.Department0.University0.edu/Course38')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent4', 'http://www.University848.edu')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent71', 'http://www.Department2.University0.edu/Course19')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent32', 'http://www.Department1.University0.edu/GraduateCourse33')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor2/Publication3', 'http://www.Department0.University0.edu/FullProfessor2')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent327', 'http://www.Department2.University0.edu/Course31')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent65', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication7', 'http://www.Department0.University0.edu/AssociateProfessor11')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent99', '"xxx-xxx-xxxx"^^xsd:string')).
