add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=531899')).
add('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/busra_ash_sham')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=489466')).
add('a1:E48_Place_Name'('http://arachne.uni-koeln.de/vocabulary/depository#heiligtum-des-apollon-pythios')).
add('a1:E48_Place_Name'('http://arachne.uni-koeln.de/vocabulary/place#midea')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=2015442&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1653311')).
add('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/cassino')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=2092230&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=2089614')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=451126&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=645872&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=634331')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=2092253&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1410273')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=475168')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1308005')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=474368&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=579644')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=490754')).
