add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Works_by_Brazilian_people')).
add('skos:broader'('a26:Category:2nd_millennium_in_South_Carolina', 'a26:Category:2nd_millennium_in_the_United_States')).
add('skos:broader'('a26:Category:Screenshots_of_Windows_Server', 'a26:Category:Screenshots_of_Microsoft_Windows')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Mammal_breeds')).
delete('skos:broader'('a26:Category:Ethnic_groups_in_Arizona', 'a26:Category:Ethnic_groups_in_the_United_States_by_state')).
delete('skos:broader'('a26:Category:Bielsk_County', 'a26:Category:Land_counties_of_Podlaskie_Voivodeship')).
delete('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Dog_breeding')).
delete('skos:broader'('a26:Category:Płock_County', 'a26:Category:Land_counties_of_Masovian_Voivodeship')).
delete('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:Centuries_in_Staffordshire')).
