add('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/AssistantProfessor3', 'http://www.University437.edu')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor6/Publication12', 'http://www.Department1.University0.edu/FullProfessor6')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent410', 'http://www.Department2.University0.edu/Course16')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent55', 'http://www.Department2.University0.edu/GraduateCourse39')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor6/Publication11', 'http://www.Department1.University0.edu/AssociateProfessor6')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent68', '"UndergraduateStudent68@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent9', 'http://www.Department2.University0.edu/GraduateCourse23')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent214', 'http://www.Department1.University0.edu/Course34')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor2/Publication0', 'http://www.Department0.University0.edu/GraduateStudent96')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent143', 'http://www.Department0.University0.edu/Course50')).
add('a1:doctoralDegreeFrom'('http://www.Department0.University0.edu/FullProfessor4', 'http://www.University799.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent107', 'http://www.Department0.University0.edu/Course25')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent314', 'http://www.Department0.University0.edu/Course14')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent89', 'http://www.Department0.University0.edu/AssistantProfessor0')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent45', 'http://www.Department2.University0.edu/GraduateCourse48')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent408', 'http://www.Department1.University0.edu/Course9')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication7', 'http://www.Department0.University0.edu/AssociateProfessor11')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication5', 'http://www.Department2.University0.edu/FullProfessor5')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent298', 'http://www.Department1.University0.edu/Course25')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor1/Publication8', 'http://www.Department0.University0.edu/AssistantProfessor1')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication8', 'http://www.Department2.University0.edu/FullProfessor3')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent102', 'http://www.Department0.University0.edu/Course24')).
add('a1:telephone'('http://www.Department0.University0.edu/AssistantProfessor1', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent146', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent346', 'http://www.Department1.University0.edu/Course40')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent83', 'http://www.Department1.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent381', 'http://www.Department2.University0.edu/Course2')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent246', '"UndergraduateStudent246@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent282', 'http://www.Department1.University0.edu/Course0')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent153', '"UndergraduateStudent153@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor5/Publication4', 'http://www.Department0.University0.edu/GraduateStudent91')).
add('a1:mastersDegreeFrom'('http://www.Department1.University0.edu/FullProfessor5', 'http://www.University921.edu')).
add('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssistantProfessor4', 'http://www.University736.edu')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent414', 'http://www.Department1.University0.edu/Course32')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent142', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent42', 'http://www.Department1.University0.edu/Course17')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent17', 'http://www.Department2.University0.edu/FullProfessor4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent173', 'http://www.Department1.University0.edu/Course2')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent113', 'http://www.Department1.University0.edu/Course53')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication12', 'http://www.Department1.University0.edu/AssociateProfessor4')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent183', 'http://www.Department2.University0.edu/Course30')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor7/Publication0', 'http://www.Department1.University0.edu/AssistantProfessor7')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent312', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent224', 'http://www.Department2.University0.edu/Course43')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent92', 'http://www.Department1.University0.edu/Course26')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent236', 'http://www.Department1.University0.edu/FullProfessor0')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent109', 'http://www.Department2.University0.edu/GraduateCourse42')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent108', 'http://www.Department1.University0.edu/Course50')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor4/Publication11', 'http://www.Department1.University0.edu/FullProfessor4')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/Lecturer6', 'http://www.Department1.University0.edu/GraduateCourse47')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent277', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent22', 'http://www.Department2.University0.edu/Course14')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent157', 'http://www.Department0.University0.edu/Course44')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent219', 'http://www.Department0.University0.edu/Course38')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent79', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent194', '"UndergraduateStudent194@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent5', '"UndergraduateStudent5@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent128', 'http://www.Department1.University0.edu/Course41')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent4', 'http://www.Department1.University0.edu/AssociateProfessor7')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor6/Publication10', 'http://www.Department0.University0.edu/GraduateStudent73')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent172', 'http://www.Department1.University0.edu/Course21')).
delete('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent47', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent249', 'http://www.Department0.University0.edu/Course50')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication4', 'http://www.Department2.University0.edu/FullProfessor5')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department1.University0.edu/AssociateProfessor1')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent216', 'http://www.Department0.University0.edu/Course13')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent257', 'http://www.Department1.University0.edu/Course22')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor7/Publication1', 'http://www.Department1.University0.edu/AssociateProfessor7')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent70', 'http://www.Department0.University0.edu/Course3')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent105', '"GraduateStudent105@Department2.University0.edu"^^xsd:string')).
delete('a1:teachingAssistantOf'('http://www.Department1.University0.edu/GraduateStudent27', 'http://www.Department1.University0.edu/Course33')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent1', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent197', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent22', '"UndergraduateStudent22@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent297', 'http://www.Department1.University0.edu/Course4')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent391', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/AssociateProfessor6', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor7/Publication3', 'http://www.Department1.University0.edu/GraduateStudent10')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent263', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent435', 'http://www.Department1.University0.edu/Course44')).
