add('skos:broader'('a26:Category:University_of_Belgrade_Faculty_of_Philosophy_alumni', 'a26:Category:Philosophy_academics')).
add('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
add('skos:broader'('a26:Category:Indiana_politicians_by_party', 'a26:Category:Indiana_politicians')).
add('skos:broader'('a26:Category:French_silent_short_films', 'a26:Category:Silent_short_films')).
add('skos:broader'('a26:Category:Graphemes', 'a26:Category:Units_of_morphological_analysis')).
add('skos:broader'('a26:Category:Adaptations_of_works_by_Luigi_Pirandello', 'a26:Category:Adaptations_of_works_by_writer')).
add('skos:broader'('a26:Category:Documentary_films_about_homelessness_in_the_United_States', 'a26:Category:Documentary_films_about_poverty_in_the_United_States')).
add('skos:broader'('a26:Category:Aguadilla_Isabela_San_Sebastián_metropolitan_area', 'a26:Category:Metropolitan_areas_of_Puerto_Rico')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_water_polo_competitions_by_host')).
add('skos:broader'('a26:Category:Great_Officers_of_State_of_England', 'a26:Category:Great_Officers_of_State')).
add('skos:broader'('a26:Category:Graphical_user_interface_testing', 'a26:Category:Software_testing_tools')).
add('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Education_in_Alameda_County_California')).
add('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Visitor_attractions_in_Midlothian')).
add('skos:broader'('a26:Category:Peers', 'a26:Category:British_people_by_rank')).
add('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Abstract_algebra')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Analysis')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_the_South_Region_Brazil')).
add('skos:broader'('a26:Category:2009_in_Catalan_sport', 'a26:Category:2009_in_Spanish_sport')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Chemistry')).
add('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Woodwind_musicians')).
add('skos:broader'('a26:Category:Organizations_based_in_the_United_States_by_state', 'a26:Category:Organizations_by_country_subdivision')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_sports_competitions_hosted_by_France')).
add('skos:broader'('a26:Category:Landforms_of_Petersburg_Borough_Alaska', 'a26:Category:Geography_of_Petersburg_Borough_Alaska')).
add('skos:broader'('a26:Category:Companies_based_in_Atlanta_Georgia', 'a26:Category:Companies_based_in_Georgia_U.S._state_by_city')).
add('skos:broader'('a26:Category:Edmonton_Oilers_broadcasters', 'a26:Category:National_Hockey_League_broadcasters')).
add('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
add('skos:broader'('a26:Category:Houses_in_the_City_of_Westminster', 'a26:Category:Buildings_and_structures_in_the_City_of_Westminster')).
add('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1280s_in_England')).
add('skos:broader'('a26:Category:Theatres_in_New_York_City', 'a26:Category:Theatre_in_New_York_City')).
add('skos:broader'('a26:Category:Austrian_Football_Bundesliga_players', 'a26:Category:Association_football_players_by_competition')).
add('skos:broader'('a26:Category:Table_tennis_in_North_America', 'a26:Category:Sport_in_North_America_by_sport')).
add('skos:broader'('a26:Category:Screenshots_of_Windows_Server', 'a26:Category:Screenshots_of_Microsoft_Windows')).
add('skos:broader'('a26:Category:Woody_Guthrie', 'a26:Category:Guthrie_family')).
add('skos:broader'('a26:Category:Bender_Moldova', 'a26:Category:Districts_of_Moldova')).
add('skos:broader'('a26:Category:People_from_Madrid', 'a26:Category:Madrid')).
add('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Tourism_in_Ulsan')).
add('skos:broader'('a26:Category:A-Class_Museums_articles', 'a26:Category:A-Class_articles')).
add('skos:broader'('a26:Category:Płock_County', 'a26:Category:Land_counties_of_Masovian_Voivodeship')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Works_by_Brazilian_people')).
add('skos:broader'('a26:Category:Fashion_events_in_the_United_Kingdom', 'a26:Category:British_fashion')).
add('skos:broader'('a26:Category:Defunct_American_football_teams', 'a26:Category:Defunct_sports_teams')).
add('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Housing_in_the_United_Kingdom')).
add('skos:broader'('a26:Category:Bielsk_County', 'a26:Category:Land_counties_of_Podlaskie_Voivodeship')).
add('skos:broader'('a26:Category:Irish_entertainers', 'a26:Category:Entertainment_in_Ireland')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:History_of_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:Theatres_in_New_York_City', 'a26:Category:Visitor_attractions_in_New_York_City')).
add('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Islands_by_ocean_or_sea')).
add('skos:broader'('a26:Category:Films_shot_in_Hong_Kong', 'a26:Category:Hong_Kong_culture')).
add('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Software_engineering')).
add('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Peruvian_sportspeople')).
delete('skos:broader'('a26:Category:Works_set_on_the_London_Underground', 'a26:Category:London_Underground')).
delete('skos:broader'('a26:Category:Injuries_of_ankle_and_foot', 'a26:Category:Injuries_by_region_of_body')).
delete('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Dog_breeding')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:1977_in_British_Columbia')).
delete('skos:broader'('a26:Category:North_American_culture_by_country', 'a26:Category:North_American_culture')).
delete('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Topology')).
delete('skos:broader'('a26:Category:Transportation_in_Maine_by_county', 'a26:Category:Maine_counties')).
delete('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_in_Ontario')).
delete('skos:broader'('a26:Category:Turkish_Football_Federation_presidents', 'a26:Category:Turkish_Football_Federation')).
delete('skos:broader'('a26:Category:2012_television_films', 'a26:Category:2012_films')).
delete('skos:broader'('a26:Category:Nama_people', 'a26:Category:Namibian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:Soap_opera_actors_by_nationality', 'a26:Category:Television_actors_by_nationality')).
delete('skos:broader'('a26:Category:Member_states_of_the_United_Nations', 'a26:Category:Member_states_by_organization')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_Brazil_by_state')).
delete('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:Establishments_in_British_Columbia_by_year')).
delete('skos:broader'('a26:Category:Scots_law_formal_titles', 'a26:Category:Scottish_titles')).
delete('skos:broader'('a26:Category:Albums_by_Ugandan_artists', 'a26:Category:Works_by_Ugandan_people')).
delete('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:19th_century_in_England')).
delete('skos:broader'('a26:Category:KMFDM', 'a26:Category:Wikipedia_categories_named_after_German_musical_groups')).
delete('skos:broader'('a26:Category:Mythological_sword_fighters', 'a26:Category:Mythological_characters')).
delete('skos:broader'('a26:Category:MCG_objects', 'a26:Category:MCG_objects')).
delete('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Mammal_breeds')).
delete('skos:broader'('a26:Category:Iowa_Libertarians', 'a26:Category:Libertarian_Party_United_States_politicians')).
delete('skos:broader'('a26:Category:MCG_objects', 'a26:Category:Astronomical_catalogues')).
delete('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Scottish_architecture')).
delete('skos:broader'('a26:Category:Cyclists_from_Western_Australia', 'a26:Category:Sportspeople_from_Western_Australia_by_sport')).
delete('skos:broader'('a26:Category:Conglomerate_companies_of_France', 'a26:Category:Conglomerate_companies_by_country')).
delete('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Visitor_attractions_in_South_Korea_by_city')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Musicians_by_instrument')).
delete('skos:broader'('a26:Category:Exoplanet_catalogues', 'a26:Category:Exoplanetology')).
delete('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Cinema_of_Brazil')).
delete('skos:broader'('a26:Category:People_from_Madrid', 'a26:Category:Madrilenian_people')).
delete('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Geography_of_Los_Angeles_County_California')).
delete('skos:broader'('a26:Category:British_adventure_films', 'a26:Category:British_films_by_genre')).
delete('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Universities_and_colleges_in_California_by_county')).
delete('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Films_by_country')).
delete('skos:broader'('a26:Category:Roman_Catholic_Church_in_Slovakia', 'a26:Category:Roman_Catholic_Church_in_Europe')).
delete('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Footballers_in_Italy_by_club')).
delete('skos:broader'('a26:Category:The_Independent_people', 'a26:Category:The_Independent')).
delete('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Parma_FC')).
delete('skos:broader'('a26:Category:Populated_places_in_Galikash_County', 'a26:Category:Populated_places_in_Golestan_Province')).
delete('skos:broader'('a26:Category:Explosions_in_England', 'a26:Category:Disasters_in_England')).
delete('skos:broader'('a26:Category:Geography_of_Greene_County_New_York', 'a26:Category:Geography_of_the_Hudson_Valley')).
delete('skos:broader'('a26:Category:Ethnic_groups_in_Arizona', 'a26:Category:Ethnic_groups_in_the_United_States_by_state')).
delete('skos:broader'('a26:Category:Association_football_international_competitions_squad_navigational_boxes', 'a26:Category:Association_football_international_competitions_navigational_boxes')).
delete('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
delete('skos:broader'('a26:Category:Screenshots_of_Windows_Server', 'a26:Category:Windows_Server')).
delete('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Romani_in_Italy')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_rulers')).
