add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent221')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent91')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent187')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent160')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent79')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent8')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent352')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor0')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse28')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
