add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent123')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent256')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent303')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent338')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent305')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent162')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse8')).
