add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent352')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent362')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent249')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent110')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent214')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent9')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent303')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent88')).
