add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor1')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent270')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent240')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent73')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent173')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent32')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent41')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent201')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent29')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent391')).
