add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent90')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse14')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent403')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent280')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent359')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent75')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent376')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent75')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent186')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent281')).
