add('skos:broader'('a26:Category:Former_country_articles_requiring_restructuring', 'a26:Category:WikiProject_Former_countries')).
add('skos:broader'('a26:Category:Conspiracy_theories', 'a26:Category:Fringe_theory')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Historic_districts_in_Pennsylvania_by_county')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs_in_Asia')).
add('skos:broader'('a26:Category:Adaptations_of_works_by_Luigi_Pirandello', 'a26:Category:Adaptations_of_works_by_writer')).
add('skos:broader'('a26:Category:Monument_types', 'a26:Category:Archaeology_of_structures')).
add('skos:broader'('a26:Category:MCG_objects', 'a26:Category:Astronomical_catalogues')).
add('skos:broader'('a26:Category:Bender_Moldova', 'a26:Category:Districts_of_Moldova')).
add('skos:broader'('a26:Category:Aguadilla_Isabela_San_Sebastián_metropolitan_area', 'a26:Category:Metropolitan_areas_of_Puerto_Rico')).
add('skos:broader'('a26:Category:Dukes_of_Choiseul', 'a26:Category:Dukes_of_France')).
add('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Visitor_attractions_in_South_Korea_by_city')).
add('skos:broader'('a26:Category:Culture_by_language', 'a26:Category:Cultures')).
add('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_in_Ontario')).
add('skos:broader'('a26:Category:Buddhist_titles', 'a26:Category:Titles')).
add('skos:broader'('a26:Category:Turkish_Football_Federation_presidents', 'a26:Category:Turkish_Football_Federation')).
add('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_sculptors')).
add('skos:broader'('a26:Category:Defunct_American_football_teams', 'a26:Category:Defunct_sports_teams')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Heads_of_state_in_the_Middle_East')).
add('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Housing_in_the_United_Kingdom')).
add('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Parma_FC')).
add('skos:broader'('a26:Category:2009_in_Catalan_sport', 'a26:Category:2009_in_Spanish_sport')).
add('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Islands_by_ocean_or_sea')).
add('skos:broader'('a26:Category:Geography_of_Greene_County_New_York', 'a26:Category:Geography_of_the_Hudson_Valley')).
add('skos:broader'('a26:Category:Association_football_international_competitions_squad_navigational_boxes', 'a26:Category:Association_football_international_competitions_navigational_boxes')).
add('skos:broader'('a26:Category:Companies_based_in_Atlanta_Georgia', 'a26:Category:Companies_based_in_Georgia_U.S._state_by_city')).
add('skos:broader'('a26:Category:Treaties_of_the_Grand_Duchy_of_Hesse', 'a26:Category:Treaties_of_Germany')).
add('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Clarinets')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_rulers')).
add('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Romani_in_Italy')).
delete('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
delete('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Populated_places_in_California_by_county')).
delete('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Archaeological_sites_in_Egypt')).
delete('skos:broader'('a26:Category:Table_tennis_in_North_America', 'a26:Category:Sport_in_North_America_by_sport')).
delete('skos:broader'('a26:Category:MCG_objects', 'a26:Category:MCG_objects')).
delete('skos:broader'('a26:Category:Iowa_Libertarians', 'a26:Category:Libertarian_Party_United_States_politicians')).
delete('skos:broader'('a26:Category:Monument_types', 'a26:Category:Monuments_and_memorials')).
delete('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Italian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:African_culture_by_nationality', 'a26:Category:Culture_by_nationality')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Musicians_by_instrument')).
delete('skos:broader'('a26:Category:Great_Officers_of_State_of_England', 'a26:Category:Great_Officers_of_State')).
delete('skos:broader'('a26:Category:Exoplanet_catalogues', 'a26:Category:Exoplanetology')).
delete('skos:broader'('a26:Category:Płock_County', 'a26:Category:Land_counties_of_Masovian_Voivodeship')).
delete('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Geography_of_Los_Angeles_County_California')).
delete('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Visitor_attractions_in_Midlothian')).
delete('skos:broader'('a26:Category:African_culture_by_nationality', 'a26:Category:African_culture')).
delete('skos:broader'('a26:Category:British_adventure_films', 'a26:Category:British_films_by_genre')).
delete('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Films_by_country')).
delete('skos:broader'('a26:Category:Irish_entertainers', 'a26:Category:Entertainment_in_Ireland')).
delete('skos:broader'('a26:Category:British_tubists', 'a26:Category:Tubists_by_nationality')).
delete('skos:broader'('a26:Category:Theatres_in_New_York_City', 'a26:Category:Visitor_attractions_in_New_York_City')).
delete('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Chemistry')).
delete('skos:broader'('a26:Category:Member_states_of_the_United_Nations', 'a26:Category:Member_states_by_organization')).
delete('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Computer_languages')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_Brazil_by_state')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Woodwind_musicians')).
delete('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_sports_competitions_hosted_by_France')).
delete('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
delete('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
