add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent123')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent101')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent61')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent79')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent330')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent305')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent28')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent256')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent205')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent412')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent103')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse34')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent234')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent240')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent362')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent343')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent33')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent34')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent206')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent11')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse23')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent56')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent78')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent20')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent254')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse40')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent91')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent214')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent249')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent248')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent338')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse8')).
