add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent86')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent167')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent56')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent320')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent116')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent88')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent148')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent129')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent69')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent304')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent346')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent382')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent96')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent32')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent61')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent413')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent339')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent251')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse18')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent30')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent404')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent35')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent87')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent89')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent255')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent77')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent91')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent34')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse31')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse34')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent7')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent236')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer3')).
