add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent73')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent104')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent115')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent357')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent35')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse21')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent17')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent224')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent247')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent282')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent107')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse7')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent46')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent105')).
add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor2')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent230')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent7')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent404')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse12')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent50')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent67')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent94')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent192')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent101')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent18')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent33')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent267')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent292')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent291')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent39')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent251')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent223')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent261')).
