add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent8')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent66')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent144')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor12')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent183')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent26')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent78')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent52')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent323')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent32')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent287')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent254')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent100')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse34')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse26')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent129')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent241')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent240')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent146')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent31')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent122')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent356')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent187')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent9')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent88')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent58')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent181')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent91')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent248')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent23')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent89')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent272')).
