add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent56')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent106')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse12')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor11')).
add('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer4')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent71')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent362')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent224')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent97')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent34')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse41')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent292')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent236')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent71')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse27')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse18')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent320')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent113')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent135')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent105')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent313')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent335')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent395')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent300')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent255')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent87')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent61')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent71')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent339')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer3')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent9')).
