add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent32')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent380')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent210')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent306')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent2')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent101')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent252')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent440')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor5')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent61')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent48')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent6')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse24')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent2')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent84')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent393')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent395')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent42')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent243')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent48')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent203')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse39')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent73')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent16')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent74')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse14')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent117')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent128')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent303')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent174')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent345')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent174')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent151')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent276')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent35')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent93')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent215')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent60')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent314')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent67')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent140')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent269')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent26')).
add('a1:AssistantProfessor'('http://www.Department1.University0.edu/AssistantProfessor4')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent70')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent200')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent340')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent406')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent239')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent175')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse1')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent50')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent380')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent256')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent214')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent214')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent252')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent101')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent311')).
add('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor3')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent120')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent266')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent0')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent226')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent262')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent241')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent54')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent53')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent195')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse31')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent35')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent91')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent259')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent236')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent102')).
add('a1:Department'('http://www.Department1.University0.edu')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent418')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent107')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent25')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent392')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent29')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor3')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent206')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent82')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent28')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent11')).
