add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent276')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent120')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse41')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent306')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent287')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent128')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent24')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor3')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent250')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent168')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent276')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent46')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent355')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent344')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent12')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent207')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent78')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent383')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent242')).
