add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent168')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent95')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent46')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent355')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent344')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent347')).
add('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor1')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent50')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent430')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent232')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent210')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent107')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse14')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse24')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
delete('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor6')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent25')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent392')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor5')).
