add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse18')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent168')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent276')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent21')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent95')).
add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent62')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent64')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent57')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse37')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent269')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent120')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse41')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent306')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent287')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent118')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent48')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent183')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent108')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent125')).
