add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent209')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent120')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse41')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent306')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent287')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent107')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent12')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent383')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent250')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse18')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent71')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent51')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent195')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent48')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent239')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse31')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent67')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent42')).
