add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent26')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent60')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent53')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent206')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent226')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent80')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent29')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent252')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent61')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent243')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent168')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent101')).
delete('a1:Department'('http://www.Department1.University0.edu')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent35')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent252')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent200')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent120')).
