add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent169')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent285')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent73')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent400')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent65')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent118')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent207')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent183')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent242')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent210')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent35')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent380')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent252')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent200')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent174')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent120')).
