add('skos:broader'('a26:Category:North_American_culture_by_country', 'a26:Category:North_American_culture')).
add('skos:broader'('a26:Category:Albums_by_Ugandan_artists', 'a26:Category:Works_by_Ugandan_people')).
add('skos:broader'('a26:Category:Fashion_events_in_the_United_Kingdom', 'a26:Category:British_fashion')).
add('skos:broader'('a26:Category:Scots_law_formal_titles', 'a26:Category:Scots_law')).
add('skos:broader'('a26:Category:Graphical_user_interface_testing', 'a26:Category:Software_testing_tools')).
add('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publisher')).
add('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Non-metropolitan_districts_of_Somerset')).
add('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
add('skos:broader'('a26:Category:Ethnic_groups_in_Arizona', 'a26:Category:Ethnic_groups_in_the_United_States_by_state')).
add('skos:broader'('a26:Category:Geography_of_the_Northern_Territory', 'a26:Category:Geography_of_Australia_by_state_or_territory')).
delete('skos:broader'('a26:Category:Northwest_Territories_territorial_electoral_districts', 'a26:Category:Canadian_provincial_and_territorial_electoral_districts')).
delete('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Works_by_Brazilian_people')).
delete('skos:broader'('a26:Category:University_of_Belgrade_Faculty_of_Philosophy_alumni', 'a26:Category:Philosophy_academics')).
delete('skos:broader'('a26:Category:2nd_millennium_in_South_Carolina', 'a26:Category:2nd_millennium_in_the_United_States')).
delete('skos:broader'('a26:Category:Indiana_Whigs', 'a26:Category:Whig_Party_United_States_politicians')).
delete('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Peruvian_sportspeople')).
delete('skos:broader'('a26:Category:Bielsk_County', 'a26:Category:Land_counties_of_Podlaskie_Voivodeship')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Geography_of_Rio_Grande_do_Sul')).
delete('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Tourism_in_Ulsan')).
delete('skos:broader'('a26:Category:Redirects_with_possibilities', 'a26:Category:Redirects_from_subtopics')).
