add('skos:broader'('a26:Category:Injuries_of_ankle_and_foot', 'a26:Category:Injuries_by_region_of_body')).
add('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Parma_FC')).
add('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Sport_shooters_by_nationality')).
add('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
add('skos:broader'('a26:Category:Major_League_Baseball_players_with_retired_numbers', 'a26:Category:Major_League_Baseball_players')).
add('skos:broader'('a26:Category:Organizations_based_in_the_United_States_by_state', 'a26:Category:Organizations_based_in_the_United_States')).
add('skos:broader'('a26:Category:Table_tennis_in_North_America', 'a26:Category:Sport_in_North_America_by_sport')).
add('skos:broader'('a26:Category:Turkish_Football_Federation_presidents', 'a26:Category:Turkish_Football_Federation')).
add('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Buildings_and_structures_in_Midlothian')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Cinema_of_Brazil')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:1977_in_British_Columbia')).
delete('skos:broader'('a26:Category:People_from_Madrid', 'a26:Category:Madrid')).
delete('skos:broader'('a26:Category:North_American_culture_by_country', 'a26:Category:North_American_culture')).
delete('skos:broader'('a26:Category:Populated_places_in_Galikash_County', 'a26:Category:Populated_places_in_Golestan_Province')).
delete('skos:broader'('a26:Category:People_from_the_Las_Vegas_Valley', 'a26:Category:People_by_populated_place_in_Nevada')).
delete('skos:broader'('a26:Category:American_Airlines_people', 'a26:Category:American_Airlines')).
delete('skos:broader'('a26:Category:British_adventure_films', 'a26:Category:British_films_by_genre')).
delete('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Non-metropolitan_districts_of_Somerset')).
delete('skos:broader'('a26:Category:Conglomerate_companies_of_France', 'a26:Category:Companies_of_France')).
delete('skos:broader'('a26:Category:Songwriters_from_Texas', 'a26:Category:Musicians_from_Texas')).
