add('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Italian_people_by_ethnic_or_national_origin')).
add('skos:broader'('a26:Category:Soap_opera_actors_by_nationality', 'a26:Category:Categories_by_nationality')).
add('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Parma_FC')).
add('skos:broader'('a26:Category:Five-year_plans', 'a26:Category:Economic_planning')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Chemistry')).
add('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
add('skos:broader'('a26:Category:Arab_people_of_the_Arab_Byzantine_wars', 'a26:Category:People_of_the_Arab_Byzantine_wars')).
add('skos:broader'('a26:Category:Mythological_sword_fighters', 'a26:Category:Mythological_characters')).
add('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:British_businesspeople')).
add('skos:broader'('a26:Category:Geography_of_the_Northern_Territory', 'a26:Category:Geography_of_Australia_by_state_or_territory')).
delete('skos:broader'('a26:Category:Monument_types', 'a26:Category:Monuments_and_memorials')).
delete('skos:broader'('a26:Category:2nd_millennium_in_South_Carolina', 'a26:Category:2nd_millennium_in_the_United_States')).
delete('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Topology')).
delete('skos:broader'('a26:Category:KMFDM', 'a26:Category:Wikipedia_categories_named_after_German_musical_groups')).
delete('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publishing_company_of_the_United_States')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_Brazil_by_state')).
delete('skos:broader'('a26:Category:Treaties_of_the_Grand_Duchy_of_Hesse', 'a26:Category:Treaties_of_Germany')).
delete('skos:broader'('a26:Category:Literary_motifs', 'a26:Category:Elements_of_fiction')).
delete('skos:broader'('a26:Category:Edmonton_Oilers_broadcasters', 'a26:Category:National_Hockey_League_broadcasters')).
delete('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Romani_in_Italy')).
