add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent220')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent47')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent247')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent357')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent65')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse11')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent282')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent71')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent191')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse17')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent113')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent69')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
delete('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer4')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer3')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent170')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent162')).
