add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent122')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent330')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent244')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent21')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor5')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent119')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent223')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent4')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent141')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent125')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent313')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse34')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse44')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse7')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent89')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor3')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse49')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent69')).
