add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent90')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent267')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent122')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent116')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse9')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent179')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent303')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent108')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent123')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent355')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent148')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent254')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent80')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent162')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent53')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
