add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent34')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent183')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent26')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent123')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent190')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent401')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent42')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent146')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent352')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent287')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent215')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent28')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent102')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent338')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent321')).
