add('skos:broader'('a26:Category:British_folk_rock_groups', 'a26:Category:British_folk_music_groups')).
add('skos:broader'('a26:Category:Serbian_sport_wrestlers', 'a26:Category:Sport_wrestlers_by_nationality')).
add('skos:broader'('a26:Category:United_States_Air_Force_generals', 'a26:Category:United_States_Air_Force_officers')).
add('skos:broader'('a26:Category:Kentucky_Republicans', 'a26:Category:Kentucky_politicians_by_party')).
add('skos:broader'('a26:Category:1980s_in_Laos', 'a26:Category:1980s_in_Asia')).
add('skos:broader'('a26:Category:Songs_written_by_Tricky_Stewart', 'a26:Category:Songs_by_songwriter')).
add('skos:broader'('a26:Category:Private_equity', 'a26:Category:Financial_markets')).
add('skos:broader'('a26:Category:Indiana_Jacksonians', 'a26:Category:Indiana_politicians_by_party')).
add('skos:broader'('a26:Category:History_of_Leon_County_Florida', 'a26:Category:Leon_County_Florida')).
add('skos:broader'('a26:Category:American_punk_rock_groups', 'a26:Category:American_punk_groups')).
delete('skos:broader'('a26:Category:Weightlifting_in_South_America', 'a26:Category:Sport_in_South_America_by_sport')).
delete('skos:broader'('a26:Category:Transport_in_Cochrane_District', 'a26:Category:Cochrane_District')).
delete('skos:broader'('a26:Category:Ruins_in_Derbyshire', 'a26:Category:Archaeological_sites_in_Derbyshire')).
delete('skos:broader'('a26:Category:Art_museums_established_in_1723', 'a26:Category:Art_museums_by_year_of_establishment')).
delete('skos:broader'('a26:Category:20th-century_French_mathematicians', 'a26:Category:20th-century_mathematicians_by_nationality')).
delete('skos:broader'('a26:Category:Members_of_the_Corps_législatif_of_the_Second_French_Empire', 'a26:Category:Members_of_the_Corps_législatif')).
delete('skos:broader'('a26:Category:Populated_places_on_the_Columbia_River', 'a26:Category:Populated_places_in_Washington_state')).
delete('skos:broader'('a26:Category:Native_American_poets', 'a26:Category:American_poets_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:Vietnam_War_sites', 'a26:Category:Military_locations')).
delete('skos:broader'('a26:Category:Shy_Nobleman_albums', 'a26:Category:Indie_rock_albums_by_Israeli_artists')).
