add('skos:broader'('a26:Category:Ming_dynasty_literature', 'a26:Category:Ming_dynasty')).
add('skos:broader'('a26:Category:International_club_association_football_competitions_hosted_by_Venezuela', 'a26:Category:International_club_association_football_competitions_in_South_America_by_host')).
add('skos:broader'('a26:Category:Organizations_based_in_Denmark', 'a26:Category:Danish_society')).
add('skos:broader'('a26:Category:Canadian_reality_television_series', 'a26:Category:Canadian_television_series_by_genre')).
add('skos:broader'('a26:Category:Denmark_Germany_border_crossings', 'a26:Category:Border_crossings_of_Germany')).
add('skos:broader'('a26:Category:Ahi_political_party_politicians', 'a26:Category:Politicians_of_Jewish_political_parties')).
add('skos:broader'('a26:Category:American_Seventh-day_Adventists', 'a26:Category:Seventh-day_Adventists_by_nationality')).
add('skos:broader'('a26:Category:1970s_in_Laos', 'a26:Category:20th_century_in_Laos')).
add('skos:broader'('a26:Category:Ambassadors_of_Ukraine', 'a26:Category:Foreign_relations_of_Ukraine')).
add('skos:broader'('a26:Category:People_from_Dalarna', 'a26:Category:Dalarna')).
delete('skos:broader'('a26:Category:Art_museums_established_in_1723', 'a26:Category:Museums_established_in_1723')).
delete('skos:broader'('a26:Category:Constitutional_laws_of_Scotland', 'a26:Category:Scottish_laws')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Musicians_by_instrument')).
delete('skos:broader'('a26:Category:Claremont_McKenna_College_alumni', 'a26:Category:Claremont_McKenna_College')).
delete('skos:broader'('a26:Category:Villages_in_Bulgaria', 'a26:Category:Populated_places_in_Bulgaria')).
delete('skos:broader'('a26:Category:Pacific_Ocean_theatre_of_World_War_II', 'a26:Category:Military_of_Oceania')).
delete('skos:broader'('a26:Category:People_from_Birmingham_Alabama', 'a26:Category:People_by_city_in_Alabama')).
delete('skos:broader'('a26:Category:Expatriate_footballers_in_Italy', 'a26:Category:Expatriate_sportspeople_in_Italy')).
delete('skos:broader'('a26:Category:Ōsu', 'a26:Category:Visitor_attractions_in_Nagoya')).
delete('skos:broader'('a26:Category:Australian_television_sitcoms', 'a26:Category:Sitcoms_by_country')).
