add('skos:broader'('a26:Category:Pipe_organ', 'a26:Category:Aerophones')).
add('skos:broader'('a26:Category:2000_in_Maryland', 'a26:Category:2000s_in_Maryland')).
add('skos:broader'('a26:Category:Cemeteries_in_Massachusetts', 'a26:Category:Visitor_attractions_in_Massachusetts')).
add('skos:broader'('a26:Category:Ancient_astronomy', 'a26:Category:History_of_astrology')).
add('skos:broader'('a26:Category:Comics_characters_by_creator', 'a26:Category:Fictional_characters_by_creator')).
add('skos:broader'('a26:Category:Asian_Games_medalists_in_judo', 'a26:Category:Judo_at_the_Asian_Games')).
add('skos:broader'('a26:Category:Languages_of_Bolivia', 'a26:Category:Languages_by_country')).
add('skos:broader'('a26:Category:Dams_completed_in_1994', 'a26:Category:Dams_by_year_of_completion')).
add('skos:broader'('a26:Category:Defunct_ice_hockey_teams_in_Alabama', 'a26:Category:Defunct_sports_teams_in_Alabama')).
add('skos:broader'('a26:Category:Marxist_books', 'a26:Category:Books_by_ideology')).
delete('skos:broader'('a26:Category:Priority_Records_artists', 'a26:Category:Artists_by_record_label')).
delete('skos:broader'('a26:Category:Wikipedia_categories_named_after_Indian_writers', 'a26:Category:Wikipedia_categories_named_after_Indian_people')).
delete('skos:broader'('a26:Category:Female_long-distance_runners', 'a26:Category:Long-distance_runners')).
delete('skos:broader'('a26:Category:American_essayists', 'a26:Category:American_writers_by_genre')).
delete('skos:broader'('a26:Category:Education_in_Springfield_Missouri', 'a26:Category:Education_in_the_United_States_by_city_or_town')).
delete('skos:broader'('a26:Category:Stadiums_in_Zimbabwe', 'a26:Category:Buildings_and_structures_in_Zimbabwe')).
delete('skos:broader'('a26:Category:Prix_de_Rome_for_sculpture', 'a26:Category:Sculpture_awards')).
delete('skos:broader'('a26:Category:Seismic_faults_of_Chile', 'a26:Category:Seismic_faults_of_South_America')).
delete('skos:broader'('a26:Category:Documentary_films_about_the_film_industry', 'a26:Category:Documentary_films_about_the_arts')).
delete('skos:broader'('a26:Category:Toyota_Racing_Series_drivers', 'a26:Category:Toyota_Racing_Series')).
