add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1341527&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=2092265&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=531418&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=386414')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1900254')).
add('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/orange')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=608453')).
add('a1:E48_Place_Name'('http://arachne.uni-koeln.de/vocabulary/depository#via-appia')).
add('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/efsos_harabeler')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1341360')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=832267&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=641693')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1251984&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=789988')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1944780')).
delete('a1:E38_Image'('http://www.waa.ox.ac.uk/XDB/images/world/egypt/1326.jpg')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1341513')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/kaisariani')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=796989&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://www.waa.ox.ac.uk/XDB/images/world/egypt/1331.jpg')).
