add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent386')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent156')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent406')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent369')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent218')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent27')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent212')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent128')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor7')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor7')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent440')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent419')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent107')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent164')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent268')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent14')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse23')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent85')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent345')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent195')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent197')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse4')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent153')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent259')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent93')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse15')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent100')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent188')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent70')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse25')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent269')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse46')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse48')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent104')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent284')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent90')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent171')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent38')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent37')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent168')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent313')).
delete('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent181')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent249')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent264')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent249')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse46')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent128')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent76')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent92')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent199')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent428')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent347')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent14')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent211')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent278')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent299')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent90')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent80')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent437')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent11')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent206')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent180')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent310')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent6')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent64')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
