add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent147')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent147')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent217')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent53')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent15')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent220')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent359')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent212')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent240')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent294')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent28')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent90')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent137')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent32')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent426')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent403')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent82')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent320')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent222')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent79')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent245')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse0')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent87')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent8')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent281')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
