add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent147')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent90')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent334')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse14')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent102')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent18')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent151')).
add('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor0')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent75')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent271')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent436')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent281')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent201')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse19')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent132')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent66')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent31')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent2')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent395')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent29')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent256')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent267')).
delete('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor1')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent59')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent34')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent8')).
delete('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor1')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent253')).
