add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent137')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent135')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent416')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse33')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent40')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent53')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent2')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent99')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent395')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent383')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent267')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse36')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent253')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent351')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent147')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent48')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent55')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent78')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent51')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent242')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
delete('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor0')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent436')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent87')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent294')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse19')).
