add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent48')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse14')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent54')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent381')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent51')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent29')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse41')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent59')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent271')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent281')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent270')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse19')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse18')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent137')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent131')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent1')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent2')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent53')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent383')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent123')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent173')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent194')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent391')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent222')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent273')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent29')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse29')).
