add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent93')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent46')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent429')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent302')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent400')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent326')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor4')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent119')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent350')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent173')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent149')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent81')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent308')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent12')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent71')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent45')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent63')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent301')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent272')).
