add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent363')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent70')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent377')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent32')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent400')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent302')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent107')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent62')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent31')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent243')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent55')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent110')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent149')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent78')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent46')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent214')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent20')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer4')).
