add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent363')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent57')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent305')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent42')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent98')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent45')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent63')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent173')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent279')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent179')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent18')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent248')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent399')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent16')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse45')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent45')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent35')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer2')).
