add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent363')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent93')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent103')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent64')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent109')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent430')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent63')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent64')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent279')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent46')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent11')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent248')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent399')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent109')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent35')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent78')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer4')).
