add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent133')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent66')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent131')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent41')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent31')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent75')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent78')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent12')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent383')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent72')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent32')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent18')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent320')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent18')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent59')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent2')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent271')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent351')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse13')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent144')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent29')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent20')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent267')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent264')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent319')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent280')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor13')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent34')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent8')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent281')).
add('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor1')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent201')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse19')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent57')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent70')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent159')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent217')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent54')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent99')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent51')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent170')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent256')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent59')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent75')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent212')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent274')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent38')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent294')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent48')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent334')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent49')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent40')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent60')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent395')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent220')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent246')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent286')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent288')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent359')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse47')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent280')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent51')).
