add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent32')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent135')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent159')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent79')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse14')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent403')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent41')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent31')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent55')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor12')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent381')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent173')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent79')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent8')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent48')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent77')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent23')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent102')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent2')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent351')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent269')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent242')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent246')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent249')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse41')).
add('a1:Department'('http://www.Department0.University0.edu')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
add('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor1')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent133')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse18')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent137')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent70')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse13')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent35')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent347')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse12')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent54')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent99')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent382')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent383')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent18')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent194')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse0')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent292')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse32')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent91')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent374')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse0')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse1')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse13')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent144')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent378')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent82')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent46')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent80')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent29')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent68')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent436')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent87')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent201')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent280')).
