add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse19')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent92')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent345')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent199')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse4')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent384')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor7')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent100')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent68')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent419')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent125')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
add('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor6')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent220')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse46')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent9')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent130')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent386')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent90')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent127')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent38')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent232')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent278')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent79')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor7')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent2')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent424')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse37')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent210')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent23')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent188')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse25')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent437')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent80')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent313')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent181')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent49')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent268')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent14')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent64')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
