add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent77', 'http://www.Department2.University0.edu/Course16')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor3/Publication10', 'http://www.Department1.University0.edu/FullProfessor3')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication9', 'http://www.Department1.University0.edu/GraduateStudent78')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent29', 'http://www.Department2.University0.edu/GraduateCourse26')).
add('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor3', 'http://www.Department1.University0.edu/Course6')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor0/Publication13', 'http://www.Department0.University0.edu/FullProfessor0')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent233', 'http://www.Department2.University0.edu/Course11')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent61', 'http://www.Department0.University0.edu/Course41')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication11', 'http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent82', 'http://www.Department1.University0.edu/GraduateCourse38')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent266', '"UndergraduateStudent266@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent131', 'http://www.Department1.University0.edu/Course47')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication6', 'http://www.Department0.University0.edu/AssistantProfessor7')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent237', '"UndergraduateStudent237@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent339', 'http://www.Department2.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent104', 'http://www.Department2.University0.edu/Course4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent80', 'http://www.Department1.University0.edu/Course3')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent195', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/AssociateProfessor10', 'http://www.University983.edu')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent339', '"UndergraduateStudent339@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor7/Publication2', 'http://www.Department1.University0.edu/AssistantProfessor7')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent87', 'http://www.Department0.University0.edu/Course35')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent98', 'http://www.Department2.University0.edu/GraduateCourse36')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent372', 'http://www.Department2.University0.edu/Course5')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor11/Publication5', 'http://www.Department2.University0.edu/GraduateStudent86')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent116', 'http://www.Department0.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent262', 'http://www.Department1.University0.edu/Course52')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent442', 'http://www.Department1.University0.edu/Course13')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent14', '"GraduateStudent14@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent61', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent138', 'http://www.Department0.University0.edu/Course7')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/Lecturer2/Publication2', 'http://www.Department2.University0.edu/Lecturer2')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent104', '"UndergraduateStudent104@Department1.University0.edu"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/AssociateProfessor5', 'http://www.University675.edu')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication5', 'http://www.Department0.University0.edu/GraduateStudent76')).
add('a1:doctoralDegreeFrom'('http://www.Department2.University0.edu/Lecturer0', 'http://www.University821.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent53', '"UndergraduateStudent53@Department1.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent405', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent399', '"UndergraduateStudent399@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent133', 'http://www.Department0.University0.edu/Course26')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent246', 'http://www.Department2.University0.edu/Course31')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent227', '"UndergraduateStudent227@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent113', '"UndergraduateStudent113@Department2.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent148', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor5/Publication6', 'http://www.Department2.University0.edu/AssistantProfessor5')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent254', 'http://www.Department1.University0.edu/AssociateProfessor6')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent201', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent92', 'http://www.Department0.University0.edu/Course12')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent346', '"UndergraduateStudent346@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent83', 'http://www.Department1.University0.edu/GraduateCourse29')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent87', 'http://www.University727.edu')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent142', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent75', 'http://www.Department2.University0.edu/Course19')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent17', '"GraduateStudent17@Department0.University0.edu"^^xsd:string')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/Lecturer1', 'http://www.Department0.University0.edu/GraduateCourse46')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/Lecturer1', 'http://www.Department0.University0.edu/Course45')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent200', 'http://www.Department1.University0.edu/Course36')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent115', 'http://www.Department0.University0.edu/Course0')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor0/Publication1', 'http://www.Department0.University0.edu/GraduateStudent39')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/Lecturer1', 'http://www.Department2.University0.edu/GraduateCourse44')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent245', 'http://www.Department2.University0.edu/Course37')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent88', 'http://www.Department0.University0.edu/GraduateCourse37')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent4', '"GraduateStudent4@Department1.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent141', 'http://www.Department0.University0.edu/AssociateProfessor9')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication2', 'http://www.Department2.University0.edu/GraduateStudent43')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent44', '"UndergraduateStudent44@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent420', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent92', 'http://www.Department1.University0.edu/AssistantProfessor0')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent109', '"UndergraduateStudent109@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent130', 'http://www.Department1.University0.edu/Course39')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent43', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent199', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent29', 'http://www.Department0.University0.edu/GraduateCourse26')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent259', 'http://www.Department1.University0.edu/Course2')).
delete('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent265', 'http://www.Department2.University0.edu/AssistantProfessor8')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent40', '"GraduateStudent40@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent32', 'http://www.Department2.University0.edu/Course0')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor4/Publication11', 'http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent114', '"GraduateStudent114@Department1.University0.edu"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent1', 'http://www.University964.edu')).
