add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=488853')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=469132&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=941793')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=722516')).
add('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/cavdarhisar')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=448479')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1341470')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1663317')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=634043&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=647481&method=min&width=141&height=111')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/metapontum')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=803411')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=3779717')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/golhisar')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=493898&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=809264')).
delete('a1:E48_Place_Name'('http://arachne.uni-koeln.de/vocabulary/place#ka-r-abu-elal')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=641144')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=3424412')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1718529')).
