add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent73')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent300')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent152')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent77')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent236')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent7')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent69')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent62')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse17')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent209')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent104')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent417')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent69')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse21')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent119')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent224')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent225')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor0')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent4')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent136')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent170')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent38')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent91')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse31')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent349')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent291')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent423')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent329')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent250')).
delete('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor2')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer3')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent7')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent229')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent313')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent65')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent44')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent87')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent220')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent61')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent247')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent282')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent129')).
