add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent113')).
add('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer4')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse11')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent53')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent97')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent292')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent329')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent62')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent357')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent229')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent335')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent89')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent67')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent44')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent87')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse41')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent286')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent86')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent115')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor11')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent239')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent94')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent17')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
delete('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor2')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent233')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse16')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse17')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent211')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent209')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent148')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent65')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent61')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse34')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent413')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent105')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
