add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent115')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent101')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent175')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent362')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent73')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent39')).
add('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer3')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent125')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent354')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent148')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent129')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent69')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent229')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent310')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent43')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent21')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent339')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent79')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent217')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent346')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent96')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent53')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent292')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent292')).
delete('a1:Department'('http://www.Department1.University0.edu')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent330')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent209')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent121')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent106')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent119')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent88')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent87')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent47')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent244')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent107')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent206')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse7')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent240')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent223')).
