add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse12')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent217')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent346')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent382')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent255')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent292')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent292')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent92')).
add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor2')).
add('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer3')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse17')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent125')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent22')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent69')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent106')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent119')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent141')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent247')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent30')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent56')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent35')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent175')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent300')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent77')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent34')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse44')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent236')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent211')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent107')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent99')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent167')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent415')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent104')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent209')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent417')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent148')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent89')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent206')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent413')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent339')).
