add('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Geography_of_Los_Angeles_County_California')).
add('skos:broader'('a26:Category:French_silent_short_films', 'a26:Category:Silent_short_films')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Middle_Eastern_monarchs')).
add('skos:broader'('a26:Category:Former_country_articles_requiring_restructuring', 'a26:Category:WikiProject_Former_countries')).
add('skos:broader'('a26:Category:Philippine_society', 'a26:Category:Philippines')).
add('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:English_businesspeople_by_city')).
add('skos:broader'('a26:Category:MCG_objects', 'a26:Category:MCG_objects')).
add('skos:broader'('a26:Category:Woody_Guthrie', 'a26:Category:Guthrie_family')).
add('skos:broader'('a26:Category:British_tubists', 'a26:Category:Tubists_by_nationality')).
add('skos:broader'('a26:Category:Theatres_in_New_York_City', 'a26:Category:Visitor_attractions_in_New_York_City')).
add('skos:broader'('a26:Category:2009_in_Catalan_sport', 'a26:Category:2009_in_Spanish_sport')).
add('skos:broader'('a26:Category:People_from_the_Las_Vegas_Valley', 'a26:Category:People_by_populated_place_in_Nevada')).
add('skos:broader'('a26:Category:Great_Officers_of_State_of_England', 'a26:Category:Great_Officers_of_State')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_Brazil_by_state')).
add('skos:broader'('a26:Category:610_mm_gauge_railway_locomotives', 'a26:Category:2_ft_gauge_locomotives')).
add('skos:broader'('a26:Category:Balé_Province', 'a26:Category:Provinces_of_Burkina_Faso')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_sports_competitions_hosted_by_France')).
add('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
add('skos:broader'('a26:Category:Steampunk_films', 'a26:Category:Science_fiction_films_by_genre')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Cinema_of_Brazil')).
delete('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
delete('skos:broader'('a26:Category:Buildings_and_structures_in_Dickinson_County_Iowa', 'a26:Category:Buildings_and_structures_in_Iowa_by_county')).
delete('skos:broader'('a26:Category:Albums_by_Ugandan_artists', 'a26:Category:Works_by_Ugandan_people')).
delete('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_sculptors')).
delete('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publishing_company_of_the_United_States')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Heads_of_state_in_the_Middle_East')).
delete('skos:broader'('a26:Category:Rulers_of_Baden', 'a26:Category:German_monarchs')).
delete('skos:broader'('a26:Category:American_football_teams_in_Denmark', 'a26:Category:American_football_teams_in_Europe_by_country')).
delete('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:Water_polo_competitions_in_France')).
delete('skos:broader'('a26:Category:MCG_objects', 'a26:Category:Astronomical_catalogues')).
delete('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Visitor_attractions_in_South_Korea_by_city')).
delete('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Topology')).
delete('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Islands_by_ocean_or_sea')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Musicians_by_instrument')).
delete('skos:broader'('a26:Category:Graphical_user_interface_testing', 'a26:Category:Software_testing_tools')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs')).
delete('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Geography_of_Rio_Grande_do_Sul')).
delete('skos:broader'('a26:Category:Third_Doctor_stories', 'a26:Category:Doctor_Who_stories')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Clarinets')).
delete('skos:broader'('a26:Category:Edmonton_Oilers_broadcasters', 'a26:Category:National_Hockey_League_broadcasters')).
