add('skos:broader'('a26:Category:Military_and_war_museums_in_the_United_States_by_state', 'a26:Category:Military_in_the_United_States_by_state')).
add('skos:broader'('a26:Category:Works_by_Italian_people', 'a26:Category:Works_by_nationality')).
add('skos:broader'('a26:Category:Radio_stations_in_Cleveland_Ohio', 'a26:Category:Radio_in_Cleveland_Ohio')).
add('skos:broader'('a26:Category:People_from_Newfoundland_island', 'a26:Category:Newfoundland_island')).
add('skos:broader'('a26:Category:Newspapers_published_in_Illinois', 'a26:Category:Illinois_media')).
add('skos:broader'('a26:Category:Programming_paradigms', 'a26:Category:Computer_programming')).
add('skos:broader'('a26:Category:Student_assessment_and_evaluation', 'a26:Category:Educational_assessment_and_evaluation')).
add('skos:broader'('a26:Category:Roman_Catholic_Church_in_Slovakia', 'a26:Category:Roman_Catholic_Church_in_Europe')).
add('skos:broader'('a26:Category:Films_shot_in_Madrid', 'a26:Category:Culture_in_Madrid')).
add('skos:broader'('a26:Category:Malayan_swords', 'a26:Category:Malay_culture')).
delete('skos:broader'('a26:Category:University_of_Geneva_alumni', 'a26:Category:University_of_Geneva')).
delete('skos:broader'('a26:Category:Dallas_Stars', 'a26:Category:Sports_clubs_established_in_1993')).
delete('skos:broader'('a26:Category:Slovenian_magazines', 'a26:Category:Magazines_by_country')).
delete('skos:broader'('a26:Category:Candidates_in_the_2015_Canadian_federal_election', 'a26:Category:Canadian_federal_election_2015')).
delete('skos:broader'('a26:Category:Irredentism', 'a26:Category:International_relations_theory')).
delete('skos:broader'('a26:Category:Presidents_of_Colombia', 'a26:Category:Government_of_Colombia')).
delete('skos:broader'('a26:Category:National_Register_of_Historic_Places_in_Chester_County_South_Carolina', 'a26:Category:Buildings_and_structures_in_Chester_County_South_Carolina')).
delete('skos:broader'('a26:Category:American_health_and_wellness_writers', 'a26:Category:Health_and_wellness_writers_by_nationality')).
delete('skos:broader'('a26:Category:LGBT_culture_in_Egypt', 'a26:Category:LGBT_in_Egypt')).
delete('skos:broader'('a26:Category:Government_of_the_Netherlands', 'a26:Category:Politics_of_the_Netherlands')).
