add('skos:broader'('a26:Category:Religion_in_Lebanon', 'a26:Category:Religion_in_Asia_by_country')).
add('skos:broader'('a26:Category:Dates_by_topic', 'a26:Category:Dates')).
add('skos:broader'('a26:Category:Arista_Records_artists', 'a26:Category:Sony_BMG_artists')).
add('skos:broader'('a26:Category:French_cardinals', 'a26:Category:French_Roman_Catholic_clergy')).
add('skos:broader'('a26:Category:Latin_Empire', 'a26:Category:Wikipedia_categories_named_after_former_countries')).
add('skos:broader'('a26:Category:Musical_theatre_librettists', 'a26:Category:Musical_theatre')).
add('skos:broader'('a26:Category:Satellite_broadcasting', 'a26:Category:Telecommunications_engineering')).
add('skos:broader'('a26:Category:Dance_occupations', 'a26:Category:Artists_by_medium')).
add('skos:broader'('a26:Category:Prehistoric_sites_in_the_United_Kingdom', 'a26:Category:Prehistoric_Britain')).
add('skos:broader'('a26:Category:1870s_in_Ukraine', 'a26:Category:Decades_in_Ukraine')).
delete('skos:broader'('a26:Category:Banks_based_in_Massachusetts', 'a26:Category:Banks_in_the_United_States_by_state')).
delete('skos:broader'('a26:Category:Kherson_Governorate', 'a26:Category:Governorates_of_the_Russian_Empire')).
delete('skos:broader'('a26:Category:Visitor_attractions_in_Westchester_County_New_York', 'a26:Category:Visitor_attractions_in_New_York_by_county')).
delete('skos:broader'('a26:Category:Gothic_Revival_architecture_in_Shropshire', 'a26:Category:Buildings_and_structures_in_Shropshire')).
delete('skos:broader'('a26:Category:Newspapers_published_in_Illinois', 'a26:Category:Illinois_media')).
delete('skos:broader'('a26:Category:Roads_in_Australia', 'a26:Category:Roads_by_country')).
delete('skos:broader'('a26:Category:Catalan_scientists', 'a26:Category:Spanish_scientists')).
delete('skos:broader'('a26:Category:Stadiums_in_Zimbabwe', 'a26:Category:Sports_venues_in_Zimbabwe')).
delete('skos:broader'('a26:Category:Roman_Catholic_Church_in_Slovakia', 'a26:Category:Roman_Catholic_Church_in_Europe')).
delete('skos:broader'('a26:Category:Portuguese_monarchy', 'a26:Category:Kingdom_of_Portugal')).
