add('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Ptolemaic_colonies')).
add('skos:broader'('a26:Category:Places_of_worship_in_Washington_state', 'a26:Category:Buildings_and_structures_in_Washington_state')).
add('skos:broader'('a26:Category:United_Peoples_Freedom_Alliance_politicians', 'a26:Category:Sri_Lankan_politicians_by_party')).
add('skos:broader'('a26:Category:United_States_Marines', 'a26:Category:United_States_Marine_Corps_personnel')).
add('skos:broader'('a26:Category:Census-designated_places_in_Merced_County_California', 'a26:Category:Populated_places_in_Merced_County_California')).
add('skos:broader'('a26:Category:Russian_businesspeople', 'a26:Category:Russian_population_groups')).
add('skos:broader'('a26:Category:Gardens_by_Capability_Brown', 'a26:Category:Gardens_by_designer')).
add('skos:broader'('a26:Category:1980s_in_television', 'a26:Category:Decades_in_television')).
add('skos:broader'('a26:Category:Deaths_from_lung_cancer', 'a26:Category:Lung_cancer')).
add('skos:broader'('a26:Category:FA-Class_West_Bengal_articles', 'a26:Category:FA-Class_articles')).
delete('skos:broader'('a26:Category:Australian_songwriters', 'a26:Category:Australian_writers')).
delete('skos:broader'('a26:Category:Delaware_Wizards_players', 'a26:Category:Soccer_players_in_the_United_States_by_club')).
delete('skos:broader'('a26:Category:American_textbook_writers', 'a26:Category:American_instructional_writers')).
delete('skos:broader'('a26:Category:Songs_written_by_Ben_Glover', 'a26:Category:Songs_by_songwriter')).
delete('skos:broader'('a26:Category:Reptiles_by_country', 'a26:Category:Reptiles_by_location')).
delete('skos:broader'('a26:Category:Political_history_of_Japan', 'a26:Category:History_of_Japan_by_topic')).
delete('skos:broader'('a26:Category:Musical_theatre_librettists', 'a26:Category:Musical_theatre')).
delete('skos:broader'('a26:Category:Defunct_Mississippi_railroads', 'a26:Category:Mississippi_railroads')).
delete('skos:broader'('a26:Category:Programming_paradigms', 'a26:Category:Computer_programming')).
delete('skos:broader'('a26:Category:Buddhism_in_Japan', 'a26:Category:Religion_in_Japan')).
