add('skos:broader'('a26:Category:Video_games_by_platform', 'a26:Category:Video_games')).
add('skos:broader'('a26:Category:Buildings_and_structures_completed_in_2007', 'a26:Category:2007_architecture')).
add('skos:broader'('a26:Category:Court_of_James_IV_of_Scotland', 'a26:Category:15th_century_in_Scotland')).
add('skos:broader'('a26:Category:Municipality_of_Cerkno', 'a26:Category:Municipalities_of_Slovenia')).
add('skos:broader'('a26:Category:Urban_Search_and_Rescue_Task_Forces', 'a26:Category:Rescue_agencies')).
add('skos:broader'('a26:Category:2015_in_sports_by_country', 'a26:Category:2015_in_sports')).
add('skos:broader'('a26:Category:Jewish_American_politicians', 'a26:Category:American_politicians_by_ethnic_or_national_origin')).
add('skos:broader'('a26:Category:Geology_of_the_United_States', 'a26:Category:Natural_history_of_the_United_States')).
add('skos:broader'('a26:Category:The_Football_League_representative_players', 'a26:Category:The_Football_League_players')).
add('skos:broader'('a26:Category:Uruguayan_harpsichordists', 'a26:Category:Uruguayan_musicians_by_instrument')).
delete('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Ptolemaic_colonies')).
delete('skos:broader'('a26:Category:Jimmy_Reed_songs', 'a26:Category:Blues_songs')).
delete('skos:broader'('a26:Category:Works_about_film', 'a26:Category:Film')).
delete('skos:broader'('a26:Category:Medical_outbreaks_in_the_United_States', 'a26:Category:Medical_outbreaks_by_country')).
delete('skos:broader'('a26:Category:United_States_Marines', 'a26:Category:United_States_Marine_Corps_personnel')).
delete('skos:broader'('a26:Category:Crime_in_fiction', 'a26:Category:Fiction_by_topic')).
delete('skos:broader'('a26:Category:German_autobiographers', 'a26:Category:Autobiographers_by_nationality')).
delete('skos:broader'('a26:Category:Pop_punk', 'a26:Category:Pop_music_genres')).
delete('skos:broader'('a26:Category:Reform_by_country', 'a26:Category:Categories_by_country')).
delete('skos:broader'('a26:Category:Faculty_by_university_or_college_in_New_York', 'a26:Category:Educators_from_New_York')).
