add('skos:broader'('a26:Category:Channel_18_digital_TV_stations_in_the_United_States', 'a26:Category:Channel_18_TV_stations_in_the_United_States')).
add('skos:broader'('a26:Category:Hungarian_silversmiths', 'a26:Category:Hungarian_metalsmiths')).
add('skos:broader'('a26:Category:Royalty_of_the_Kingdom_of_Hawaii', 'a26:Category:Hawaiian_royalty')).
add('skos:broader'('a26:Category:Animals_described_in_1869', 'a26:Category:Animals_described_in_the_19th_century')).
add('skos:broader'('a26:Category:Portuguese-speaking_countries_and_territories', 'a26:Category:Countries_by_language')).
add('skos:broader'('a26:Category:Roman_Catholic_bishops', 'a26:Category:Bishops_by_denomination')).
add('skos:broader'('a26:Category:Catalan_scientists', 'a26:Category:Spanish_scientists')).
add('skos:broader'('a26:Category:Stem_cell_researchers', 'a26:Category:Medical_researchers')).
add('skos:broader'('a26:Category:Butterflies_of_India', 'a26:Category:Butterflies_of_Asia')).
add('skos:broader'('a26:Category:Expatriate_football_managers_in_Spain', 'a26:Category:Football_managers_in_Spain')).
delete('skos:broader'('a26:Category:Progressive_Party_United_States_1948_politicians', 'a26:Category:20th-century_American_politicians')).
delete('skos:broader'('a26:Category:Austrian_people_of_Czech_descent', 'a26:Category:Austrian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:Massacres_of_Native_Americans', 'a26:Category:Native_American_genocide')).
delete('skos:broader'('a26:Category:People_from_Newfoundland_island', 'a26:Category:Newfoundland_island')).
delete('skos:broader'('a26:Category:People_by_occupation_and_city', 'a26:Category:People_by_city')).
delete('skos:broader'('a26:Category:Montana_Grizzlies_football_coaches', 'a26:Category:Montana_Grizzlies_football')).
delete('skos:broader'('a26:Category:The_Football_League_representative_players', 'a26:Category:The_Football_League_players')).
delete('skos:broader'('a26:Category:Theatre_in_India', 'a26:Category:Performing_arts_in_India')).
delete('skos:broader'('a26:Category:Antarctica_geography_stubs', 'a26:Category:Geography_stubs')).
delete('skos:broader'('a26:Category:Indexes', 'a26:Category:Directories')).
