add('skos:broader'('a26:Category:State_road_transport_corporations_of_India', 'a26:Category:Public_transport_in_India')).
add('skos:broader'('a26:Category:Art_galleries_by_year_of_establishment', 'a26:Category:Art_museums_and_galleries_by_year')).
add('skos:broader'('a26:Category:Unincorporated_communities_in_Venango_County_Pennsylvania', 'a26:Category:Unincorporated_communities_in_Pennsylvania_by_county')).
add('skos:broader'('a26:Category:Hochschule_für_Musik_und_Tanz_Köln_faculty', 'a26:Category:Faculty_by_university_in_Germany')).
add('skos:broader'('a26:Category:Land_management', 'a26:Category:Management_by_type')).
add('skos:broader'('a26:Category:Independent_record_labels_by_country', 'a26:Category:Independent_record_labels')).
add('skos:broader'('a26:Category:Malayali_people', 'a26:Category:People_by_ethnicity')).
add('skos:broader'('a26:Category:River_Ver', 'a26:Category:Rivers_of_England')).
add('skos:broader'('a26:Category:Hamlets_in_the_United_States', 'a26:Category:Populated_places_in_the_United_States')).
add('skos:broader'('a26:Category:Cayman_Islands_international_footballers', 'a26:Category:Association_football_players_by_national_team')).
delete('skos:broader'('a26:Category:Geography_of_Rostov_Oblast', 'a26:Category:Geography_of_Southern_Russia')).
delete('skos:broader'('a26:Category:Hinduism_in_Africa', 'a26:Category:Religion_in_Africa')).
delete('skos:broader'('a26:Category:BGŻ_Arena', 'a26:Category:Indoor_arenas_in_Poland')).
delete('skos:broader'('a26:Category:Freemasonry_in_Scotland', 'a26:Category:Clubs_and_societies_in_Scotland')).
delete('skos:broader'('a26:Category:Transport_ministers_of_Ukraine', 'a26:Category:Government_ministers_of_Ukraine')).
delete('skos:broader'('a26:Category:Bodies_of_water_of_the_United_States', 'a26:Category:Bodies_of_water_by_country')).
delete('skos:broader'('a26:Category:2015_in_sports_by_country', 'a26:Category:2015_in_sports')).
delete('skos:broader'('a26:Category:German_philologists', 'a26:Category:Linguists_from_Germany')).
delete('skos:broader'('a26:Category:Deaths_from_liver_cancer', 'a26:Category:Deaths_from_cancer_by_type')).
delete('skos:broader'('a26:Category:College_football_rivalries_in_the_United_States', 'a26:Category:American_football_rivalries')).
