add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse19')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent54')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent427')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent406')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent382')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent39')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent211')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent58')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent10')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent2')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent424')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent100')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse29')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent70')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent11')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse25')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent125')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent314')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
add('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent181')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent186')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent249')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent310')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent16')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent269')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent87')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent104')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent9')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent130')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent10')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent156')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent173')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent216')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent197')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent324')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent343')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent50')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent27')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent79')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent93')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent37')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent25')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent270')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse36')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse15')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent251')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent168')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent331')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent188')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent128')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent107')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent64')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent164')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent431')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent284')).
