add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent130')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent76')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent85')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent54')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent428')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent218')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent38')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent14')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent382')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent259')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent52')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent10')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent93')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent37')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent6')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent90')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent68')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent210')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent80')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse29')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent111')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent379')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent314')).
add('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor8')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent336')).
add('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor7')).
add('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent164')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor4')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent264')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent50')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent431')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse19')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent90')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent345')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent108')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent216')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent324')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent343')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent212')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent94')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent46')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent424')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent100')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse37')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent251')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent100')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent419')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent168')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent22')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent71')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent186')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor3')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent16')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent268')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent269')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse20')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent249')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent64')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent104')).
