add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent90')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent155')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent199')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent324')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent27')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent212')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent278')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent258')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse22')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor7')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor3')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent440')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse15')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent100')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent168')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent331')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent45')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent22')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent168')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent206')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent313')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent64')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent16')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor3')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent269')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse20')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent64')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse23')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent284')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent76')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent428')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent156')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent173')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent127')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent218')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent50')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent299')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent79')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse36')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent6')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent68')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent210')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse29')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent23')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent126')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent111')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent102')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent379')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse14')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse25')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent107')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent336')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent310')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor4')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent220')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent318')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse46')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse48')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent87')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent19')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent431')).
