add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent85')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent199')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent76')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent173')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent347')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent216')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent218')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse4')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent343')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent211')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent278')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent299')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent79')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent94')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent25')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent90')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse36')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent100')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse37')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent440')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse25')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent437')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent125')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent64')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent164')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor4')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent16')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent249')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse20')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse46')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent87')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse48')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent386')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent385')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent76')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent92')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent428')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent10')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent369')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent195')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent384')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent58')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent6')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent210')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse29')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent45')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse14')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent207')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
delete('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent186')).
delete('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent310')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent186')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent268')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse46')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent6')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent104')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent19')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
