add('skos:broader'('a26:Category:Northwest_Territories_territorial_electoral_districts', 'a26:Category:Canadian_provincial_and_territorial_electoral_districts')).
add('skos:broader'('a26:Category:Parishes_of_Valka_District', 'a26:Category:Parishes_of_Latvia')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Heads_of_state_in_the_Middle_East')).
add('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publisher')).
add('skos:broader'('a26:Category:Member_states_of_the_United_Nations', 'a26:Category:History_of_the_United_Nations')).
add('skos:broader'('a26:Category:Chantilly_Racecourse', 'a26:Category:Wikipedia_categories_named_after_sports_venues')).
add('skos:broader'('a26:Category:MCG_objects', 'a26:Category:Astronomical_catalogues')).
add('skos:broader'('a26:Category:British_tubists', 'a26:Category:Tubists_by_nationality')).
add('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Sport_shooters_by_nationality')).
add('skos:broader'('a26:Category:2009_in_Catalan_sport', 'a26:Category:2009_in_Spanish_sport')).
add('skos:broader'('a26:Category:Indiana_Whigs', 'a26:Category:Whig_Party_United_States_politicians')).
add('skos:broader'('a26:Category:Arab_people_of_the_Arab_Byzantine_wars', 'a26:Category:People_of_the_Arab_Byzantine_wars')).
add('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1285_in_Europe')).
add('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Education_in_Alameda_County_California')).
add('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Computer_languages')).
delete('skos:broader'('a26:Category:Works_set_on_the_London_Underground', 'a26:Category:London_Underground')).
delete('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Ptolemaic_colonies')).
delete('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Works_by_Brazilian_people')).
delete('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_sculptors')).
delete('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_and_colleges_in_Ottawa')).
delete('skos:broader'('a26:Category:Buildings_and_structures_in_Teton_County_Wyoming', 'a26:Category:Buildings_and_structures_in_Wyoming_by_county')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Musicians_by_instrument')).
delete('skos:broader'('a26:Category:Exoplanet_catalogues', 'a26:Category:Exoplanetology')).
delete('skos:broader'('a26:Category:Landforms_of_Petersburg_Borough_Alaska', 'a26:Category:Geography_of_Petersburg_Borough_Alaska')).
delete('skos:broader'('a26:Category:The_Football_League_representative_players', 'a26:Category:The_Football_League_players')).
delete('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Tourism_in_Ulsan')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:Establishments_in_British_Columbia_by_year')).
delete('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
delete('skos:broader'('a26:Category:University_of_Benghazi_faculty', 'a26:Category:Faculty_by_university_or_college_in_Libya')).
delete('skos:broader'('a26:Category:DC_Comics-related_lists', 'a26:Category:Comic_lists_by_franchise')).
