add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent36')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent303')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent79')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor12')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent78')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent124')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent52')).
add('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer2')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent381')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent254')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent72')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent34')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent100')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent236')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse34')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent39')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor3')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent352')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent102')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent144')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent148')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent23')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent187')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse23')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent206')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent160')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent2')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent221')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent108')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent412')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent129')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent92')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse14')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent61')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent11')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent219')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent174')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent12')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse9')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent305')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent257')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent215')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent103')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent23')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor5')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent208')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent184')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent183')).
delete('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor7')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent181')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent265')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent285')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent69')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent61')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent248')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent80')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse33')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent338')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse48')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent79')).
