add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent320')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent56')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent404')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent35')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent136')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent217')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent239')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent346')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent94')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent18')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent32')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent232')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse31')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent80')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse44')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent7')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse27')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent250')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent99')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent209')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent129')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse23')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent87')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent67')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent162')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent87')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent244')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse34')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent260')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent86')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse18')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent135')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor11')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent106')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent304')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent197')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent130')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent192')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent94')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent362')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent77')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent349')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent26')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent252')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent230')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent62')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse17')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent125')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent7')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent167')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent415')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent43')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent121')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent229')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent105')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent313')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent224')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent339')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent223')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent286')).
