add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent320')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent121')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent229')).
add('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer4')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent191')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent53')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent73')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent292')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent240')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent330')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent122')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent107')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent388')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor11')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent94')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent253')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent413')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent252')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent233')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent4')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent261')).
