add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent343')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent34')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent36')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent302')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent97')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent26')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent343')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent110')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent194')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent381')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent12')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent305')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent257')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse33')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent102')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent14')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent179')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent88')).
delete('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer5')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent323')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent34')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent33')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent256')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent282')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent103')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse35')).
