add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent12')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent343')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent179')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent108')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent141')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent42')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent245')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent220')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent69')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent327')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent256')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent96')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent36')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent157')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent79')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent56')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent58')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent181')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent13')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent12')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent214')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent89')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent432')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent240')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent211')).
