add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse17')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent99')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent357')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent35')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent117')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent346')).
add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent192')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent232')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent292')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent69')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent9')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse18')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent320')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent106')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent335')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent112')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent18')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent141')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse34')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent39')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent71')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent105')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse27')).
