add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent30')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent113')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent22')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent197')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent119')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent32')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent255')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent240')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent167')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent104')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent117')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent346')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent323')).
delete('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor10')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent153')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent34')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent21')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent282')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent292')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent339')).
