add('skos:broader'('a26:Category:Defunct_American_football_teams', 'a26:Category:Defunct_sports_teams')).
add('skos:broader'('a26:Category:Exoplanet_catalogues', 'a26:Category:Exoplanetology')).
add('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publisher')).
add('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publishing_company_of_the_United_States')).
add('skos:broader'('a26:Category:Conspiracy_theories', 'a26:Category:Fringe_theory')).
add('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Universities_and_colleges_in_California_by_county')).
add('skos:broader'('a26:Category:A-Class_Museums_articles', 'a26:Category:A-Class_articles')).
add('skos:broader'('a26:Category:MCG_objects', 'a26:Category:MCG_objects')).
add('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Clarinets')).
add('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:Centuries_in_Staffordshire')).
delete('skos:broader'('a26:Category:Conspiracy_theories', 'a26:Category:Conspiracy')).
delete('skos:broader'('a26:Category:Buildings_and_structures_in_Dickinson_County_Iowa', 'a26:Category:Buildings_and_structures_in_Iowa_by_county')).
delete('skos:broader'('a26:Category:Altötting_district', 'a26:Category:Upper_Bavaria')).
delete('skos:broader'('a26:Category:Compositions_in_E_minor', 'a26:Category:Compositions_by_key')).
delete('skos:broader'('a26:Category:French_silent_short_films', 'a26:Category:Silent_short_films')).
delete('skos:broader'('a26:Category:Pirate_Party_Germany', 'a26:Category:Liberal_parties_in_Germany')).
delete('skos:broader'('a26:Category:The_Football_League_representative_players', 'a26:Category:The_Football_League_players')).
delete('skos:broader'('a26:Category:Treaties_of_the_Grand_Duchy_of_Hesse', 'a26:Category:Treaties_of_Germany')).
delete('skos:broader'('a26:Category:Conglomerate_companies_of_France', 'a26:Category:Companies_of_France')).
delete('skos:broader'('a26:Category:American_football_teams_in_Denmark', 'a26:Category:American_football_teams_in_Europe_by_country')).
