add('skos:broader'('a26:Category:Dietary_antioxidants', 'a26:Category:Antioxidants')).
add('skos:broader'('a26:Category:Sportspeople_from_Chicago_Illinois', 'a26:Category:Sportspeople_from_DuPage_County_Illinois')).
add('skos:broader'('a26:Category:Manhattan_Jaspers_basketball', 'a26:Category:Metro_Atlantic_Athletic_Conference_mens_basketball')).
add('skos:broader'('a26:Category:Forced_disappearance', 'a26:Category:Crimes_against_humanity')).
add('skos:broader'('a26:Category:Census-designated_places_in_Tennessee', 'a26:Category:Populated_places_in_Tennessee')).
add('skos:broader'('a26:Category:Olympic_cross-country_skiing_venues', 'a26:Category:Cross-country_skiing_at_the_Winter_Olympics')).
add('skos:broader'('a26:Category:Professional_sports_leagues_in_Canada', 'a26:Category:Sports_leagues_in_Canada')).
add('skos:broader'('a26:Category:The_Hart_Foundation_members', 'a26:Category:Independent_promotions_teams_and_stables')).
add('skos:broader'('a26:Category:Areas_of_Dudley', 'a26:Category:Areas_of_the_West_Midlands_county')).
add('skos:broader'('a26:Category:Musical_groups_from_San_Diego_California', 'a26:Category:Culture_of_San_Diego_California')).
add('skos:broader'('a26:Category:Languages_of_India', 'a26:Category:Languages_by_country')).
add('skos:broader'('a26:Category:MCG_objects', 'a26:Category:Astronomical_catalogues')).
add('skos:broader'('a26:Category:People_from_Dalarna', 'a26:Category:Dalarna')).
add('skos:broader'('a26:Category:Companies_based_in_Los_Angeles_California', 'a26:Category:Organizations_based_in_Los_Angeles_California')).
add('skos:broader'('a26:Category:Light_rail_in_California', 'a26:Category:Passenger_rail_transportation_in_California')).
add('skos:broader'('a26:Category:Boston_College', 'a26:Category:Universities_and_colleges_in_Massachusetts')).
add('skos:broader'('a26:Category:Mammals_of_Belize', 'a26:Category:Mammals_by_country')).
add('skos:broader'('a26:Category:Scottish_rock_music_groups', 'a26:Category:Scottish_musical_groups_by_genre')).
add('skos:broader'('a26:Category:Turkish_Football_Federation_presidents', 'a26:Category:Turkish_Football_Federation')).
add('skos:broader'('a26:Category:1860s_in_South_Africa', 'a26:Category:19th_century_in_South_Africa')).
delete('skos:broader'('a26:Category:Rivers_of_New_South_Wales', 'a26:Category:Bodies_of_water_of_New_South_Wales')).
delete('skos:broader'('a26:Category:Field_armies_of_Turkey', 'a26:Category:Army_units_and_formations_of_Turkey')).
delete('skos:broader'('a26:Category:National_Heritage_Fellowship_winners', 'a26:Category:Award_winners')).
delete('skos:broader'('a26:Category:Military_history_of_the_United_Kingdom', 'a26:Category:Military_history_of_Europe')).
delete('skos:broader'('a26:Category:Hospital_buildings_completed_in_1954', 'a26:Category:Hospital_buildings_by_year_of_completion')).
delete('skos:broader'('a26:Category:Busking', 'a26:Category:Performing_arts')).
delete('skos:broader'('a26:Category:Rulers_of_Baden', 'a26:Category:German_monarchs')).
delete('skos:broader'('a26:Category:Engines', 'a26:Category:Rotating_machines')).
delete('skos:broader'('a26:Category:Dallas_Fort_Worth_metroplex', 'a26:Category:Metropolitan_areas_of_Texas')).
delete('skos:broader'('a26:Category:People_from_Springfield_Ohio', 'a26:Category:People_from_Clark_County_Ohio')).
delete('skos:broader'('a26:Category:Alumni_of_Christ_Church_Oxford', 'a26:Category:Alumni_of_the_University_of_Oxford')).
delete('skos:broader'('a26:Category:Populated_places_in_Galikash_County', 'a26:Category:Populated_places_in_Golestan_Province')).
delete('skos:broader'('a26:Category:Video_game_prequels', 'a26:Category:Prequels')).
delete('skos:broader'('a26:Category:Churches_in_Missouri', 'a26:Category:Christianity_in_Missouri')).
delete('skos:broader'('a26:Category:Presidency_of_James_K._Polk', 'a26:Category:Presidencies_of_the_United_States')).
delete('skos:broader'('a26:Category:Buildings_and_structures_in_Winn_Parish_Louisiana', 'a26:Category:Winn_Parish_Louisiana')).
delete('skos:broader'('a26:Category:People_from_Berchtesgaden', 'a26:Category:People_by_municipality_in_Germany')).
delete('skos:broader'('a26:Category:English_proverbs', 'a26:Category:Proverbs')).
delete('skos:broader'('a26:Category:Class_computer_programming', 'a26:Category:Object-oriented_programming')).
delete('skos:broader'('a26:Category:Geography_of_Tennessee', 'a26:Category:Geography_of_the_United_States_by_state')).
