add('skos:broader'('a26:Category:Visitor_attractions_by_country', 'a26:Category:Categories_by_country')).
add('skos:broader'('a26:Category:Maltese_archaeologists', 'a26:Category:Maltese_academics')).
add('skos:broader'('a26:Category:Petroleum_industry_in_Norway', 'a26:Category:Petroleum_in_Norway')).
add('skos:broader'('a26:Category:Combinatorialists', 'a26:Category:Combinatorics')).
add('skos:broader'('a26:Category:History_of_Vojvodina', 'a26:Category:History_of_Serbia_by_region')).
add('skos:broader'('a26:Category:Doomsday_scenarios', 'a26:Category:Human_extinction')).
add('skos:broader'('a26:Category:Former_settlements_in_Lassen_County_California', 'a26:Category:Former_populated_places_in_California_by_county')).
add('skos:broader'('a26:Category:Cubist_artists', 'a26:Category:Artists_by_genre')).
add('skos:broader'('a26:Category:People_of_the_Salvadoran_Civil_War', 'a26:Category:20th-century_people_by_conflict')).
add('skos:broader'('a26:Category:Animals_described_in_1876', 'a26:Category:Species_described_in_1876')).
add('skos:broader'('a26:Category:Radio_stations_established_in_1997', 'a26:Category:1997_establishments')).
add('skos:broader'('a26:Category:American_romance_novels', 'a26:Category:Romance_novels_by_country')).
add('skos:broader'('a26:Category:History_of_Syrmia', 'a26:Category:Syrmia')).
add('skos:broader'('a26:Category:Eastern_Orthodox_church_bodies_and_patriarchates', 'a26:Category:Eastern_Orthodox_organizations')).
add('skos:broader'('a26:Category:New_Zealand_racehorses', 'a26:Category:Horse_racing_in_New_Zealand')).
add('skos:broader'('a26:Category:1823_in_Alta_California', 'a26:Category:Years_in_California')).
add('skos:broader'('a26:Category:Dutch_European_Commissioners', 'a26:Category:Netherlands_and_the_European_Union')).
add('skos:broader'('a26:Category:Houses_in_Dauphin_County_Pennsylvania', 'a26:Category:Houses_in_Pennsylvania_by_county')).
add('skos:broader'('a26:Category:DC_Comics-related_lists', 'a26:Category:Comic_lists_by_franchise')).
add('skos:broader'('a26:Category:Open_content', 'a26:Category:Crowdsourcing')).
delete('skos:broader'('a26:Category:Northwest_Territories_territorial_electoral_districts', 'a26:Category:Canadian_provincial_and_territorial_electoral_districts')).
delete('skos:broader'('a26:Category:Airports_in_Klamath_County_Oregon', 'a26:Category:Airports_in_Oregon')).
delete('skos:broader'('a26:Category:Census-designated_places_in_Tennessee', 'a26:Category:Populated_places_in_Tennessee')).
delete('skos:broader'('a26:Category:People_by_century', 'a26:Category:People_by_time')).
delete('skos:broader'('a26:Category:2011_in_Armenian_football', 'a26:Category:2011_in_association_football')).
delete('skos:broader'('a26:Category:Non-profit_organizations_by_country', 'a26:Category:Organizations_by_subject_and_country')).
delete('skos:broader'('a26:Category:Demographics_of_Peru', 'a26:Category:Demographics_by_country')).
delete('skos:broader'('a26:Category:Ghost_towns_in_Western_Australia', 'a26:Category:Ghost_towns_in_Australia')).
delete('skos:broader'('a26:Category:Politics_of_Shizuoka_Shizuoka', 'a26:Category:Shizuoka_Shizuoka')).
delete('skos:broader'('a26:Category:Towns_and_villages_in_County_Cork', 'a26:Category:Geography_of_County_Cork')).
delete('skos:broader'('a26:Category:Kentucky_Wildcats_football_coaches', 'a26:Category:Kentucky_Wildcats_coaches')).
delete('skos:broader'('a26:Category:Theatres_in_New_York_City', 'a26:Category:Visitor_attractions_in_New_York_City')).
delete('skos:broader'('a26:Category:Boston_College', 'a26:Category:Jesuit_universities_and_colleges_in_the_United_States')).
delete('skos:broader'('a26:Category:Companies_based_in_Los_Angeles_California', 'a26:Category:Organizations_based_in_Los_Angeles_California')).
delete('skos:broader'('a26:Category:Government_of_Poland', 'a26:Category:Government_by_country')).
delete('skos:broader'('a26:Category:Swimming_by_country', 'a26:Category:Categories_by_country')).
delete('skos:broader'('a26:Category:Cities_in_Georgia_country', 'a26:Category:Cities_in_Europe')).
delete('skos:broader'('a26:Category:Canadian_legislation', 'a26:Category:Statutory_law_by_country')).
delete('skos:broader'('a26:Category:Pre-Reformation_bishops_in_Ireland', 'a26:Category:Church_of_Ireland_bishops')).
delete('skos:broader'('a26:Category:Roman_Catholic_bishops', 'a26:Category:Catholic_bishops')).
