add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent275', 'http://www.Department2.University0.edu/Course0')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent204', '"UndergraduateStudent204@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent84', 'http://www.Department1.University0.edu/Course18')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor0/Publication5', 'http://www.Department0.University0.edu/FullProfessor0')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor6/Publication2', 'http://www.Department1.University0.edu/GraduateStudent113')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor1/Publication1', 'http://www.Department2.University0.edu/GraduateStudent97')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor10/Publication12', 'http://www.Department2.University0.edu/GraduateStudent2')).
add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent64', 'http://www.Department2.University0.edu/FullProfessor2')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor2/Publication11', 'http://www.Department2.University0.edu/GraduateStudent68')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent13', 'http://www.Department2.University0.edu/Course47')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent129', '"UndergraduateStudent129@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent106', '"UndergraduateStudent106@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication8', 'http://www.Department0.University0.edu/GraduateStudent3')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent121', 'http://www.Department2.University0.edu/Course20')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor5', 'http://www.Department2.University0.edu/Course17')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent254', 'http://www.Department0.University0.edu/Course11')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent386', '"UndergraduateStudent386@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent84', 'http://www.Department0.University0.edu/GraduateCourse10')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor3/Publication6', 'http://www.Department1.University0.edu/FullProfessor3')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent343', 'http://www.Department1.University0.edu/Course31')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor3/Publication7', 'http://www.Department1.University0.edu/GraduateStudent31')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent13', 'http://www.Department0.University0.edu/Course1')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent409', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent289', 'http://www.Department2.University0.edu/Course3')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent161', 'http://www.Department2.University0.edu/Course10')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent62', 'http://www.Department1.University0.edu/FullProfessor7')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent397', 'http://www.Department2.University0.edu/Course42')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication3', 'http://www.Department2.University0.edu/AssociateProfessor3')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse45')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent215', 'http://www.Department0.University0.edu/Course1')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent192', 'http://www.Department0.University0.edu/Course45')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent16', 'http://www.Department2.University0.edu/Course38')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor4/Publication4', 'http://www.Department2.University0.edu/GraduateStudent0')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent355', 'http://www.Department2.University0.edu/Course36')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent298', 'http://www.Department1.University0.edu/Course4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent19', 'http://www.Department1.University0.edu/GraduateCourse14')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent164', 'http://www.Department0.University0.edu/Course26')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor6/Publication6', 'http://www.Department1.University0.edu/AssistantProfessor6')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication2', 'http://www.Department0.University0.edu/GraduateStudent94')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor11/Publication9', 'http://www.Department2.University0.edu/GraduateStudent55')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent197', 'http://www.Department0.University0.edu/Course43')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent151', 'http://www.Department0.University0.edu/Course47')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent258', 'http://www.Department2.University0.edu/Course17')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent311', 'http://www.Department2.University0.edu/Course1')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/AssistantProfessor0', 'http://www.Department0.University0.edu/GraduateCourse33')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent78', 'http://www.Department1.University0.edu/AssistantProfessor0')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent217', 'http://www.Department1.University0.edu/Course5')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent168', 'http://www.Department1.University0.edu/Course12')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/AssistantProfessor2', 'http://www.Department0.University0.edu/Course36')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor1/Publication13', 'http://www.Department1.University0.edu/FullProfessor1')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent197', 'http://www.Department2.University0.edu/Course7')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent303', '"UndergraduateStudent303@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent57', 'http://www.Department1.University0.edu/GraduateCourse2')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor7/Publication4', 'http://www.Department1.University0.edu/GraduateStudent89')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent51', 'http://www.Department1.University0.edu/GraduateCourse12')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent74', 'http://www.Department0.University0.edu/Course36')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor4/Publication13', 'http://www.Department2.University0.edu/FullProfessor4')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent10', 'http://www.Department2.University0.edu/Course10')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent70', 'http://www.University259.edu')).
delete('a1:telephone'('http://www.Department1.University0.edu/Lecturer6', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent283', 'http://www.Department1.University0.edu/Course44')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor3/Publication7', 'http://www.Department1.University0.edu/AssociateProfessor3')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent415', 'http://www.Department1.University0.edu/Course14')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent90', 'http://www.Department0.University0.edu/FullProfessor6')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent14', 'http://www.Department1.University0.edu/GraduateCourse17')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor4', 'http://www.Department1.University0.edu/GraduateCourse5')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent166', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent189', 'http://www.Department1.University0.edu/Course51')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor6/Publication8', 'http://www.Department0.University0.edu/FullProfessor6')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent94', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent49', 'http://www.Department2.University0.edu/Course40')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent356', 'http://www.Department1.University0.edu/Course36')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent9', 'http://www.University271.edu')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent162', 'http://www.Department2.University0.edu/Course18')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent332', 'http://www.Department2.University0.edu/Course6')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor2/Publication9', 'http://www.Department1.University0.edu/GraduateStudent63')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor0/Publication0', 'http://www.Department1.University0.edu/GraduateStudent117')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent349', 'http://www.Department2.University0.edu/Course21')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent95', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent206', 'http://www.Department0.University0.edu/Course48')).
