add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent317', '"UndergraduateStudent317@Department0.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent8', 'http://www.Department1.University0.edu/FullProfessor7')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent1', 'http://www.Department0.University0.edu/AssociateProfessor5')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor3/Publication4', 'http://www.Department2.University0.edu/AssistantProfessor3')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent385', 'http://www.Department2.University0.edu/Course26')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor11', 'http://www.Department2.University0.edu/Course26')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent48', '"GraduateStudent48@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent259', 'http://www.Department0.University0.edu/Course7')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent98', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication8', 'http://www.Department0.University0.edu/FullProfessor3')).
add('a1:teacherOf'('http://www.Department1.University0.edu/AssistantProfessor3', 'http://www.Department1.University0.edu/GraduateCourse31')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent27', 'http://www.Department0.University0.edu/Course12')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication6', 'http://www.Department0.University0.edu/AssistantProfessor7')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent165', '"UndergraduateStudent165@Department0.University0.edu"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent29', 'http://www.University83.edu')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent16', 'http://www.University172.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent172', '"UndergraduateStudent172@Department1.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent372', '"UndergraduateStudent372@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent27', 'http://www.Department2.University0.edu/GraduateCourse33')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent275', '"UndergraduateStudent275@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent257', 'http://www.Department0.University0.edu/Course35')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent273', 'http://www.Department2.University0.edu/Course25')).
add('a1:telephone'('http://www.Department2.University0.edu/FullProfessor1', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/Lecturer0/Publication1', 'http://www.Department0.University0.edu/GraduateStudent88')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent12', 'http://www.Department0.University0.edu/Course6')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent362', 'http://www.Department2.University0.edu/Course45')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent119', 'http://www.Department1.University0.edu/GraduateCourse15')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent40', '"GraduateStudent40@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent327', 'http://www.Department1.University0.edu/Course9')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent173', 'http://www.Department1.University0.edu/Course2')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent306', 'http://www.Department0.University0.edu/Course45')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication10', 'http://www.Department0.University0.edu/AssociateProfessor12')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor6/Publication2', 'http://www.Department1.University0.edu/AssociateProfessor6')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent283', 'http://www.Department2.University0.edu/Course0')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent257', 'http://www.Department2.University0.edu/Course39')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/FullProfessor6', '"FullProfessor6@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent291', 'http://www.Department1.University0.edu/Course23')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor4/Publication6', 'http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent91', 'http://www.Department2.University0.edu/Course5')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor6/Publication10', 'http://www.Department1.University0.edu/GraduateStudent64')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent223', 'http://www.Department1.University0.edu/Course53')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent219', 'http://www.Department0.University0.edu/Course38')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor0/Publication7', 'http://www.Department0.University0.edu/AssociateProfessor0')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent282', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent4', 'http://www.Department1.University0.edu/AssociateProfessor7')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent99', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent400', 'http://www.Department1.University0.edu/Course12')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent155', 'http://www.Department1.University0.edu/Course33')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent0', 'http://www.Department2.University0.edu/Course21')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor3/Publication8', 'http://www.Department0.University0.edu/AssistantProfessor3')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent122', 'http://www.University431.edu')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent197', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor0/Publication3', 'http://www.Department1.University0.edu/GraduateStudent11')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent55', 'http://www.Department0.University0.edu/Course41')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent199', '"UndergraduateStudent199@Department1.University0.edu"^^xsd:string')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/AssociateProfessor6', 'http://www.Department1.University0.edu/GraduateCourse19')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent23', 'http://www.Department0.University0.edu/Course18')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent90', 'http://www.Department0.University0.edu/GraduateCourse30')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor7/Publication14', 'http://www.Department1.University0.edu/AssociateProfessor7')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent20', 'http://www.Department1.University0.edu/Course22')).
