add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication4', 'http://www.Department0.University0.edu/AssociateProfessor12')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent47', 'http://www.University963.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent39', '"GraduateStudent39@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent178', 'http://www.Department2.University0.edu/Course46')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication15', 'http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication6', 'http://www.Department2.University0.edu/GraduateStudent71')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent415', '"UndergraduateStudent415@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication15', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent125', 'http://www.Department2.University0.edu/Course17')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent427', 'http://www.Department1.University0.edu/Course46')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent16', '"GraduateStudent16@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent351', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent117', '"GraduateStudent117@Department1.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent34', '"GraduateStudent34@Department1.University0.edu"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/AssistantProfessor0', 'http://www.University641.edu')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
add('a1:telephone'('http://www.Department0.University0.edu/AssociateProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent222', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent1', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication4', 'http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent140', 'http://www.Department1.University0.edu/FullProfessor4')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent64', 'http://www.Department0.University0.edu/GraduateCourse32')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/AssistantProfessor0')).
add('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent44', 'http://www.Department0.University0.edu/Course45')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent172', 'http://www.Department2.University0.edu/Course2')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor8/Publication7', 'http://www.Department1.University0.edu/GraduateStudent32')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent407', 'http://www.Department2.University0.edu/Course43')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent56', 'http://www.Department1.University0.edu/Course19')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent279', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent102', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent395', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication1', 'http://www.Department0.University0.edu/GraduateStudent107')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication4', 'http://www.Department0.University0.edu/GraduateStudent77')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent1', 'http://www.Department2.University0.edu/Course36')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent260', 'http://www.Department2.University0.edu/Course18')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent183', 'http://www.Department0.University0.edu/Course25')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent52', '"GraduateStudent52@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent290', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor3', 'http://www.University616.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent25', 'http://www.Department1.University0.edu/GraduateCourse10')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor4/Publication2', 'http://www.Department2.University0.edu/AssistantProfessor4')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent213', 'http://www.Department0.University0.edu/Course17')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent13', 'http://www.Department2.University0.edu/Course37')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent373', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor1')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication17', 'http://www.Department0.University0.edu/GraduateStudent95')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent405', 'http://www.Department1.University0.edu/Course48')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent241', '"UndergraduateStudent241@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/FullProfessor1', '"FullProfessor1@Department0.University0.edu"^^xsd:string')).
