add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent88', 'http://www.University398.edu')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor4/Publication2', 'http://www.Department2.University0.edu/AssistantProfessor4')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent199', '"UndergraduateStudent199@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent112', 'http://www.Department1.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent172', 'http://www.Department0.University0.edu/Course3')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent283', 'http://www.Department2.University0.edu/Course0')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent242', 'http://www.Department0.University0.edu/Course19')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent147', 'http://www.Department0.University0.edu/Course46')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent427', 'http://www.Department1.University0.edu/Course46')).
add('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor11', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent16', '"GraduateStudent16@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication3', 'http://www.Department1.University0.edu/GraduateStudent72')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor0/Publication3', 'http://www.Department1.University0.edu/GraduateStudent11')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication4', 'http://www.Department0.University0.edu/AssistantProfessor6')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent0', 'http://www.Department0.University0.edu/FullProfessor2')).
delete('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor12', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent52', '"GraduateStudent52@Department1.University0.edu"^^xsd:string')).
delete('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent53', 'http://www.Department0.University0.edu/Course27')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent339', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent165', 'http://www.Department2.University0.edu/Course41')).
