add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent221', 'http://www.Department0.University0.edu/Course12')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent169', '"UndergraduateStudent169@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent139', '"UndergraduateStudent139@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor2/Publication6', 'http://www.Department0.University0.edu/AssociateProfessor2')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent83', 'http://www.Department1.University0.edu/Course51')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication4', 'http://www.Department1.University0.edu/GraduateStudent85')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication1', 'http://www.Department1.University0.edu/GraduateStudent103')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent414', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent246', '"UndergraduateStudent246@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent52', '"GraduateStudent52@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent168', 'http://www.Department0.University0.edu/Course20')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent418', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/AssistantProfessor1', 'http://www.Department1.University0.edu/GraduateCourse28')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent368', 'http://www.Department1.University0.edu/Course51')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent28', 'http://www.Department1.University0.edu/GraduateCourse5')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent35', 'http://www.Department0.University0.edu/GraduateCourse21')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication14', 'http://www.Department1.University0.edu/FullProfessor5')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor4/Publication10', 'http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent420', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent123', 'http://www.Department0.University0.edu/Course29')).
