add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=493936')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=2015516')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=618848')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=647738')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=797260')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=475037&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=3446093')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=797263')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=386313')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=412132&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=2015514')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/yarm_tepe')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=386310')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=579343')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=475040')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1487170')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/andravida')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/serres')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=2039133')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/nea_palatia')).
