add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent79', '"UndergraduateStudent79@Department1.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent30', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent251', 'http://www.Department2.University0.edu/Course28')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent295', 'http://www.Department1.University0.edu/Course45')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent201', 'http://www.Department1.University0.edu/Course18')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent184', '"UndergraduateStudent184@Department1.University0.edu"^^xsd:string')).
add('a1:mastersDegreeFrom'('http://www.Department1.University0.edu/AssistantProfessor5', 'http://www.University367.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent297', '"UndergraduateStudent297@Department1.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent64', 'http://www.Department0.University0.edu/AssistantProfessor2')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor8/Publication10', 'http://www.Department1.University0.edu/GraduateStudent22')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent146', 'http://www.Department1.University0.edu/Course46')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent85', 'http://www.Department1.University0.edu/GraduateCourse37')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor4/Publication15', 'http://www.Department0.University0.edu/GraduateStudent2')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent226', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent122', 'http://www.Department0.University0.edu/Course6')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent115', 'http://www.University311.edu')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent249', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent22', 'http://www.Department2.University0.edu/GraduateCourse29')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent433', '"UndergraduateStudent433@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent50', 'http://www.Department0.University0.edu/Course8')).
