add('skos:broader'('a26:Category:Health_in_Canada', 'a26:Category:Health_in_North_America')).
add('skos:broader'('a26:Category:Rivers_of_New_South_Wales', 'a26:Category:Bodies_of_water_of_New_South_Wales')).
add('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1285_in_Europe')).
add('skos:broader'('a26:Category:Boston_College', 'a26:Category:Former_Big_East_Conference_schools')).
add('skos:broader'('a26:Category:University_of_Valencia', 'a26:Category:Wikipedia_categories_named_after_universities_and_colleges')).
add('skos:broader'('a26:Category:History_of_algebra', 'a26:Category:History_of_mathematics')).
add('skos:broader'('a26:Category:Animals_described_in_1871', 'a26:Category:Animals_described_in_the_19th_century')).
add('skos:broader'('a26:Category:Canadian_legislation', 'a26:Category:Statutory_law_by_country')).
add('skos:broader'('a26:Category:Astrobiology', 'a26:Category:Branches_of_biology')).
add('skos:broader'('a26:Category:Chordophones', 'a26:Category:Hornbostel-Sachs')).
delete('skos:broader'('a26:Category:Noble_titles', 'a26:Category:Honorary_titles')).
delete('skos:broader'('a26:Category:Former_countries_in_Malaysian_history', 'a26:Category:Former_countries_in_Southeast_Asia')).
delete('skos:broader'('a26:Category:South_African_people_of_Zimbabwean_descent', 'a26:Category:South_Africa_Zimbabwe_relations')).
delete('skos:broader'('a26:Category:Estonian_Jews', 'a26:Category:Ethnic_groups_in_Estonia')).
delete('skos:broader'('a26:Category:Regional_airlines_of_the_Canadian_Territories', 'a26:Category:Regional_airlines_of_Canada')).
delete('skos:broader'('a26:Category:Field_armies_of_Turkey', 'a26:Category:Army_units_and_formations_of_Turkey')).
delete('skos:broader'('a26:Category:European_archaeology', 'a26:Category:Archaeology_by_continent')).
delete('skos:broader'('a26:Category:Royal_Saxon_Academy_of_Forestry', 'a26:Category:History_of_forestry_education')).
delete('skos:broader'('a26:Category:Vietnam_War_sites', 'a26:Category:Military_locations')).
delete('skos:broader'('a26:Category:Non-profit_organizations_by_country', 'a26:Category:Organizations_by_subject_and_country')).
