add('skos:broader'('a26:Category:Injuries_of_ankle_and_foot', 'a26:Category:Injuries_by_region_of_body')).
add('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
add('skos:broader'('a26:Category:French_silent_short_films', 'a26:Category:Silent_short_films')).
add('skos:broader'('a26:Category:Former_country_articles_requiring_restructuring', 'a26:Category:WikiProject_Former_countries')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Historic_districts_in_Pennsylvania_by_county')).
add('skos:broader'('a26:Category:Geography_of_the_Northern_Territory', 'a26:Category:Geography_of_Australia_by_state_or_territory')).
add('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1285_in_Europe')).
add('skos:broader'('a26:Category:Great_Officers_of_State_of_England', 'a26:Category:Great_Officers_of_State')).
add('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:American_sculptors_by_century')).
add('skos:broader'('a26:Category:Buddhist_titles', 'a26:Category:Titles')).
add('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Abstract_algebra')).
add('skos:broader'('a26:Category:Parishes_of_Valka_District', 'a26:Category:Parishes_of_Latvia')).
add('skos:broader'('a26:Category:Hungarian_people_of_Slovenian_descent', 'a26:Category:Hungarian_people_by_ethnic_or_national_origin')).
add('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Woodwind_musicians')).
add('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:Racquetball_players_by_nationality')).
add('skos:broader'('a26:Category:Balé_Province', 'a26:Category:Provinces_of_Burkina_Faso')).
add('skos:broader'('a26:Category:Redirects_with_possibilities', 'a26:Category:Redirects_from_subtopics')).
add('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Clarinets')).
add('skos:broader'('a26:Category:Conspiracy_theories', 'a26:Category:Fringe_theory')).
add('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:American_sportspeople')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:Professional_Indoor_Football_League_teams', 'a26:Category:Indoor_American_football_teams_in_the_United_States_by_league')).
add('skos:broader'('a26:Category:Iowa_Libertarians', 'a26:Category:Libertarian_Party_United_States_politicians')).
add('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Italian_people_by_ethnic_or_national_origin')).
add('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Visitor_attractions_in_South_Korea_by_city')).
add('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Local_government_in_Somerset')).
add('skos:broader'('a26:Category:610_mm_gauge_railway_locomotives', 'a26:Category:2_ft_gauge_locomotives')).
add('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Tourism_in_Ulsan')).
add('skos:broader'('a26:Category:A-Class_Museums_articles', 'a26:Category:A-Class_articles')).
add('skos:broader'('a26:Category:Songwriters_from_Texas', 'a26:Category:Musicians_from_Texas')).
add('skos:broader'('a26:Category:Solar_phenomena', 'a26:Category:Stellar_phenomena')).
add('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Geography_of_Los_Angeles_County_California')).
add('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_and_colleges_in_Ottawa')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Heads_of_state_in_the_Middle_East')).
add('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Housing_in_the_United_Kingdom')).
add('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Universities_and_colleges_in_California_by_county')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Films_by_country')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:History_of_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:Conglomerate_companies_of_France', 'a26:Category:Companies_of_France')).
add('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Footballers_in_Italy_by_club')).
add('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Parma_FC')).
add('skos:broader'('a26:Category:Compositions_in_E_minor', 'a26:Category:Compositions_by_key')).
add('skos:broader'('a26:Category:Explosions_in_England', 'a26:Category:Disasters_in_England')).
add('skos:broader'('a26:Category:Pirate_Party_Germany', 'a26:Category:Liberal_parties_in_Germany')).
add('skos:broader'('a26:Category:Graphemes', 'a26:Category:Writing_systems')).
add('skos:broader'('a26:Category:The_Football_League_representative_players', 'a26:Category:The_Football_League_players')).
add('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
add('skos:broader'('a26:Category:Association_football_international_competitions_squad_navigational_boxes', 'a26:Category:Association_football_international_competitions_navigational_boxes')).
add('skos:broader'('a26:Category:Treaties_of_the_Grand_Duchy_of_Hesse', 'a26:Category:Treaties_of_Germany')).
add('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:Centuries_in_Staffordshire')).
delete('skos:broader'('a26:Category:Altötting_district', 'a26:Category:Upper_Bavaria')).
delete('skos:broader'('a26:Category:American_Airlines_people', 'a26:Category:American_Airlines')).
delete('skos:broader'('a26:Category:Transport_in_Greater_Moncton', 'a26:Category:Transport_in_New_Brunswick_by_city')).
delete('skos:broader'('a26:Category:Graphemes', 'a26:Category:Units_of_morphological_analysis')).
delete('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Dog_breeding')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:1977_in_British_Columbia')).
delete('skos:broader'('a26:Category:Aguadilla_Isabela_San_Sebastián_metropolitan_area', 'a26:Category:Metropolitan_areas_of_Puerto_Rico')).
delete('skos:broader'('a26:Category:South_African_people_of_Zimbabwean_descent', 'a26:Category:South_Africa_Zimbabwe_relations')).
delete('skos:broader'('a26:Category:Major_League_Baseball_players_with_retired_numbers', 'a26:Category:Major_League_Baseball_players')).
delete('skos:broader'('a26:Category:Neighbourhoods_of_Helsinki', 'a26:Category:Geography_of_Helsinki')).
delete('skos:broader'('a26:Category:Northwest_Territories_territorial_electoral_districts', 'a26:Category:Canadian_provincial_and_territorial_electoral_districts')).
delete('skos:broader'('a26:Category:Peers', 'a26:Category:British_people_by_rank')).
delete('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Analysis')).
delete('skos:broader'('a26:Category:Organizations_based_in_the_United_States_by_state', 'a26:Category:Society_of_the_United_States_by_state')).
delete('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Chemistry')).
delete('skos:broader'('a26:Category:Organizations_based_in_the_United_States_by_state', 'a26:Category:Organizations_based_in_the_United_States')).
delete('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_sports_competitions_hosted_by_France')).
delete('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:Establishments_in_British_Columbia_by_year')).
delete('skos:broader'('a26:Category:Companies_based_in_Atlanta_Georgia', 'a26:Category:Companies_based_in_Georgia_U.S._state_by_city')).
delete('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
delete('skos:broader'('a26:Category:Albums_by_Ugandan_artists', 'a26:Category:Works_by_Ugandan_people')).
delete('skos:broader'('a26:Category:KMFDM', 'a26:Category:Wikipedia_categories_named_after_German_musical_groups')).
delete('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:19th_century_in_England')).
delete('skos:broader'('a26:Category:Austrian_Football_Bundesliga_players', 'a26:Category:Association_football_players_by_competition')).
delete('skos:broader'('a26:Category:Mythological_sword_fighters', 'a26:Category:Mythological_characters')).
delete('skos:broader'('a26:Category:Table_tennis_in_North_America', 'a26:Category:Sport_in_North_America_by_sport')).
delete('skos:broader'('a26:Category:Screenshots_of_Windows_Server', 'a26:Category:Screenshots_of_Microsoft_Windows')).
delete('skos:broader'('a26:Category:MCG_objects', 'a26:Category:MCG_objects')).
delete('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Scottish_architecture')).
delete('skos:broader'('a26:Category:Monument_types', 'a26:Category:Archaeology_of_structures')).
delete('skos:broader'('a26:Category:African_culture_by_nationality', 'a26:Category:Culture_by_nationality')).
delete('skos:broader'('a26:Category:Exoplanet_catalogues', 'a26:Category:Exoplanetology')).
delete('skos:broader'('a26:Category:Płock_County', 'a26:Category:Land_counties_of_Masovian_Voivodeship')).
delete('skos:broader'('a26:Category:People_from_Madrid', 'a26:Category:Madrilenian_people')).
delete('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Cinema_of_Brazil')).
delete('skos:broader'('a26:Category:Buildings_and_structures_in_Dickinson_County_Iowa', 'a26:Category:Buildings_and_structures_in_Iowa_by_county')).
delete('skos:broader'('a26:Category:African_culture_by_nationality', 'a26:Category:African_culture')).
delete('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_sculptors')).
delete('skos:broader'('a26:Category:Defunct_American_football_teams', 'a26:Category:Defunct_sports_teams')).
delete('skos:broader'('a26:Category:British_adventure_films', 'a26:Category:British_films_by_genre')).
delete('skos:broader'('a26:Category:Bielsk_County', 'a26:Category:Land_counties_of_Podlaskie_Voivodeship')).
delete('skos:broader'('a26:Category:British_tubists', 'a26:Category:Tubists_by_nationality')).
delete('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Sport_shooters_by_nationality')).
delete('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Computer_languages')).
delete('skos:broader'('a26:Category:Member_states_of_the_United_Nations', 'a26:Category:United_Nations')).
delete('skos:broader'('a26:Category:Ethnic_groups_in_Arizona', 'a26:Category:Ethnic_groups_in_the_United_States_by_state')).
delete('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Peruvian_sportspeople')).
delete('skos:broader'('a26:Category:Steampunk_films', 'a26:Category:Science_fiction_films_by_genre')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_rulers')).
