add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=579713')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=941794')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1341970&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=494177&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=647734')).
add('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/cavdarhisar')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=618845')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1456382&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=412132&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=781558')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=455755&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=488853')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=2015515')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=618847')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=608239')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=742024&method=min&width=141&height=111')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/kilisik')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/shahrestan-e_andimeshk')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1486660')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/bergkamen')).
