add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse19')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent171')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent218')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent192')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent50')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse37')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent68')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse15')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent210')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent111')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent102')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent70')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent186')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent186')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent269')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent6')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent87')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent386')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent85')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent155')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent39')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent258')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent128')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent37')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent440')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent379')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent249')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent104')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent9')).
