add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent156')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent369')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent173')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent195')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent197')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent382')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent343')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse22')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor7')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent270')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent90')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor3')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse37')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent440')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent22')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent206')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent164')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent249')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor3')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse23')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent104')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse19')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent14')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent58')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent258')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent93')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent419')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse29')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent24')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent64')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent6')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent284')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
