add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent267')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent376')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent306')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent95')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent349')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent47')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent203')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent124')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent146')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent100')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent91')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent62')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent155')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse37')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor5')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent294')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent27')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent181')).
