add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent123')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent107')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent48')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent332')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse42')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent13')).
add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent79')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent420')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent69')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent255')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent376')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent199')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent52')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent29')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent189')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor12')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent103')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent101')).
