add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent386')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse29')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent76')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent331')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent126')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent313')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent186')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent249')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent310')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent232')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent278')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent58')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent258')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse20')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor7')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent19')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent90')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent85')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent379')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent108')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent180')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent220')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent269')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse23')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent22')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse15')).
