add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent331')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent199')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent11')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent168')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent14')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent197')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor4')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor7')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent25')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse46')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent19')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent102')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent92')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent70')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent10')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent220')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent212')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent259')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent249')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse48')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse23')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
