add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent76')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse14')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent427')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent156')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent347')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent218')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent313')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent180')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent382')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent153')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent24')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent299')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent79')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent128')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent14')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent68')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent331')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent437')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent207')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent168')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent314')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent206')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent38')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent64')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent90')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse36')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent2')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse15')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
