add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent413', 'http://www.Department2.University0.edu/Course5')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent199', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent253', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent81', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor6', 'http://www.University294.edu')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent225', 'http://www.Department0.University0.edu/AssociateProfessor11')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent344', 'http://www.Department2.University0.edu/Course23')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent133', '"UndergraduateStudent133@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent378', 'http://www.Department1.University0.edu/Course35')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor12/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor12')).
