add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent221', 'http://www.Department0.University0.edu/Course12')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor9/Publication8', 'http://www.Department2.University0.edu/AssociateProfessor9')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication4', 'http://www.Department1.University0.edu/GraduateStudent85')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent13', 'http://www.Department0.University0.edu/FullProfessor3')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent414', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent109', 'http://www.Department1.University0.edu/AssistantProfessor6')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent34', 'http://www.Department2.University0.edu/Course13')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor6/Publication4', 'http://www.Department1.University0.edu/AssociateProfessor6')).
delete('a1:teachingAssistantOf'('http://www.Department1.University0.edu/GraduateStudent79', 'http://www.Department1.University0.edu/Course34')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent362', 'http://www.Department1.University0.edu/Course35')).
