add('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:1977_in_British_Columbia')).
add('skos:broader'('a26:Category:Hungarian_people_of_Slovenian_descent', 'a26:Category:Hungarian_people_by_ethnic_or_national_origin')).
add('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Sport_shooters_by_nationality')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Chemistry')).
add('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Education_in_Alameda_County_California')).
add('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Non-metropolitan_districts_of_Somerset')).
add('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:Racquetball_players_by_nationality')).
add('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Peruvian_sportspeople')).
add('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:British_businesspeople')).
add('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Mammal_breeds')).
delete('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Irish_Sea')).
delete('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Computer_languages')).
delete('skos:broader'('a26:Category:Geography_of_Greene_County_New_York', 'a26:Category:Geography_of_the_Hudson_Valley')).
delete('skos:broader'('a26:Category:Organizations_based_in_the_United_States_by_state', 'a26:Category:Organizations_based_in_the_United_States')).
delete('skos:broader'('a26:Category:Philippine_society', 'a26:Category:Philippines')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:Establishments_in_British_Columbia_by_year')).
delete('skos:broader'('a26:Category:Conglomerate_companies_of_France', 'a26:Category:Companies_of_France')).
delete('skos:broader'('a26:Category:DC_Comics-related_lists', 'a26:Category:Comic_lists_by_franchise')).
delete('skos:broader'('a26:Category:Geography_of_the_Northern_Territory', 'a26:Category:Geography_of_Australia_by_state_or_territory')).
delete('skos:broader'('a26:Category:Bender_Moldova', 'a26:Category:Districts_of_Moldova')).
