add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent85')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent385')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent54')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent88')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent155')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent92')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent7')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent345')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent76')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent90')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent216')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent38')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent108')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent192')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent50')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent212')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent37')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent2')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent440')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent68')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent331')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse27')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse25')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent358')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent125')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent181')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent186')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent16')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent90')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent171')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse3')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse4')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent130')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent211')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent19')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor7')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent270')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent90')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent84')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse29')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent419')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse29')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent23')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent128')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent33')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent207')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent206')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent314')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent313')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent180')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent249')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent318')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent203')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent6')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse48')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent103')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent431')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent9')).
