add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent58')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent76')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent323')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent347')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent153')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent382')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse7')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent232')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent128')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent257')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent25')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor7')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent270')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent251')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent210')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent419')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent126')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent45')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent111')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent33')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent64')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent249')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent185')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent180')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor4')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent264')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent318')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent249')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent6')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent5')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent128')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent19')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent104')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent385')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent155')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent54')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent7')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent345')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent427')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent76')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent156')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent10')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent150')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent195')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent197')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent384')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent258')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent93')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent10')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent52')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent277')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent37')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent2')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse15')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent70')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent45')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse25')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent437')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent181')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent186')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent16')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse46')).
