add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent221', 'http://www.Department0.University0.edu/Course12')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent305', '"UndergraduateStudent305@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor0/Publication14', 'http://www.Department0.University0.edu/GraduateStudent63')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent343', 'http://www.Department2.University0.edu/Course34')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor1/Publication18', 'http://www.Department2.University0.edu/GraduateStudent74')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor6/Publication4', 'http://www.Department2.University0.edu/AssistantProfessor6')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent35', 'http://www.Department0.University0.edu/GraduateCourse21')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent301', 'http://www.Department2.University0.edu/Course24')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent234', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent414', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent246', '"UndergraduateStudent246@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent139', '"UndergraduateStudent139@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor2/Publication6', 'http://www.Department0.University0.edu/AssociateProfessor2')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent83', 'http://www.Department1.University0.edu/Course51')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor5/Publication4', 'http://www.Department0.University0.edu/GraduateStudent91')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor9/Publication8', 'http://www.Department2.University0.edu/AssociateProfessor9')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication4', 'http://www.Department1.University0.edu/GraduateStudent85')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent417', '"UndergraduateStudent417@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication1', 'http://www.Department1.University0.edu/GraduateStudent103')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent384', 'http://www.Department1.University0.edu/Course36')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent132', '"UndergraduateStudent132@Department2.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent10', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent368', 'http://www.Department1.University0.edu/Course51')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent28', 'http://www.Department1.University0.edu/GraduateCourse5')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication14', 'http://www.Department1.University0.edu/FullProfessor5')).
delete('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent12', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor6/Publication7', 'http://www.Department0.University0.edu/FullProfessor6')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor10', 'http://www.Department2.University0.edu/GraduateCourse22')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent384', 'http://www.Department2.University0.edu/Course37')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication6', 'http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor0/Publication1', 'http://www.Department2.University0.edu/GraduateStudent2')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/AssociateProfessor12', 'http://www.University459.edu')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent363', '"UndergraduateStudent363@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent48', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent38', 'http://www.Department2.University0.edu/GraduateCourse30')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor3/Publication8', 'http://www.Department2.University0.edu/AssistantProfessor3')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication1', 'http://www.Department0.University0.edu/AssociateProfessor11')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent246', 'http://www.Department1.University0.edu/Course23')).
delete('a1:mastersDegreeFrom'('http://www.Department1.University0.edu/AssociateProfessor4', 'http://www.University492.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/Course39')).
