add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent28', '"UndergraduateStudent28@Department0.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent117', '"GraduateStudent117@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent217', 'http://www.Department2.University0.edu/Course31')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent178', '"UndergraduateStudent178@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent172', 'http://www.Department0.University0.edu/Course3')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor1')).
add('a1:emailAddress'('http://www.Department1.University0.edu/Lecturer6', '"Lecturer6@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication4', 'http://www.Department0.University0.edu/GraduateStudent77')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse45')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent283', 'http://www.Department1.University0.edu/Course27')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent309', 'http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent127', 'http://www.Department2.University0.edu/Course13')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent20', '"UndergraduateStudent20@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication1', 'http://www.Department0.University0.edu/GraduateStudent106')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent52', '"GraduateStudent52@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication14', 'http://www.Department1.University0.edu/GraduateStudent113')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication15', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor3', 'http://www.University616.edu')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent427', 'http://www.Department1.University0.edu/Course46')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent167', '"UndergraduateStudent167@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent102', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor3/Publication6', 'http://www.Department1.University0.edu/AssociateProfessor3')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent96', '"GraduateStudent96@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent178', 'http://www.Department2.University0.edu/Course46')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent242', 'http://www.Department0.University0.edu/Course19')).
delete('a1:telephone'('http://www.Department0.University0.edu/AssociateProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent11', 'http://www.Department0.University0.edu/Course22')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent420', 'http://www.Department2.University0.edu/Course29')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent118', 'http://www.Department2.University0.edu/Course2')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent276', 'http://www.Department0.University0.edu/Course20')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent4', 'http://www.University220.edu')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent362', 'http://www.Department2.University0.edu/Course10')).
delete('a1:telephone'('http://www.Department0.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication1', 'http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:telephone'('http://www.Department1.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor5/Publication4', 'http://www.Department1.University0.edu/GraduateStudent78')).
delete('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor12', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent105', 'http://www.Department0.University0.edu/GraduateCourse20')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent4', '"GraduateStudent4@Department2.University0.edu"^^xsd:string')).
