add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent168', 'http://www.Department0.University0.edu/Course20')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/Lecturer0/Publication1', 'http://www.Department0.University0.edu/GraduateStudent17')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor1/Publication18', 'http://www.Department2.University0.edu/GraduateStudent74')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent179', 'http://www.Department0.University0.edu/Course1')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent211', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent2', '"GraduateStudent2@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor13/Publication2', 'http://www.Department0.University0.edu/GraduateStudent34')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent384', 'http://www.Department2.University0.edu/Course37')).
add('a1:doctoralDegreeFrom'('http://www.Department2.University0.edu/FullProfessor6', 'http://www.University186.edu')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor5/Publication4', 'http://www.Department0.University0.edu/GraduateStudent91')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent71', 'http://www.Department2.University0.edu/GraduateCourse43')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication4', 'http://www.Department1.University0.edu/GraduateStudent85')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent338', 'http://www.Department1.University0.edu/Course42')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent311', '"UndergraduateStudent311@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent384', 'http://www.Department1.University0.edu/Course36')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor0/Publication6', 'http://www.Department2.University0.edu/AssistantProfessor0')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor2/Publication2', 'http://www.Department0.University0.edu/GraduateStudent35')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/Course39')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent51', '"GraduateStudent51@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent132', '"UndergraduateStudent132@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent90', '"UndergraduateStudent90@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor1/Publication2', 'http://www.Department1.University0.edu/GraduateStudent40')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent77', 'http://www.Department1.University0.edu/Course18')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication1', 'http://www.Department1.University0.edu/AssociateProfessor4')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent388', 'http://www.Department1.University0.edu/Course35')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent54', 'http://www.Department1.University0.edu/GraduateCourse35')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent17', '"UndergraduateStudent17@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor0/Publication4', 'http://www.Department0.University0.edu/FullProfessor0')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor10', 'http://www.Department2.University0.edu/GraduateCourse22')).
delete('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/FullProfessor8', 'http://www.University850.edu')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent109', '"UndergraduateStudent109@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent83', 'http://www.Department1.University0.edu/Course51')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent192', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent261', 'http://www.Department2.University0.edu/Course20')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent57', 'http://www.Department0.University0.edu/Course13')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent99', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent97', '"UndergraduateStudent97@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent290', '"UndergraduateStudent290@Department0.University0.edu"^^xsd:string')).
delete('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/AssistantProfessor5', 'http://www.University911.edu')).
