add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent351', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent213', 'http://www.Department1.University0.edu/Course8')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse41')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent147', 'http://www.Department2.University0.edu/Course31')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor1')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/AssistantProfessor0', 'http://www.University641.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent251', 'http://www.Department0.University0.edu/Course36')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor2', 'http://www.Department2.University0.edu/Course33')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor6', 'http://www.University944.edu')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent186', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent68', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication4', 'http://www.Department0.University0.edu/GraduateStudent77')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor8', 'http://www.Department2.University0.edu/GraduateCourse20')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent260', 'http://www.Department2.University0.edu/Course18')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent183', 'http://www.Department0.University0.edu/Course25')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent405', 'http://www.Department1.University0.edu/Course48')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent52', '"GraduateStudent52@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent51', 'http://www.Department0.University0.edu/GraduateCourse11')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent244', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/FullProfessor1', '"FullProfessor1@Department0.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent325', 'http://www.Department0.University0.edu/AssistantProfessor6')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent43', 'http://www.Department2.University0.edu/Course46')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent373', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor3/Publication6', 'http://www.Department1.University0.edu/AssociateProfessor3')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent13', 'http://www.Department2.University0.edu/Course37')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent96', '"GraduateStudent96@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent178', 'http://www.Department2.University0.edu/Course46')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent281', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent387', 'http://www.Department1.University0.edu/Course35')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication15', 'http://www.Department0.University0.edu/GraduateStudent94')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor0/Publication3', 'http://www.Department1.University0.edu/GraduateStudent11')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent276', 'http://www.Department0.University0.edu/Course20')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication4', 'http://www.Department0.University0.edu/AssistantProfessor6')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent118', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer3/Publication0', 'http://www.Department1.University0.edu/Lecturer3')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent171', '"UndergraduateStudent171@Department2.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent140', 'http://www.Department1.University0.edu/FullProfessor4')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent5', 'http://www.Department1.University0.edu/GraduateCourse8')).
