add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor8/Publication7', 'http://www.Department1.University0.edu/GraduateStudent32')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication7', 'http://www.Department1.University0.edu/FullProfessor8')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor4/Publication2', 'http://www.Department2.University0.edu/AssistantProfessor4')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent178', '"UndergraduateStudent178@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent34', '"GraduateStudent34@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent43', 'http://www.Department2.University0.edu/Course46')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor3/Publication6', 'http://www.Department1.University0.edu/AssociateProfessor3')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent147', 'http://www.Department2.University0.edu/Course31')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor1')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/AssistantProfessor0', 'http://www.University641.edu')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent174', 'http://www.Department2.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent195', 'http://www.Department2.University0.edu/Course3')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor0/Publication3', 'http://www.Department1.University0.edu/GraduateStudent11')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication4', 'http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent405', 'http://www.Department1.University0.edu/Course48')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent85', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication6', 'http://www.Department2.University0.edu/GraduateStudent71')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication15', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent64', 'http://www.Department0.University0.edu/GraduateCourse32')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent4', '"GraduateStudent4@Department2.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent351', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent395', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent283', 'http://www.Department2.University0.edu/Course0')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent136', 'http://www.Department0.University0.edu/Course13')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse20')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent217', 'http://www.Department2.University0.edu/Course37')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent319', '"UndergraduateStudent319@Department0.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent309', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent283', 'http://www.Department1.University0.edu/Course27')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent11', 'http://www.Department0.University0.edu/Course22')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent88', 'http://www.University398.edu')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent276', 'http://www.Department0.University0.edu/Course20')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent118', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent161', '"UndergraduateStudent161@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent415', '"UndergraduateStudent415@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent207', 'http://www.Department0.University0.edu/Course32')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor3', 'http://www.University616.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent114', 'http://www.Department1.University0.edu/Course28')).
