add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent213', 'http://www.Department1.University0.edu/Course8')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent172', 'http://www.Department2.University0.edu/Course2')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent178', '"UndergraduateStudent178@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent254', 'http://www.Department1.University0.edu/Course36')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent178', 'http://www.Department2.University0.edu/Course46')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/AssistantProfessor0', 'http://www.University641.edu')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent283', 'http://www.Department2.University0.edu/Course0')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent195', 'http://www.Department2.University0.edu/Course3')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent1', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/FullProfessor8', '"FullProfessor8@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent260', 'http://www.Department2.University0.edu/Course18')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent118', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent85', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication6', 'http://www.Department2.University0.edu/GraduateStudent71')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent301', 'http://www.Department1.University0.edu/Course20')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent28', '"GraduateStudent28@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent64', 'http://www.Department0.University0.edu/GraduateCourse32')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent241', '"UndergraduateStudent241@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent4', '"GraduateStudent4@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent183', 'http://www.Department2.University0.edu/Course10')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent34', '"GraduateStudent34@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication17', 'http://www.Department0.University0.edu/GraduateStudent95')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor6/Publication4', 'http://www.Department2.University0.edu/GraduateStudent105')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent339', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent319', '"UndergraduateStudent319@Department0.University0.edu"^^xsd:string')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor0', 'http://www.Department1.University0.edu/GraduateCourse0')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent49', 'http://www.Department0.University0.edu/Course8')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor8', 'http://www.Department2.University0.edu/GraduateCourse20')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent305', 'http://www.Department2.University0.edu/Course40')).
delete('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent89', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor2/Publication2', 'http://www.Department1.University0.edu/AssistantProfessor2')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor7', 'http://www.Department0.University0.edu/GraduateCourse24')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent171', '"UndergraduateStudent171@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent23', '"UndergraduateStudent23@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent51', 'http://www.Department0.University0.edu/GraduateCourse11')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent244', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication14', 'http://www.Department1.University0.edu/GraduateStudent113')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication8', 'http://www.Department2.University0.edu/GraduateStudent14')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication4', 'http://www.Department2.University0.edu/FullProfessor3')).
