add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent352', 'http://www.Department1.University0.edu/Course47')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent172', 'http://www.Department2.University0.edu/Course2')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent47', 'http://www.University963.edu')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication15', 'http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent387', 'http://www.Department1.University0.edu/Course35')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication2', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent165', 'http://www.Department2.University0.edu/Course41')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent319', '"UndergraduateStudent319@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor9/Publication7', 'http://www.Department2.University0.edu/AssociateProfessor9')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer3/Publication0', 'http://www.Department1.University0.edu/Lecturer3')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent362', 'http://www.Department2.University0.edu/Course10')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent186', 'http://www.Department0.University0.edu/Course45')).
add('a1:telephone'('http://www.Department0.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor5/Publication4', 'http://www.Department1.University0.edu/GraduateStudent78')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent52', '"GraduateStudent52@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent114', 'http://www.Department1.University0.edu/Course28')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication3', 'http://www.Department1.University0.edu/GraduateStudent72')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent117', '"GraduateStudent117@Department1.University0.edu"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent66', 'http://www.University904.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent372', '"UndergraduateStudent372@Department1.University0.edu"^^xsd:string')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor8', 'http://www.Department2.University0.edu/GraduateCourse20')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication4', 'http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent125', 'http://www.Department0.University0.edu/Course34')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent193', 'http://www.Department1.University0.edu/Course32')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication4', 'http://www.Department0.University0.edu/AssociateProfessor12')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent395', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse41')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent166', 'http://www.Department0.University0.edu/Course43')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication1', 'http://www.Department0.University0.edu/GraduateStudent107')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent251', 'http://www.Department0.University0.edu/Course36')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent291', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent417', 'http://www.Department1.University0.edu/Course8')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent191', 'http://www.Department2.University0.edu/Course45')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor1/Publication13', 'http://www.Department0.University0.edu/FullProfessor1')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication15', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent125', 'http://www.Department2.University0.edu/Course17')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent427', 'http://www.Department1.University0.edu/Course46')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent16', '"GraduateStudent16@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor4/Publication2', 'http://www.Department2.University0.edu/AssistantProfessor4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent128', 'http://www.Department1.University0.edu/Course11')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent96', '"GraduateStudent96@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor6/Publication4', 'http://www.Department2.University0.edu/GraduateStudent105')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent339', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse45')).
add('a1:emailAddress'('http://www.Department1.University0.edu/FullProfessor8', '"FullProfessor8@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication2', 'http://www.Department0.University0.edu/GraduateStudent15')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent49', 'http://www.Department0.University0.edu/Course8')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent27', 'http://www.Department2.University0.edu/Course3')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent301', 'http://www.Department1.University0.edu/Course20')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent105', 'http://www.Department0.University0.edu/GraduateCourse20')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent167', '"UndergraduateStudent167@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent183', 'http://www.Department2.University0.edu/Course10')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent124', 'http://www.Department2.University0.edu/Course16')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent331', 'http://www.Department2.University0.edu/Course41')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent174', 'http://www.Department2.University0.edu/Course26')).
delete('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor11', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent1', 'http://www.Department2.University0.edu/AssistantProfessor6')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent85', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent53', 'http://www.Department0.University0.edu/Course27')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent290', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor1/Publication6', 'http://www.Department0.University0.edu/GraduateStudent98')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor3', 'http://www.University616.edu')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent351', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent314', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent213', 'http://www.Department1.University0.edu/Course8')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent147', 'http://www.Department0.University0.edu/AssistantProfessor7')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent215', 'http://www.Department0.University0.edu/Course7')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/Lecturer6', '"Lecturer6@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent242', 'http://www.Department0.University0.edu/Course19')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor2/Publication2', 'http://www.Department1.University0.edu/AssistantProfessor2')).
delete('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent89', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent11', 'http://www.Department1.University0.edu/Course13')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent28', '"GraduateStudent28@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent4', '"GraduateStudent4@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication7', 'http://www.Department2.University0.edu/FullProfessor3')).
delete('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent68', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent90', 'http://www.Department1.University0.edu/GraduateCourse4')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent276', 'http://www.Department0.University0.edu/Course20')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent183', 'http://www.Department0.University0.edu/Course25')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent197', 'http://www.Department2.University0.edu/Course7')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent415', '"UndergraduateStudent415@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent28', 'http://www.Department1.University0.edu/Course8')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent244', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent25', 'http://www.Department1.University0.edu/GraduateCourse10')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication4', 'http://www.Department2.University0.edu/FullProfessor3')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent178', '"UndergraduateStudent178@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor2/Publication17', 'http://www.Department1.University0.edu/GraduateStudent83')).
delete('a1:doctoralDegreeFrom'('http://www.Department2.University0.edu/AssociateProfessor8', 'http://www.University651.edu')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication17', 'http://www.Department0.University0.edu/GraduateStudent95')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent103', 'http://www.Department0.University0.edu/GraduateCourse42')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent309', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent11', 'http://www.Department0.University0.edu/Course22')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent404', '"UndergraduateStudent404@Department2.University0.edu"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent20', '"UndergraduateStudent20@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent199', '"UndergraduateStudent199@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent64', 'http://www.Department0.University0.edu/GraduateCourse32')).
delete('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent44', 'http://www.Department0.University0.edu/Course45')).
