add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent352', 'http://www.Department1.University0.edu/Course47')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent56', 'http://www.Department1.University0.edu/Course19')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent124', 'http://www.Department2.University0.edu/Course16')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent102', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent43', 'http://www.Department2.University0.edu/Course46')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent39', '"GraduateStudent39@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent331', 'http://www.Department2.University0.edu/Course41')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent387', 'http://www.Department1.University0.edu/Course35')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor2', 'http://www.Department2.University0.edu/Course33')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication4', 'http://www.Department0.University0.edu/GraduateStudent77')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent90', 'http://www.Department1.University0.edu/GraduateCourse4')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication0', 'http://www.Department0.University0.edu/FullProfessor4')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent0', 'http://www.Department0.University0.edu/FullProfessor2')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent197', 'http://www.Department2.University0.edu/Course7')).
add('a1:telephone'('http://www.Department1.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication6', 'http://www.Department2.University0.edu/GraduateStudent71')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor1/Publication13', 'http://www.Department0.University0.edu/FullProfessor1')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent52', '"GraduateStudent52@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication15', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor1/Publication6', 'http://www.Department0.University0.edu/GraduateStudent98')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent125', 'http://www.Department2.University0.edu/Course17')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication3', 'http://www.Department1.University0.edu/GraduateStudent72')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent314', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent78', 'http://www.Department2.University0.edu/Course46')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent34', '"GraduateStudent34@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor1')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication12', 'http://www.Department2.University0.edu/GraduateStudent55')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent24', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent92', 'http://www.Department0.University0.edu/AssistantProfessor1')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent339', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent249', 'http://www.Department1.University0.edu/AssociateProfessor7')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent372', '"UndergraduateStudent372@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent49', 'http://www.Department0.University0.edu/Course8')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent118', 'http://www.Department2.University0.edu/Course2')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent85', 'http://www.Department0.University0.edu/Course41')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent89', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent23', '"UndergraduateStudent23@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication14', 'http://www.Department1.University0.edu/GraduateStudent113')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication8', 'http://www.Department2.University0.edu/GraduateStudent14')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent125', 'http://www.Department0.University0.edu/Course34')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent217', 'http://www.Department2.University0.edu/Course31')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent325', 'http://www.Department0.University0.edu/AssistantProfessor6')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent47', 'http://www.University963.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent321', 'http://www.Department1.University0.edu/Course7')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent172', 'http://www.Department0.University0.edu/Course3')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent251', 'http://www.Department0.University0.edu/Course36')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication7', 'http://www.Department2.University0.edu/FullProfessor3')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication15', 'http://www.Department0.University0.edu/GraduateStudent94')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent118', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor6/Publication17', 'http://www.Department2.University0.edu/AssociateProfessor6')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent183', 'http://www.Department0.University0.edu/Course25')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent85', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent291', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent53', 'http://www.Department0.University0.edu/Course27')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent290', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent427', 'http://www.Department1.University0.edu/Course46')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent5', 'http://www.Department1.University0.edu/GraduateCourse8')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent16', '"GraduateStudent16@Department0.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent53', 'http://www.Department1.University0.edu/AssistantProfessor3')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent213', 'http://www.Department0.University0.edu/Course17')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor4/Publication2', 'http://www.Department2.University0.edu/AssistantProfessor4')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor2/Publication17', 'http://www.Department1.University0.edu/GraduateStudent83')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent96', '"GraduateStudent96@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent147', 'http://www.Department2.University0.edu/Course31')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent147', 'http://www.Department0.University0.edu/AssistantProfessor7')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor6/Publication4', 'http://www.Department2.University0.edu/GraduateStudent105')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent242', 'http://www.Department0.University0.edu/Course19')).
delete('a1:telephone'('http://www.Department0.University0.edu/AssociateProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse20')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse45')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent283', 'http://www.Department1.University0.edu/Course27')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/FullProfessor8', '"FullProfessor8@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent11', 'http://www.Department0.University0.edu/Course22')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication2', 'http://www.Department0.University0.edu/GraduateStudent15')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent404', '"UndergraduateStudent404@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent199', '"UndergraduateStudent199@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent27', 'http://www.Department2.University0.edu/Course3')).
delete('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/Lecturer4', 'http://www.University421.edu')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent241', '"UndergraduateStudent241@Department2.University0.edu"^^xsd:string')).
