add('a1:publicationAuthor'('http://www.Department0.University0.edu/Lecturer0/Publication1', 'http://www.Department0.University0.edu/GraduateStudent17')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent44', '"GraduateStudent44@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent369', 'http://www.Department1.University0.edu/Course24')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent211', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent158', 'http://www.Department1.University0.edu/AssociateProfessor4')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent316', '"UndergraduateStudent316@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor6/Publication7', 'http://www.Department0.University0.edu/FullProfessor6')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent112', 'http://www.Department2.University0.edu/Course10')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent414', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication6', 'http://www.Department1.University0.edu/GraduateStudent73')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent97', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent303', '"UndergraduateStudent303@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent69', 'http://www.Department0.University0.edu/GraduateCourse11')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent169', '"UndergraduateStudent169@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor2/Publication6', 'http://www.Department0.University0.edu/AssociateProfessor2')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent12', 'http://www.Department0.University0.edu/AssociateProfessor9')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent3', '"UndergraduateStudent3@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent57', 'http://www.Department0.University0.edu/Course13')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent176', 'http://www.Department0.University0.edu/Course30')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent289', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent305', '"UndergraduateStudent305@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent2', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent109', 'http://www.Department1.University0.edu/AssistantProfessor6')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent418', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor3/Publication3', 'http://www.Department1.University0.edu/GraduateStudent85')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent389', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent67', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent216', '"UndergraduateStudent216@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor0/Publication4', 'http://www.Department0.University0.edu/FullProfessor0')).
add('a1:doctoralDegreeFrom'('http://www.Department2.University0.edu/FullProfessor6', 'http://www.University186.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent363', '"UndergraduateStudent363@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent164', 'http://www.Department2.University0.edu/Course6')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent324', 'http://www.Department2.University0.edu/Course13')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent83', 'http://www.Department1.University0.edu/Course51')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication4', 'http://www.Department1.University0.edu/GraduateStudent85')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent100', '"UndergraduateStudent100@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication1', 'http://www.Department0.University0.edu/AssociateProfessor11')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent69', 'http://www.Department0.University0.edu/Course20')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent384', 'http://www.Department1.University0.edu/Course36')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent182', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent65', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent90', '"UndergraduateStudent90@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent99', '"GraduateStudent99@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent388', 'http://www.Department1.University0.edu/Course35')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent35', 'http://www.Department0.University0.edu/GraduateCourse21')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent338', 'http://www.Department1.University0.edu/Course42')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent192', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor3/Publication8', 'http://www.Department2.University0.edu/AssistantProfessor3')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent99', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/Course39')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent140', 'http://www.Department0.University0.edu/Course1')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent52', '"GraduateStudent52@Department0.University0.edu"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent105', 'http://www.University95.edu')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/AssociateProfessor11', '"AssociateProfessor11@Department0.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent132', '"UndergraduateStudent132@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent208', '"UndergraduateStudent208@Department0.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/AssistantProfessor6', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor3/Publication9', 'http://www.Department0.University0.edu/GraduateStudent31')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent179', 'http://www.Department0.University0.edu/Course1')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent144', 'http://www.Department1.University0.edu/Course52')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent276', '"UndergraduateStudent276@Department2.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent12', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor9/Publication4', 'http://www.Department1.University0.edu/GraduateStudent123')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent246', '"UndergraduateStudent246@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent2', '"GraduateStudent2@Department0.University0.edu"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent9', 'http://www.University549.edu')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor2/Publication3', 'http://www.Department0.University0.edu/GraduateStudent67')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent109', '"UndergraduateStudent109@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor10/Publication9', 'http://www.Department2.University0.edu/AssociateProfessor10')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent38', 'http://www.Department2.University0.edu/GraduateCourse30')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent113', 'http://www.Department2.University0.edu/Course27')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent434', 'http://www.Department1.University0.edu/Course23')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent173', 'http://www.Department1.University0.edu/Course38')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent89', '"UndergraduateStudent89@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent129', 'http://www.Department0.University0.edu/Course45')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent261', 'http://www.Department2.University0.edu/Course20')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent342', 'http://www.Department2.University0.edu/Course32')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent258', 'http://www.Department0.University0.edu/Course31')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent30', 'http://www.Department1.University0.edu/Course9')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent46', 'http://www.University723.edu')).
