add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent370', 'http://www.Department2.University0.edu/Course46')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor11/Publication10', 'http://www.Department2.University0.edu/AssociateProfessor11')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor8/Publication14', 'http://www.Department2.University0.edu/AssociateProfessor8')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor1/Publication18', 'http://www.Department2.University0.edu/GraduateStudent74')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent45', 'http://www.Department2.University0.edu/Course5')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent99', '"GraduateStudent99@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent369', 'http://www.Department1.University0.edu/Course24')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication1', 'http://www.Department1.University0.edu/AssociateProfessor4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent122', 'http://www.Department1.University0.edu/Course10')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent316', '"UndergraduateStudent316@Department0.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent12', 'http://www.Department2.University0.edu/AssociateProfessor2')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent414', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor6/Publication4', 'http://www.Department1.University0.edu/AssociateProfessor6')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor10', 'http://www.Department2.University0.edu/GraduateCourse22')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent69', 'http://www.Department0.University0.edu/GraduateCourse11')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent57', 'http://www.Department0.University0.edu/Course13')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent52', '"GraduateStudent52@Department0.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent305', '"UndergraduateStudent305@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent2', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor3/Publication9', 'http://www.Department0.University0.edu/GraduateStudent31')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent27', '"GraduateStudent27@Department2.University0.edu"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent97', 'http://www.University669.edu')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent13', 'http://www.Department0.University0.edu/FullProfessor3')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent389', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent26', '"UndergraduateStudent26@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent2', '"GraduateStudent2@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent98', 'http://www.Department2.University0.edu/Course7')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent282', 'http://www.Department1.University0.edu/Course0')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor0/Publication4', 'http://www.Department0.University0.edu/FullProfessor0')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/AssociateProfessor12', 'http://www.University459.edu')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent314', '"UndergraduateStudent314@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent434', 'http://www.Department1.University0.edu/Course23')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent105', 'http://www.Department1.University0.edu/Course46')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication1', 'http://www.Department0.University0.edu/AssociateProfessor11')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent420', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/FullProfessor4', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent342', 'http://www.Department2.University0.edu/Course32')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent384', 'http://www.Department1.University0.edu/Course36')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor2/Publication2', 'http://www.Department0.University0.edu/GraduateStudent35')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent51', '"GraduateStudent51@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent44', '"GraduateStudent44@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent388', 'http://www.Department1.University0.edu/Course35')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor4/Publication14', 'http://www.Department2.University0.edu/GraduateStudent44')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent158', 'http://www.Department1.University0.edu/AssociateProfessor4')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent28', 'http://www.Department1.University0.edu/GraduateCourse5')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication14', 'http://www.Department1.University0.edu/FullProfessor5')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent112', 'http://www.Department2.University0.edu/Course10')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor6/Publication7', 'http://www.Department0.University0.edu/FullProfessor6')).
delete('a1:teachingAssistantOf'('http://www.Department1.University0.edu/GraduateStudent79', 'http://www.Department1.University0.edu/Course34')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor13/Publication2', 'http://www.Department0.University0.edu/GraduateStudent34')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication6', 'http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor2/Publication0', 'http://www.Department2.University0.edu/AssociateProfessor2')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent22', 'http://www.Department2.University0.edu/AssociateProfessor7')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent284', '"UndergraduateStudent284@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent338', 'http://www.Department1.University0.edu/Course42')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor7/Publication11', 'http://www.Department1.University0.edu/GraduateStudent92')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent132', '"UndergraduateStudent132@Department2.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent10', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent418', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor1/Publication2', 'http://www.Department1.University0.edu/GraduateStudent40')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent216', '"UndergraduateStudent216@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor11/Publication12', 'http://www.Department2.University0.edu/AssociateProfessor11')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent276', '"UndergraduateStudent276@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor9/Publication4', 'http://www.Department1.University0.edu/GraduateStudent123')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent329', '"UndergraduateStudent329@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent205', 'http://www.Department2.University0.edu/Course3')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent384', 'http://www.Department2.University0.edu/Course37')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent363', '"UndergraduateStudent363@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent324', 'http://www.Department2.University0.edu/Course13')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent111', 'http://www.Department2.University0.edu/GraduateCourse19')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent89', '"UndergraduateStudent89@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication13', 'http://www.Department1.University0.edu/GraduateStudent21')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor4/Publication10', 'http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent189', 'http://www.Department2.University0.edu/Course33')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent97', '"UndergraduateStudent97@Department2.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent182', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent46', 'http://www.University723.edu')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent105', '"UndergraduateStudent105@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor0/Publication6', 'http://www.Department2.University0.edu/AssistantProfessor0')).
delete('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent44', 'http://www.Department0.University0.edu/Course45')).
