add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent359', 'http://www.Department1.University0.edu/Course9')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent279', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent325', 'http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent102', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent47', 'http://www.University963.edu')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent321', 'http://www.Department1.University0.edu/Course7')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse41')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent280', 'http://www.Department0.University0.edu/Course34')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent283', 'http://www.Department2.University0.edu/Course0')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent387', 'http://www.Department1.University0.edu/Course35')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent217', 'http://www.Department2.University0.edu/Course37')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent1', 'http://www.Department2.University0.edu/Course36')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent276', 'http://www.Department0.University0.edu/Course20')).
add('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor7', 'http://www.Department0.University0.edu/GraduateCourse24')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer3/Publication0', 'http://www.Department1.University0.edu/Lecturer3')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent291', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication1', 'http://www.Department0.University0.edu/FullProfessor7')).
add('a1:telephone'('http://www.Department0.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent53', 'http://www.Department0.University0.edu/Course27')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent415', '"UndergraduateStudent415@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent28', 'http://www.Department1.University0.edu/Course8')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent351', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/Lecturer6/Publication3', 'http://www.Department1.University0.edu/GraduateStudent72')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent16', '"GraduateStudent16@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent314', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor2/Publication17', 'http://www.Department1.University0.edu/GraduateStudent83')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent128', 'http://www.Department1.University0.edu/Course11')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication12', 'http://www.Department2.University0.edu/GraduateStudent55')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication17', 'http://www.Department0.University0.edu/GraduateStudent95')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor6', 'http://www.University944.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse20')).
add('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent287', 'http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent249', 'http://www.Department1.University0.edu/AssociateProfessor7')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor8', 'http://www.Department2.University0.edu/GraduateCourse20')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent4', 'http://www.University220.edu')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication1', 'http://www.Department0.University0.edu/GraduateStudent106')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent140', 'http://www.Department1.University0.edu/FullProfessor4')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent28', '"GraduateStudent28@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication8', 'http://www.Department2.University0.edu/GraduateStudent14')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent4', '"GraduateStudent4@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent352', 'http://www.Department1.University0.edu/Course47')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent147', 'http://www.Department1.University0.edu/AssociateProfessor10')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent166', 'http://www.Department0.University0.edu/Course43')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent251', 'http://www.Department0.University0.edu/Course36')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent331', 'http://www.Department2.University0.edu/Course41')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication15', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication4', 'http://www.Department0.University0.edu/GraduateStudent77')).
delete('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent68', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent319', '"UndergraduateStudent319@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent174', 'http://www.Department2.University0.edu/Course26')).
delete('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor11', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent1', 'http://www.Department2.University0.edu/AssistantProfessor6')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent183', 'http://www.Department0.University0.edu/Course25')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent118', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent0', 'http://www.Department0.University0.edu/FullProfessor2')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent197', 'http://www.Department2.University0.edu/Course7')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor5/Publication4', 'http://www.Department1.University0.edu/GraduateStudent78')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent186', 'http://www.Department0.University0.edu/Course45')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor1/Publication13', 'http://www.Department0.University0.edu/FullProfessor1')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent207', 'http://www.Department0.University0.edu/Course32')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent51', 'http://www.Department0.University0.edu/GraduateCourse11')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent178', '"UndergraduateStudent178@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor4/Publication2', 'http://www.Department2.University0.edu/AssistantProfessor4')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication7', 'http://www.Department1.University0.edu/FullProfessor8')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent13', 'http://www.Department2.University0.edu/Course37')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent373', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent147', 'http://www.Department0.University0.edu/AssistantProfessor7')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent103', 'http://www.Department0.University0.edu/GraduateCourse42')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent242', 'http://www.Department0.University0.edu/Course19')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor6/Publication4', 'http://www.Department2.University0.edu/GraduateStudent105')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent1', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent372', '"UndergraduateStudent372@Department1.University0.edu"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent405', 'http://www.Department1.University0.edu/Course48')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent199', '"UndergraduateStudent199@Department0.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent241', '"UndergraduateStudent241@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent147', 'http://www.Department0.University0.edu/Course46')).
delete('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent44', 'http://www.Department0.University0.edu/Course45')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent304', 'http://www.Department0.University0.edu/Course32')).
