add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent271', 'http://www.Department0.University0.edu/Course48')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent413', 'http://www.Department2.University0.edu/Course5')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse40')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication14', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent13', 'http://www.Department0.University0.edu/GraduateCourse37')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor2/Publication0', 'http://www.Department1.University0.edu/GraduateStudent37')).
add('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor7', 'http://www.Department0.University0.edu/Course23')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication5', 'http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent45', 'http://www.Department0.University0.edu/Course22')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent37', '"GraduateStudent37@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent86', '"UndergraduateStudent86@Department1.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent139', '"UndergraduateStudent139@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/Lecturer3', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor11/Publication11', 'http://www.Department2.University0.edu/AssociateProfessor11')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent268', 'http://www.Department0.University0.edu/Course37')).
add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent334', 'http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent163', 'http://www.Department0.University0.edu/Course18')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent193', 'http://www.Department0.University0.edu/Course17')).
add('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor3', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent103', 'http://www.Department2.University0.edu/FullProfessor4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent56', 'http://www.Department1.University0.edu/GraduateCourse16')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor4', 'http://www.Department2.University0.edu/GraduateCourse34')).
add('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent225', 'http://www.Department0.University0.edu/AssociateProfessor11')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent37', 'http://www.Department1.University0.edu/Course51')).
add('a1:emailAddress'('http://www.Department2.University0.edu/AssociateProfessor2', '"AssociateProfessor2@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent76', 'http://www.Department1.University0.edu/Course38')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent54', '"GraduateStudent54@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent17', 'http://www.Department1.University0.edu/GraduateCourse46')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent252', '"UndergraduateStudent252@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent412', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent84', 'http://www.Department0.University0.edu/GraduateCourse26')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent223', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent242', '"UndergraduateStudent242@Department1.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent8', '"UndergraduateStudent8@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent374', 'http://www.Department1.University0.edu/Course40')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent159', '"UndergraduateStudent159@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication5', 'http://www.Department0.University0.edu/AssociateProfessor7')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent424', 'http://www.Department2.University0.edu/Course21')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/AssistantProfessor0')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent80', '"UndergraduateStudent80@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent53', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent217', 'http://www.Department2.University0.edu/Course31')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent204', '"UndergraduateStudent204@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent21', 'http://www.Department0.University0.edu/Course33')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent167', '"UndergraduateStudent167@Department0.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent197', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication2', 'http://www.Department1.University0.edu/GraduateStudent64')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor12/Publication1', 'http://www.Department2.University0.edu/AssociateProfessor12')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent319', 'http://www.Department2.University0.edu/Course8')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent300', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent158', 'http://www.Department0.University0.edu/Course14')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent344', 'http://www.Department2.University0.edu/Course23')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent173', '"UndergraduateStudent173@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent247', 'http://www.Department0.University0.edu/Course42')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication6', 'http://www.Department2.University0.edu/GraduateStudent101')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent226', 'http://www.Department0.University0.edu/Course1')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent85', '"UndergraduateStudent85@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent98', 'http://www.Department1.University0.edu/Course22')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent56', 'http://www.Department1.University0.edu/Course22')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication8', 'http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent358', 'http://www.Department2.University0.edu/Course3')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent79', 'http://www.Department2.University0.edu/Course43')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent293', 'http://www.Department0.University0.edu/Course25')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication11', 'http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent128', 'http://www.Department2.University0.edu/Course6')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication4', 'http://www.Department1.University0.edu/AssociateProfessor5')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent370', 'http://www.Department1.University0.edu/AssistantProfessor6')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent222', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent27', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent149', 'http://www.Department2.University0.edu/Course32')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent230', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent12', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent259', 'http://www.Department0.University0.edu/AssociateProfessor9')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication0', 'http://www.Department2.University0.edu/AssistantProfessor8')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor6/Publication3', 'http://www.Department2.University0.edu/GraduateStudent21')).
delete('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/FullProfessor7', 'http://www.University459.edu')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent46', 'http://www.Department1.University0.edu/AssociateProfessor10')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication8', 'http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:doctoralDegreeFrom'('http://www.Department0.University0.edu/FullProfessor5', 'http://www.University926.edu')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent152', '"xxx-xxx-xxxx"^^xsd:string')).
