add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication5', 'http://www.Department2.University0.edu/GraduateStudent14')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent33', 'http://www.Department2.University0.edu/Course6')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor2/Publication3', 'http://www.Department0.University0.edu/FullProfessor2')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent261', 'http://www.Department0.University0.edu/Course19')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication17', 'http://www.Department0.University0.edu/GraduateStudent95')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent59', 'http://www.Department2.University0.edu/Course16')).
add('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent79', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent191', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent79', 'http://www.Department1.University0.edu/GraduateCourse3')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent89', '"UndergraduateStudent89@Department0.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent365', '"UndergraduateStudent365@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent246', 'http://www.Department2.University0.edu/Course31')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent379', '"UndergraduateStudent379@Department2.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent127', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/FullProfessor0', 'http://www.University496.edu')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor1/Publication12', 'http://www.Department2.University0.edu/FullProfessor1')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent30', '"UndergraduateStudent30@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor7/Publication1', 'http://www.Department1.University0.edu/FullProfessor7')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor1/Publication1', 'http://www.Department2.University0.edu/AssistantProfessor1')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent223', '"UndergraduateStudent223@Department2.University0.edu"^^xsd:string')).
