add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent24', 'http://www.Department0.University0.edu/FullProfessor1')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent262', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent137', 'http://www.Department0.University0.edu/Course27')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor6/Publication11', 'http://www.Department2.University0.edu/FullProfessor6')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent279', 'http://www.Department2.University0.edu/Course47')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent111', 'http://www.Department2.University0.edu/Course0')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor0/Publication2', 'http://www.Department0.University0.edu/AssistantProfessor0')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent182', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent9', 'http://www.Department1.University0.edu/Course12')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent373', '"UndergraduateStudent373@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent169', 'http://www.Department1.University0.edu/Course33')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent46', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent350', '"UndergraduateStudent350@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent254', 'http://www.Department2.University0.edu/Course15')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor9/Publication8', 'http://www.Department0.University0.edu/AssociateProfessor9')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent265', 'http://www.Department2.University0.edu/Course20')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent261', 'http://www.Department0.University0.edu/Course19')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent304', 'http://www.Department1.University0.edu/Course32')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent115', 'http://www.Department1.University0.edu/Course19')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/FullProfessor1', '"FullProfessor1@Department0.University0.edu"^^xsd:string')).
