add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent46', 'http://www.Department2.University0.edu/Course10')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent137', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent4', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor10/Publication10', 'http://www.Department2.University0.edu/GraduateStudent42')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent51', 'http://www.Department1.University0.edu/Course21')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent62', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/Lecturer2', '"Lecturer2@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor0/Publication1', 'http://www.Department2.University0.edu/AssociateProfessor0')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent209', 'http://www.Department2.University0.edu/Course23')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent59', 'http://www.Department2.University0.edu/Course18')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent103', 'http://www.University47.edu')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor6/Publication9', 'http://www.Department1.University0.edu/GraduateStudent73')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent233', 'http://www.Department0.University0.edu/Course19')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent111', 'http://www.Department2.University0.edu/Course0')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent44', 'http://www.University717.edu')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor7/Publication12', 'http://www.Department1.University0.edu/GraduateStudent66')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication8', 'http://www.Department1.University0.edu/GraduateStudent5')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent182', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent79', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent9', 'http://www.Department1.University0.edu/Course12')).
