add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent379', 'http://www.Department1.University0.edu/Course2')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent151', 'http://www.Department0.University0.edu/Course47')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent54', 'http://www.Department2.University0.edu/GraduateCourse13')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor11/Publication14', 'http://www.Department1.University0.edu/AssociateProfessor11')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent276', 'http://www.Department2.University0.edu/Course43')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent402', 'http://www.Department2.University0.edu/Course34')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent8', 'http://www.Department0.University0.edu/FullProfessor7')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent51', '"GraduateStudent51@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor4/Publication9', 'http://www.Department2.University0.edu/GraduateStudent107')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication0', 'http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor0/Publication10', 'http://www.Department1.University0.edu/GraduateStudent41')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent267', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent306', 'http://www.Department0.University0.edu/Course16')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent51', 'http://www.Department1.University0.edu/Course21')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent71', '"GraduateStudent71@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/Lecturer2', '"Lecturer2@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor7/Publication1', 'http://www.Department1.University0.edu/GraduateStudent20')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent218', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent186', 'http://www.Department1.University0.edu/AssociateProfessor1')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent239', 'http://www.Department2.University0.edu/Course45')).
