add('skos:broader'('a26:Category:Buildings_and_structures_in_Teton_County_Wyoming', 'a26:Category:Buildings_and_structures_in_Wyoming_by_county')).
add('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:American_sportspeople')).
add('skos:broader'('a26:Category:Long-distance_footpaths_in_Wales', 'a26:Category:Footpaths_in_Wales')).
add('skos:broader'('a26:Category:Monument_types', 'a26:Category:Archaeology_of_structures')).
add('skos:broader'('a26:Category:Monument_types', 'a26:Category:Monuments_and_memorials')).
add('skos:broader'('a26:Category:People_from_Madrid', 'a26:Category:Madrid')).
add('skos:broader'('a26:Category:Aguadilla_Isabela_San_Sebastián_metropolitan_area', 'a26:Category:Metropolitan_areas_of_Puerto_Rico')).
add('skos:broader'('a26:Category:Literary_motifs', 'a26:Category:Fiction_by_topic')).
add('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Topology')).
add('skos:broader'('a26:Category:Exoplanet_catalogues', 'a26:Category:Exoplanetology')).
add('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_in_Ontario')).
add('skos:broader'('a26:Category:Turkish_Football_Federation_presidents', 'a26:Category:Turkish_Football_Federation')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Cinema_of_Brazil')).
add('skos:broader'('a26:Category:2nd_millennium_in_South_Carolina', 'a26:Category:2nd_millennium_in_the_United_States')).
add('skos:broader'('a26:Category:African_culture_by_nationality', 'a26:Category:African_culture')).
add('skos:broader'('a26:Category:Blackened_death_metal_musical_groups', 'a26:Category:Blackened_death_metal')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Analysis')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Films_by_country')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:Water_polo_competitions_in_France')).
add('skos:broader'('a26:Category:The_Independent_people', 'a26:Category:The_Independent')).
add('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Sport_shooters_by_nationality')).
add('skos:broader'('a26:Category:Organizations_based_in_the_United_States_by_state', 'a26:Category:Organizations_based_in_the_United_States')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_sports_competitions_hosted_by_France')).
add('skos:broader'('a26:Category:Graphemes', 'a26:Category:Writing_systems')).
add('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
delete('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
delete('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Populated_places_in_California_by_county')).
delete('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1280s_in_England')).
delete('skos:broader'('a26:Category:Former_country_articles_requiring_restructuring', 'a26:Category:WikiProject_Former_countries')).
delete('skos:broader'('a26:Category:Conspiracy_theories', 'a26:Category:Fringe_theory')).
delete('skos:broader'('a26:Category:Mythological_sword_fighters', 'a26:Category:Mythological_characters')).
delete('skos:broader'('a26:Category:Geography_of_the_Northern_Territory', 'a26:Category:Geography_of_Australia_by_state_or_territory')).
delete('skos:broader'('a26:Category:Bender_Moldova', 'a26:Category:Districts_of_Moldova')).
delete('skos:broader'('a26:Category:Housing_in_Scotland', 'a26:Category:Scottish_architecture')).
delete('skos:broader'('a26:Category:North_American_culture_by_country', 'a26:Category:North_American_culture')).
delete('skos:broader'('a26:Category:Neighbourhoods_of_Helsinki', 'a26:Category:Geography_of_Helsinki')).
delete('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Non-metropolitan_districts_of_Somerset')).
delete('skos:broader'('a26:Category:Third_Doctor_stories', 'a26:Category:Doctor_Who_stories')).
delete('skos:broader'('a26:Category:A-Class_Museums_articles', 'a26:Category:A-Class_articles')).
delete('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Buildings_and_structures_in_Midlothian')).
delete('skos:broader'('a26:Category:Soap_opera_actors_by_nationality', 'a26:Category:Categories_by_nationality')).
delete('skos:broader'('a26:Category:Fashion_events_in_the_United_Kingdom', 'a26:Category:British_fashion')).
delete('skos:broader'('a26:Category:Census-designated_places_in_Tennessee', 'a26:Category:Populated_places_in_Tennessee')).
delete('skos:broader'('a26:Category:Bielsk_County', 'a26:Category:Land_counties_of_Podlaskie_Voivodeship')).
delete('skos:broader'('a26:Category:Explosions_in_England', 'a26:Category:Disasters_in_England')).
delete('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Peruvian_sportspeople')).
delete('skos:broader'('a26:Category:Association_football_international_competitions_squad_navigational_boxes', 'a26:Category:Association_football_international_competitions_navigational_boxes')).
delete('skos:broader'('a26:Category:Treaties_of_the_Grand_Duchy_of_Hesse', 'a26:Category:Treaties_of_Germany')).
delete('skos:broader'('a26:Category:Companies_based_in_Atlanta_Georgia', 'a26:Category:Companies_based_in_Georgia_U.S._state_by_city')).
delete('skos:broader'('a26:Category:Redirects_with_possibilities', 'a26:Category:Redirects_from_subtopics')).
