add('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Visitor_attractions_in_Midlothian')).
add('skos:broader'('a26:Category:Professional_Indoor_Football_League_teams', 'a26:Category:Indoor_American_football_teams_in_the_United_States_by_league')).
add('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:English_businesspeople_by_city')).
add('skos:broader'('a26:Category:Rulers_of_Baden', 'a26:Category:German_monarchs')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Films_by_country')).
add('skos:broader'('a26:Category:Literary_motifs', 'a26:Category:Fiction_by_topic')).
add('skos:broader'('a26:Category:Conglomerate_companies_of_France', 'a26:Category:Conglomerate_companies_by_country')).
add('skos:broader'('a26:Category:Five-year_plans', 'a26:Category:Economic_planning')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_Brazil_by_state')).
add('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Non-metropolitan_districts_of_Somerset')).
add('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Woodwind_musicians')).
add('skos:broader'('a26:Category:Treaties_of_the_Grand_Duchy_of_Hesse', 'a26:Category:Treaties_of_Germany')).
add('skos:broader'('a26:Category:A-Class_Museums_articles', 'a26:Category:A-Class_articles')).
add('skos:broader'('a26:Category:Steampunk_films', 'a26:Category:Science_fiction_films_by_genre')).
add('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Romani_in_Italy')).
delete('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
delete('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_American_people')).
delete('skos:broader'('a26:Category:Fashion_events_in_the_United_Kingdom', 'a26:Category:British_fashion')).
delete('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publisher')).
delete('skos:broader'('a26:Category:Graphemes', 'a26:Category:Units_of_morphological_analysis')).
delete('skos:broader'('a26:Category:Member_states_of_the_United_Nations', 'a26:Category:History_of_the_United_Nations')).
delete('skos:broader'('a26:Category:MCG_objects', 'a26:Category:MCG_objects')).
delete('skos:broader'('a26:Category:Woody_Guthrie', 'a26:Category:Guthrie_family')).
delete('skos:broader'('a26:Category:People_from_Madrid', 'a26:Category:Madrid')).
delete('skos:broader'('a26:Category:Populated_places_in_Galikash_County', 'a26:Category:Populated_places_in_Golestan_Province')).
delete('skos:broader'('a26:Category:Pirate_Party_Germany', 'a26:Category:Liberal_parties_in_Germany')).
delete('skos:broader'('a26:Category:Landforms_of_Petersburg_Borough_Alaska', 'a26:Category:Geography_of_Petersburg_Borough_Alaska')).
delete('skos:broader'('a26:Category:DC_Comics-related_lists', 'a26:Category:Comic_lists_by_franchise')).
delete('skos:broader'('a26:Category:Redirects_with_possibilities', 'a26:Category:Redirects_from_subtopics')).
delete('skos:broader'('a26:Category:Advanced_Micro_Devices', 'a26:Category:Manufacturing_companies_of_the_United_States')).
