add('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Ptolemaic_colonies')).
add('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Geography_of_Los_Angeles_County_California')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_Brazil_by_state')).
add('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publishing_company_of_the_United_States')).
add('skos:broader'('a26:Category:Austrian_Football_Bundesliga_players', 'a26:Category:Austrian_Football_Bundesliga')).
add('skos:broader'('a26:Category:Transport_in_Greater_Moncton', 'a26:Category:Transport_in_New_Brunswick_by_city')).
add('skos:broader'('a26:Category:Carleton_University', 'a26:Category:Universities_in_Ontario')).
add('skos:broader'('a26:Category:Bielsk_County', 'a26:Category:Land_counties_of_Podlaskie_Voivodeship')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Geography_of_Rio_Grande_do_Sul')).
add('skos:broader'('a26:Category:MCG_objects', 'a26:Category:Astronomical_catalogues')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:1977_in_British_Columbia')).
delete('skos:broader'('a26:Category:Documentary_films_about_homelessness_in_the_United_States', 'a26:Category:Documentary_films_about_poverty_in_the_United_States')).
delete('skos:broader'('a26:Category:Literary_motifs', 'a26:Category:Fiction_by_topic')).
delete('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:19th_century_in_England')).
delete('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Irish_Sea')).
delete('skos:broader'('a26:Category:British_adventure_films', 'a26:Category:British_films_by_genre')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Heads_of_state_in_the_Middle_East')).
delete('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
delete('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
delete('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:Centuries_in_Staffordshire')).
