add('skos:broader'('a26:Category:Populated_places_in_Morgan_County_Tennessee', 'a26:Category:Geography_of_Morgan_County_Tennessee')).
add('skos:broader'('a26:Category:Sociological_terminology', 'a26:Category:Sociology')).
add('skos:broader'('a26:Category:Ontario_sportspeople', 'a26:Category:Canadian_sportspeople_by_province_or_territory')).
add('skos:broader'('a26:Category:People_from_West_Sussex', 'a26:Category:People_from_South_East_England')).
add('skos:broader'('a26:Category:Government_of_Stockholm', 'a26:Category:Government_of_Sweden')).
add('skos:broader'('a26:Category:Oceanography', 'a26:Category:Physical_geography')).
add('skos:broader'('a26:Category:Dams_completed_in_1999', 'a26:Category:Dams_by_year_of_completion')).
add('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Mammal_breeds')).
add('skos:broader'('a26:Category:Populated_places_in_Al_Wahat_District', 'a26:Category:Populated_places_in_Libya')).
add('skos:broader'('a26:Category:History_of_New_England', 'a26:Category:History_of_the_Northeastern_United_States')).
delete('skos:broader'('a26:Category:Air-to-ground_rockets', 'a26:Category:Rocket_weapons')).
delete('skos:broader'('a26:Category:Foreign_relations_of_Burundi', 'a26:Category:Foreign_relations_by_country')).
delete('skos:broader'('a26:Category:Commemorative_coins', 'a26:Category:Coins')).
delete('skos:broader'('a26:Category:European_archaeology', 'a26:Category:Archaeology_by_continent')).
delete('skos:broader'('a26:Category:Politology', 'a26:Category:Political_science')).
delete('skos:broader'('a26:Category:Provinces_of_South_Korea', 'a26:Category:Provinces_of_Korea')).
delete('skos:broader'('a26:Category:Commemorative_coins', 'a26:Category:Exonumia')).
delete('skos:broader'('a26:Category:1860s_in_South_Africa', 'a26:Category:19th_century_in_South_Africa')).
delete('skos:broader'('a26:Category:British_tubists', 'a26:Category:Tubists_by_nationality')).
delete('skos:broader'('a26:Category:U.S._Highways_in_Wisconsin', 'a26:Category:State_highways_in_Wisconsin')).
