add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent352', 'http://www.Department1.University0.edu/Course47')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent183', 'http://www.Department2.University0.edu/Course10')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent56', 'http://www.Department1.University0.edu/Course19')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent124', 'http://www.Department2.University0.edu/Course16')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent102', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent43', 'http://www.Department2.University0.edu/Course46')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent395', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent39', '"GraduateStudent39@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent166', 'http://www.Department0.University0.edu/Course43')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent387', 'http://www.Department1.University0.edu/Course35')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication4', 'http://www.Department0.University0.edu/GraduateStudent77')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent90', 'http://www.Department1.University0.edu/GraduateCourse4')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent260', 'http://www.Department2.University0.edu/Course18')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication0', 'http://www.Department0.University0.edu/FullProfessor4')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent420', 'http://www.Department2.University0.edu/Course29')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent0', 'http://www.Department0.University0.edu/FullProfessor2')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent118', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent183', 'http://www.Department0.University0.edu/Course25')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent197', 'http://www.Department2.University0.edu/Course7')).
add('a1:telephone'('http://www.Department1.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication6', 'http://www.Department2.University0.edu/GraduateStudent71')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor1/Publication13', 'http://www.Department0.University0.edu/FullProfessor1')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent52', '"GraduateStudent52@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication15', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor1/Publication6', 'http://www.Department0.University0.edu/GraduateStudent98')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent28', 'http://www.Department1.University0.edu/Course8')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent125', 'http://www.Department2.University0.edu/Course17')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent53', 'http://www.Department1.University0.edu/AssistantProfessor3')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication7', 'http://www.Department1.University0.edu/FullProfessor8')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent34', '"GraduateStudent34@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent13', 'http://www.Department2.University0.edu/Course37')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent96', '"GraduateStudent96@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor1/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor1')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent24', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent339', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent195', 'http://www.Department2.University0.edu/Course3')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent249', 'http://www.Department1.University0.edu/AssociateProfessor7')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent372', '"UndergraduateStudent372@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent85', 'http://www.Department0.University0.edu/Course41')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent118', 'http://www.Department2.University0.edu/Course2')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent89', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent27', 'http://www.Department2.University0.edu/Course3')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent125', 'http://www.Department0.University0.edu/Course34')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication8', 'http://www.Department2.University0.edu/GraduateStudent14')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent64', 'http://www.Department0.University0.edu/GraduateCourse32')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent193', 'http://www.Department1.University0.edu/Course32')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent172', 'http://www.Department2.University0.edu/Course2')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication4', 'http://www.Department0.University0.edu/AssociateProfessor12')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent410', 'http://www.Department2.University0.edu/Course16')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent279', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent325', 'http://www.Department0.University0.edu/AssistantProfessor6')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent257', 'http://www.Department2.University0.edu/Course18')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent321', 'http://www.Department1.University0.edu/Course7')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse41')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent280', 'http://www.Department0.University0.edu/Course34')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent172', 'http://www.Department0.University0.edu/Course3')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication1', 'http://www.Department0.University0.edu/GraduateStudent107')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent283', 'http://www.Department2.University0.edu/Course0')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor2', 'http://www.Department2.University0.edu/Course33')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent127', 'http://www.Department2.University0.edu/Course13')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent88', 'http://www.University398.edu')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor7', 'http://www.Department0.University0.edu/GraduateCourse24')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent362', 'http://www.Department2.University0.edu/Course10')).
delete('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent53', 'http://www.Department0.University0.edu/Course27')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent191', 'http://www.Department2.University0.edu/Course45')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent207', 'http://www.Department0.University0.edu/Course32')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent415', '"UndergraduateStudent415@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent244', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent25', 'http://www.Department1.University0.edu/GraduateCourse10')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent213', '"UndergraduateStudent213@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent114', 'http://www.Department1.University0.edu/Course28')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent78', 'http://www.Department2.University0.edu/Course46')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent213', 'http://www.Department0.University0.edu/Course17')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent128', 'http://www.Department1.University0.edu/Course11')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent147', 'http://www.Department0.University0.edu/AssistantProfessor7')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication12', 'http://www.Department2.University0.edu/GraduateStudent55')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication17', 'http://www.Department0.University0.edu/GraduateStudent95')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent92', 'http://www.Department0.University0.edu/AssistantProfessor1')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse20')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent305', 'http://www.Department2.University0.edu/Course40')).
delete('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent425', 'http://www.Department2.University0.edu/AssistantProfessor0')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent404', '"UndergraduateStudent404@Department2.University0.edu"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent4', 'http://www.University220.edu')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent199', '"UndergraduateStudent199@Department0.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent140', 'http://www.Department1.University0.edu/FullProfessor4')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent161', '"UndergraduateStudent161@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent28', '"GraduateStudent28@Department2.University0.edu"^^xsd:string')).
delete('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/Lecturer4', 'http://www.University421.edu')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent4', '"GraduateStudent4@Department2.University0.edu"^^xsd:string')).
