add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent271', 'http://www.Department1.University0.edu/Course38')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor4/Publication0', 'http://www.Department2.University0.edu/GraduateStudent65')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor0/Publication12', 'http://www.Department0.University0.edu/AssociateProfessor0')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent360', 'http://www.Department2.University0.edu/Course16')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor4/Publication6', 'http://www.Department2.University0.edu/GraduateStudent65')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent242', 'http://www.Department0.University0.edu/Course21')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent431', 'http://www.Department1.University0.edu/Course20')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent261', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent224', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent313', 'http://www.Department0.University0.edu/Course37')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent75', 'http://www.Department0.University0.edu/GraduateCourse8')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent167', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent280', '"UndergraduateStudent280@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor0/Publication8', 'http://www.Department0.University0.edu/AssociateProfessor0')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent55', 'http://www.Department2.University0.edu/Course7')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent288', 'http://www.Department1.University0.edu/Course7')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent166', 'http://www.Department0.University0.edu/Course43')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor6/Publication6', 'http://www.Department0.University0.edu/AssociateProfessor6')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent90', '"UndergraduateStudent90@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication10', 'http://www.Department0.University0.edu/AssociateProfessor7')).
