add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent145', 'http://www.Department1.University0.edu/Course28')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent317', '"UndergraduateStudent317@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/AssistantProfessor3', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent254', '"UndergraduateStudent254@Department1.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent33', '"GraduateStudent33@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent55', 'http://www.Department2.University0.edu/Course7')).
add('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor5', 'http://www.Department0.University0.edu/Course18')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent137', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssistantProfessor7', 'http://www.University960.edu')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent139', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent377', '"UndergraduateStudent377@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor0/Publication14', 'http://www.Department0.University0.edu/GraduateStudent63')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent34', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent111', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent115', '"UndergraduateStudent115@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent253', '"UndergraduateStudent253@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent431', 'http://www.Department1.University0.edu/Course20')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent340', 'http://www.Department1.University0.edu/Course33')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent7', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent432', '"xxx-xxx-xxxx"^^xsd:string')).
