add('skos:broader'('a26:Category:Muslim_conquests', 'a26:Category:Medieval_Islam')).
add('skos:broader'('a26:Category:Arteries_of_the_head_and_neck', 'a26:Category:Arteries')).
add('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
add('skos:broader'('a26:Category:People_from_Musselburgh', 'a26:Category:People_by_city_or_town_in_Scotland')).
add('skos:broader'('a26:Category:American_romance_novels', 'a26:Category:American_novels_by_genre')).
add('skos:broader'('a26:Category:Post_towns_in_the_LL_postcode_area', 'a26:Category:Post_towns_in_postcode_areas_covering_Wales')).
add('skos:broader'('a26:Category:British_folk_rock_groups', 'a26:Category:British_rock_music_groups_by_style')).
add('skos:broader'('a26:Category:History_of_Great_Britain', 'a26:Category:18th_century_by_country')).
add('skos:broader'('a26:Category:Wallidan_FC_players', 'a26:Category:Footballers_in_the_Gambia_by_club')).
add('skos:broader'('a26:Category:Category_A_prisons_in_England', 'a26:Category:Prisons_in_England_by_category')).
add('skos:broader'('a26:Category:1997_98_in_OFC_football', 'a26:Category:1997_in_association_football')).
add('skos:broader'('a26:Category:Eastern_United_States', 'a26:Category:Regions_of_the_United_States')).
add('skos:broader'('a26:Category:Ballets_by_composer', 'a26:Category:Ballets')).
add('skos:broader'('a26:Category:Ajax_programming', 'a26:Category:JavaScript')).
add('skos:broader'('a26:Category:Texas_AandM_University_people', 'a26:Category:Texas_AandM_University')).
add('skos:broader'('a26:Category:Rivers_of_County_Longford', 'a26:Category:Rivers_of_the_Republic_of_Ireland')).
add('skos:broader'('a26:Category:Defunct_NAIA_conferences', 'a26:Category:Defunct_college_sports_conferences_in_the_United_States')).
add('skos:broader'('a26:Category:Concept_automobiles', 'a26:Category:Car_classifications')).
add('skos:broader'('a26:Category:Wrestlers_at_the_2004_Summer_Olympics', 'a26:Category:Competitors_at_the_2004_Summer_Olympics')).
add('skos:broader'('a26:Category:Romanian_Christian_monks', 'a26:Category:Romanian_men_by_occupation')).
add('skos:broader'('a26:Category:Digital_radio_in_Australia', 'a26:Category:Australian_radio')).
add('skos:broader'('a26:Category:Regions_of_Tennessee', 'a26:Category:Regions_of_the_Southern_United_States_by_state')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Heads_of_state_in_the_Middle_East')).
add('skos:broader'('a26:Category:Commemorative_coins', 'a26:Category:Coins')).
add('skos:broader'('a26:Category:Cubist_artists', 'a26:Category:Artists_by_genre')).
add('skos:broader'('a26:Category:Consorts_of_Montpellier', 'a26:Category:Majorcan_queens_consort')).
add('skos:broader'('a26:Category:European-American_culture', 'a26:Category:European_American')).
add('skos:broader'('a26:Category:American_Western_genre_films', 'a26:Category:Western_genre_films_by_country')).
add('skos:broader'('a26:Category:Companies_listed_on_the_Bolsa_Mexicana_de_Valores', 'a26:Category:Companies_by_stock_exchange')).
add('skos:broader'('a26:Category:Lists_of_vice_presidents', 'a26:Category:Vice_presidents')).
add('skos:broader'('a26:Category:Ahi_political_party_politicians', 'a26:Category:Israeli_politicians_by_party')).
add('skos:broader'('a26:Category:Click_consonants', 'a26:Category:Consonants')).
add('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:Racquetball_players_by_nationality')).
add('skos:broader'('a26:Category:Towns_in_Vermont', 'a26:Category:Towns_in_the_United_States_by_state')).
add('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
add('skos:broader'('a26:Category:Programming_tools_for_Windows', 'a26:Category:Computer_programming_tools')).
add('skos:broader'('a26:Category:Marxist_books', 'a26:Category:Books_by_ideology')).
add('skos:broader'('a26:Category:2004_05_in_American_ice_hockey', 'a26:Category:2005_in_ice_hockey')).
add('skos:broader'('a26:Category:Houses_on_the_National_Register_of_Historic_Places_in_Cambridge_Massachusetts', 'a26:Category:Houses_on_the_National_Register_of_Historic_Places_in_Middlesex_County_Massachusetts')).
add('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Romani_in_Italy')).
delete('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_American_people')).
delete('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:19th_century_in_England')).
delete('skos:broader'('a26:Category:Abbots', 'a26:Category:Christian_monks')).
delete('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Archaeological_sites_in_Egypt')).
delete('skos:broader'('a26:Category:Table_tennis_in_North_America', 'a26:Category:Sport_in_North_America_by_sport')).
delete('skos:broader'('a26:Category:Long-distance_footpaths_in_Wales', 'a26:Category:Footpaths_in_Wales')).
delete('skos:broader'('a26:Category:Hwiccan_monarchs', 'a26:Category:Anglo-Saxon_monarchs')).
delete('skos:broader'('a26:Category:Abbots', 'a26:Category:Members_of_Christian_religious_orders')).
delete('skos:broader'('a26:Category:People_from_Lausanne', 'a26:Category:Lausanne')).
delete('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Mammal_breeds')).
delete('skos:broader'('a26:Category:Endemic_flora_of_Yemen', 'a26:Category:Endemic_flora_by_country')).
delete('skos:broader'('a26:Category:MCG_objects', 'a26:Category:Astronomical_catalogues')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:1977_in_British_Columbia')).
delete('skos:broader'('a26:Category:People_from_Bourgoin-Jallieu', 'a26:Category:People_by_city_in_Rhône-Alpes')).
delete('skos:broader'('a26:Category:Radio_stations_established_in_1999', 'a26:Category:1999_in_radio')).
delete('skos:broader'('a26:Category:Washtenaw_County_Michigan', 'a26:Category:Metro_Detroit')).
delete('skos:broader'('a26:Category:Football_League_Two', 'a26:Category:The_Football_League')).
delete('skos:broader'('a26:Category:19th_century_in_Yorkshire', 'a26:Category:Centuries_in_Yorkshire')).
delete('skos:broader'('a26:Category:Education_in_Newfoundland_and_Labrador', 'a26:Category:Newfoundland_and_Labrador')).
delete('skos:broader'('a26:Category:Canadian_Forces_Naval_Reserve', 'a26:Category:Royal_Canadian_Navy')).
delete('skos:broader'('a26:Category:Populated_places_in_Chiang_Mai_Province', 'a26:Category:Populated_places_in_Thailand')).
delete('skos:broader'('a26:Category:Census-designated_places_in_Tennessee', 'a26:Category:Populated_places_in_Tennessee')).
delete('skos:broader'('a26:Category:People_from_Kings_Lynn_and_West_Norfolk_district', 'a26:Category:People_from_Norfolk')).
delete('skos:broader'('a26:Category:Olympic_cross-country_skiing_venues', 'a26:Category:Cross-country_skiing_at_the_Winter_Olympics')).
delete('skos:broader'('a26:Category:Odissi_dancers', 'a26:Category:Indian_classical_dancers')).
delete('skos:broader'('a26:Category:Radio_stations_established_in_1997', 'a26:Category:1997_establishments')).
delete('skos:broader'('a26:Category:Yugoslavia', 'a26:Category:Former_countries_in_Europe')).
delete('skos:broader'('a26:Category:People_from_Clinton_County_Ohio', 'a26:Category:People_by_county_in_Ohio')).
delete('skos:broader'('a26:Category:Bi-monthly_magazines', 'a26:Category:Magazines_by_publication_frequency')).
delete('skos:broader'('a26:Category:Townships_in_Allegheny_County_Pennsylvania', 'a26:Category:Populated_places_in_Allegheny_County_Pennsylvania')).
delete('skos:broader'('a26:Category:14th-century_Roman_Catholic_archbishops', 'a26:Category:Roman_Catholic_archbishops_by_period')).
delete('skos:broader'('a26:Category:Health_in_Canada', 'a26:Category:Health_in_North_America')).
delete('skos:broader'('a26:Category:Shooters_at_the_2012_Summer_Olympics', 'a26:Category:Competitors_at_the_2012_Summer_Olympics')).
delete('skos:broader'('a26:Category:English_first-class_cricket_teams', 'a26:Category:Cricket_teams_in_England')).
delete('skos:broader'('a26:Category:Invergordon_No._430_Saskatchewan', 'a26:Category:Rural_municipalities_in_Saskatchewan')).
delete('skos:broader'('a26:Category:Poetry_museums', 'a26:Category:Literary_museums_by_type')).
delete('skos:broader'('a26:Category:Religious_leadership_roles', 'a26:Category:Religious_occupations')).
delete('skos:broader'('a26:Category:Beverage_companies_of_Belgium', 'a26:Category:Beverage_companies_by_country')).
delete('skos:broader'('a26:Category:Westminster_system', 'a26:Category:Government_in_Canada')).
delete('skos:broader'('a26:Category:Scots_law_formal_titles', 'a26:Category:Scottish_titles')).
