add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent51')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent48')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent257')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent156')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent64')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent207')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent124')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent201')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent141')).
add('a1:AssistantProfessor'('http://www.Department1.University0.edu/AssistantProfessor7')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent78')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent306')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent13')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse32')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent72')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse3')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent384')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent221')).
