add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent78')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent121')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent13')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent335')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent325')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse32')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent320')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent401')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent233')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent235')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent95')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent256')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse10')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent150')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent304')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent321')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent323')).
