add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent111')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent122')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent298')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse45')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent171')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent194')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent109')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent52')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent12')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent146')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent265')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent257')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent156')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent212')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent335')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent88')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent94')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent384')).
