add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent265')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent28')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent56')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent60')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent411')).
add('a1:AssistantProfessor'('http://www.Department1.University0.edu/AssistantProfessor5')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent324')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent274')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse19')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent275')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent121')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent13')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent308')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent118')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent13')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent192')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent181')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent381')).
