add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent143')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent13')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent403')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent58')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent31')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent64')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent142')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent124')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor2')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent233')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent48')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse3')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse10')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent0')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent150')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent312')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent323')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent221')).
