add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse18')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent56')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent388')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent79')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent304')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent303')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent382')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent170')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent232')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent253')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent92')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse44')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent46')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent7')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent234')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent62')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent233')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent125')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent330')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent22')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent357')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent129')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent69')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent117')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent313')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent395')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent162')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent107')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent413')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent129')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse49')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent223')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent86')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent113')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent404')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent35')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent71')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent17')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent34')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent97')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent292')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent423')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent291')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent39')).
delete('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor2')).
delete('a1:Lecturer'('http://www.Department0.University0.edu/Lecturer3')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent211')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent7')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent167')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent209')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent415')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent105')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent229')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent65')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse21')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent89')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent67')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
delete('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor1')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent247')).
delete('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor0')).
delete('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor5')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent339')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent4')).
