add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent31')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent33')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent34')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent11')).
add('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer5')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent58')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent321')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent194')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent278')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent214')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent327')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent257')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent118')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse34')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent297')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent401')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent8')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse28')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent144')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent148')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent208')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent23')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent335')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse23')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent102')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent184')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent61')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent287')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent61')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse42')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent81')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent12')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent362')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent116')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent75')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent303')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent97')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent56')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent99')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent78')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent190')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent174')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent254')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor1')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent110')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent72')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent33')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse0')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent39')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent38')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent211')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent122')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent355')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent88')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent2')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent183')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent113')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent20')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse40')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent285')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent249')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse33')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent205')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent108')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent436')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent49')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent240')).
