add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent75')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent34')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent179')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent36')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent302')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent99')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent321')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent123')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent343')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent174')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent194')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent301')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent91')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent254')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse9')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent257')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse43')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent96')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent89')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent38')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent297')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent401')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent144')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent206')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent184')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent61')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent220')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent28')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent80')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent26')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse8')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent78')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent92')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent116')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent2')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent0')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent303')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent239')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent108')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent124')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent381')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent32')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor1')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent215')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent327')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent256')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent4')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent118')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent100')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent23')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse34')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent39')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent1')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent211')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent146')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent88')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent181')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent221')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent287')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent285')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent61')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse30')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse42')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent248')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent129')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent241')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent240')).
