add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent56')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent135')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent404')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent304')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent197')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent94')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent192')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent101')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent300')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent341')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent53')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent32')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse31')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent292')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent39')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent251')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent230')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent233')).
add('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent415')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent104')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent357')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent105')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse23')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent184')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent313')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent395')).
add('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor1')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent47')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent434')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse34')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent206')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent260')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent200')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent4')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent261')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent30')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent79')).
delete('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer4')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent217')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent106')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent170')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent170')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse6')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent73')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent291')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent26')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse47')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent7')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent236')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent252')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent250')).
delete('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor2')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse39')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse17')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent55')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent22')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent106')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent417')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent67')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent267')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent244')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent61')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent224')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent248')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse41')).
delete('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor0')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent282')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent413')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent286')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
