add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent210', '"UndergraduateStudent210@Department1.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent68', '"GraduateStudent68@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent66', '"UndergraduateStudent66@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent262', 'http://www.Department1.University0.edu/Course35')).
add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent199', 'http://www.Department2.University0.edu/AssociateProfessor2')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent171', 'http://www.Department0.University0.edu/Course44')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent114', 'http://www.Department1.University0.edu/Course47')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent234', 'http://www.Department1.University0.edu/Course37')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor4/Publication1', 'http://www.Department0.University0.edu/AssistantProfessor4')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent76', '"GraduateStudent76@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor0/Publication1', 'http://www.Department0.University0.edu/GraduateStudent11')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication4', 'http://www.Department1.University0.edu/GraduateStudent55')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent40', '"UndergraduateStudent40@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent152', 'http://www.Department0.University0.edu/Course33')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication14', 'http://www.Department0.University0.edu/GraduateStudent39')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent70', 'http://www.Department2.University0.edu/GraduateCourse34')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent81', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent56', 'http://www.Department2.University0.edu/Course19')).
delete('a1:mastersDegreeFrom'('http://www.Department1.University0.edu/AssociateProfessor8', 'http://www.University51.edu')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication5', 'http://www.Department0.University0.edu/GraduateStudent107')).
