add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent244', 'http://www.Department2.University0.edu/AssistantProfessor1')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor3/Publication1', 'http://www.Department1.University0.edu/GraduateStudent82')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor6/Publication12', 'http://www.Department2.University0.edu/AssociateProfessor6')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent33', 'http://www.Department1.University0.edu/Course45')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent291', 'http://www.Department1.University0.edu/Course30')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent204', '"UndergraduateStudent204@Department2.University0.edu"^^xsd:string')).
add('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/FullProfessor6', 'http://www.University89.edu')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/Lecturer0', 'http://www.University767.edu')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent266', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent37', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent35', 'http://www.Department2.University0.edu/Course34')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent62', 'http://www.Department0.University0.edu/Course2')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent61', 'http://www.Department2.University0.edu/Course40')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent120', 'http://www.Department2.University0.edu/Course1')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent163', 'http://www.Department0.University0.edu/Course50')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent302', 'http://www.Department0.University0.edu/Course39')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent40', 'http://www.Department0.University0.edu/Course17')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent405', 'http://www.Department2.University0.edu/Course9')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor4/Publication13', 'http://www.Department2.University0.edu/FullProfessor4')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent31', 'http://www.Department0.University0.edu/GraduateCourse3')).
