add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor4/Publication6', 'http://www.Department2.University0.edu/FullProfessor4')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent40', 'http://www.Department2.University0.edu/GraduateCourse23')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication9', 'http://www.Department1.University0.edu/GraduateStudent53')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor10/Publication5', 'http://www.Department0.University0.edu/AssociateProfessor10')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent3', 'http://www.Department2.University0.edu/Course17')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor5', 'http://www.University292.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent140', '"UndergraduateStudent140@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor1/Publication11', 'http://www.Department1.University0.edu/FullProfessor1')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent105', 'http://www.Department1.University0.edu/GraduateCourse38')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor1/Publication16', 'http://www.Department2.University0.edu/FullProfessor1')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent250', 'http://www.Department2.University0.edu/Course9')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor0/Publication5', 'http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent90', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent21', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent4', '"UndergraduateStudent4@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent54', 'http://www.Department2.University0.edu/Course21')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor1/Publication3', 'http://www.Department2.University0.edu/AssistantProfessor1')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent178', '"UndergraduateStudent178@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent294', '"UndergraduateStudent294@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent420', 'http://www.Department2.University0.edu/Course9')).
