add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent38', 'http://www.Department2.University0.edu/GraduateCourse30')).
add('a1:teacherOf'('http://www.Department0.University0.edu/FullProfessor0', 'http://www.Department0.University0.edu/Course0')).
add('a1:telephone'('http://www.Department1.University0.edu/AssociateProfessor10', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor6/Publication19', 'http://www.Department1.University0.edu/FullProfessor6')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent35', 'http://www.Department1.University0.edu/GraduateCourse12')).
add('a1:emailAddress'('http://www.Department2.University0.edu/AssociateProfessor3', '"AssociateProfessor3@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent20', 'http://www.Department1.University0.edu/Course22')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent317', 'http://www.Department2.University0.edu/Course6')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent323', 'http://www.Department1.University0.edu/Course9')).
add('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent37', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent117', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent12', 'http://www.Department0.University0.edu/Course1')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent339', 'http://www.Department1.University0.edu/Course11')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent39', 'http://www.Department0.University0.edu/GraduateCourse28')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent368', 'http://www.Department2.University0.edu/Course12')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent166', 'http://www.Department0.University0.edu/Course41')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent170', '"UndergraduateStudent170@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor6/Publication6', 'http://www.Department2.University0.edu/GraduateStudent17')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent187', 'http://www.Department1.University0.edu/Course12')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent39', '"UndergraduateStudent39@Department1.University0.edu"^^xsd:string')).
