add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent9', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent236', 'http://www.Department0.University0.edu/Course38')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent127', 'http://www.Department2.University0.edu/Course4')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent204', 'http://www.Department0.University0.edu/Course43')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent82', 'http://www.Department1.University0.edu/GraduateCourse8')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent398', 'http://www.Department1.University0.edu/Course21')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent434', '"UndergraduateStudent434@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor6/Publication4', 'http://www.Department2.University0.edu/FullProfessor6')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent308', 'http://www.Department0.University0.edu/Course28')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent11', '"GraduateStudent11@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent40', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent155', 'http://www.Department2.University0.edu/Course2')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent139', '"UndergraduateStudent139@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent38', 'http://www.Department0.University0.edu/Course44')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent111', '"UndergraduateStudent111@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor1/Publication1', 'http://www.Department1.University0.edu/AssistantProfessor1')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent210', 'http://www.Department0.University0.edu/Course13')).
delete('a1:doctoralDegreeFrom'('http://www.Department0.University0.edu/FullProfessor5', 'http://www.University926.edu')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/AssociateProfessor11', 'http://www.Department1.University0.edu/Course30')).
delete('a1:mastersDegreeFrom'('http://www.Department2.University0.edu/FullProfessor4', 'http://www.University753.edu')).
