add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication12', 'http://www.Department0.University0.edu/GraduateStudent81')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent312', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent112', 'http://www.Department1.University0.edu/Course6')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent375', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor0/Publication3', 'http://www.Department0.University0.edu/GraduateStudent104')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent49', 'http://www.Department2.University0.edu/Course35')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent82', 'http://www.Department2.University0.edu/Course26')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent16', 'http://www.Department0.University0.edu/AssociateProfessor6')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent233', '"UndergraduateStudent233@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent232', 'http://www.Department2.University0.edu/Course2')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent11', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent137', 'http://www.Department0.University0.edu/Course47')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent239', 'http://www.Department1.University0.edu/Course8')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent222', 'http://www.Department1.University0.edu/Course40')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent48', 'http://www.Department1.University0.edu/Course29')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor9/Publication5', 'http://www.Department0.University0.edu/GraduateStudent78')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent58', 'http://www.Department1.University0.edu/GraduateCourse29')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent25', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication5', 'http://www.Department1.University0.edu/GraduateStudent28')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent60', '"GraduateStudent60@Department0.University0.edu"^^xsd:string')).
