add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent79', 'http://www.Department1.University0.edu/Course39')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent331', '"UndergraduateStudent331@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent154', 'http://www.Department0.University0.edu/Course39')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent172', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent348', 'http://www.Department1.University0.edu/Course20')).
add('a1:teacherOf'('http://www.Department0.University0.edu/FullProfessor4', 'http://www.Department0.University0.edu/GraduateCourse6')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent42', 'http://www.Department1.University0.edu/Course17')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent32', '"UndergraduateStudent32@Department0.University0.edu"^^xsd:string')).
add('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor1', 'http://www.University715.edu')).
add('a1:telephone'('http://www.Department1.University0.edu/AssociateProfessor11', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent306', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent318', '"UndergraduateStudent318@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor2/Publication12', 'http://www.Department2.University0.edu/AssociateProfessor2')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent92', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent288', 'http://www.Department2.University0.edu/Course31')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent98', 'http://www.Department2.University0.edu/GraduateCourse9')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor5', 'http://www.Department2.University0.edu/Course37')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent184', 'http://www.Department2.University0.edu/Course32')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent27', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent105', '"xxx-xxx-xxxx"^^xsd:string')).
