add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent313', 'http://www.Department1.University0.edu/Course22')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/AssociateProfessor6', 'http://www.University601.edu')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor11', 'http://www.University362.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent404', '"UndergraduateStudent404@Department1.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent115', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent54', 'http://www.Department1.University0.edu/GraduateCourse22')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent116', 'http://www.Department0.University0.edu/Course40')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent250', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent135', 'http://www.Department0.University0.edu/Course26')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent87', 'http://www.Department0.University0.edu/FullProfessor0')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent379', 'http://www.Department1.University0.edu/Course2')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent17', 'http://www.Department2.University0.edu/GraduateCourse42')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent286', 'http://www.Department1.University0.edu/Course30')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent8', 'http://www.Department1.University0.edu/GraduateCourse9')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent187', 'http://www.Department1.University0.edu/FullProfessor6')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor6/Publication6', 'http://www.Department1.University0.edu/FullProfessor6')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent32', 'http://www.Department1.University0.edu/Course37')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent288', '"UndergraduateStudent288@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor8/Publication13', 'http://www.Department2.University0.edu/GraduateStudent80')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent123', '"xxx-xxx-xxxx"^^xsd:string')).
