add('skos:broader'('a26:Category:University_of_Belgrade_Faculty_of_Philosophy_alumni', 'a26:Category:Philosophy_academics')).
add('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:20th-century_American_people')).
add('skos:broader'('a26:Category:19th_century_in_Staffordshire', 'a26:Category:19th_century_in_England')).
add('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Archaeological_sites_in_Egypt')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs_in_Asia')).
add('skos:broader'('a26:Category:Adaptations_of_works_by_Luigi_Pirandello', 'a26:Category:Adaptations_of_works_by_writer')).
add('skos:broader'('a26:Category:Documentary_films_about_homelessness_in_the_United_States', 'a26:Category:Documentary_films_about_poverty_in_the_United_States')).
add('skos:broader'('a26:Category:Cyclists_from_Western_Australia', 'a26:Category:Sportspeople_from_Western_Australia_by_sport')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_water_polo_competitions_by_host')).
add('skos:broader'('a26:Category:Five-year_plans', 'a26:Category:Economic_planning')).
add('skos:broader'('a26:Category:610_mm_gauge_railway_locomotives', 'a26:Category:2_ft_gauge_locomotives')).
add('skos:broader'('a26:Category:Businesspeople_from_London', 'a26:Category:British_businesspeople')).
add('skos:broader'('a26:Category:People_from_Perth-Andover', 'a26:Category:People_from_Victoria_County_New_Brunswick')).
add('skos:broader'('a26:Category:Fashion_events_in_the_United_Kingdom', 'a26:Category:British_fashion')).
add('skos:broader'('a26:Category:Scots_law_formal_titles', 'a26:Category:Scots_law')).
add('skos:broader'('a26:Category:Parishes_of_Valka_District', 'a26:Category:Parishes_of_Latvia')).
add('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publisher')).
add('skos:broader'('a26:Category:Blackened_death_metal_musical_groups', 'a26:Category:Blackened_death_metal')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Analysis')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Populated_places_in_the_South_Region_Brazil')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:Water_polo_competitions_in_France')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Chemistry')).
add('skos:broader'('a26:Category:Populated_places_in_Galikash_County', 'a26:Category:Populated_places_in_Golestan_Province')).
add('skos:broader'('a26:Category:Programming_language_topics', 'a26:Category:Computer_languages')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs')).
add('skos:broader'('a26:Category:Geography_of_Greene_County_New_York', 'a26:Category:Geography_of_the_Hudson_Valley')).
add('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Geography_of_Rio_Grande_do_Sul')).
add('skos:broader'('a26:Category:Association_football_international_competitions_squad_navigational_boxes', 'a26:Category:Association_football_international_competitions_navigational_boxes')).
add('skos:broader'('a26:Category:Trials_in_the_United_States', 'a26:Category:Trials_by_country')).
add('skos:broader'('a26:Category:Ministry_band_members', 'a26:Category:Ministry_band')).
add('skos:broader'('a26:Category:Steampunk_films', 'a26:Category:Science_fiction_films_by_genre')).
add('skos:broader'('a26:Category:Advanced_Micro_Devices', 'a26:Category:Manufacturing_companies_of_the_United_States')).
add('skos:broader'('a26:Category:Edmonton_Oilers_broadcasters', 'a26:Category:National_Hockey_League_broadcasters')).
add('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Clarinets')).
delete('skos:broader'('a26:Category:Iowa_Libertarians', 'a26:Category:Iowa_politicians_by_party')).
delete('skos:broader'('a26:Category:History_of_ethnic_groups_in_Romania', 'a26:Category:History_by_ethnic_group')).
delete('skos:broader'('a26:Category:Indiana_politicians_by_party', 'a26:Category:Indiana_politicians')).
delete('skos:broader'('a26:Category:French_silent_short_films', 'a26:Category:Silent_short_films')).
delete('skos:broader'('a26:Category:American_Airlines_people', 'a26:Category:American_Airlines')).
delete('skos:broader'('a26:Category:Conspiracy_theories', 'a26:Category:Fringe_theory')).
delete('skos:broader'('a26:Category:Mythological_sword_fighters', 'a26:Category:Mythological_characters')).
delete('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:American_sportspeople')).
delete('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
delete('skos:broader'('a26:Category:Woody_Guthrie', 'a26:Category:Guthrie_family')).
delete('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Mammal_breeds')).
delete('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Local_government_in_Somerset')).
delete('skos:broader'('a26:Category:Indiana_Whigs', 'a26:Category:Whig_Party_United_States_politicians')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Musicians_by_instrument')).
delete('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1285_in_Europe')).
delete('skos:broader'('a26:Category:Exoplanet_catalogues', 'a26:Category:Exoplanetology')).
delete('skos:broader'('a26:Category:A-Class_Museums_articles', 'a26:Category:A-Class_articles')).
delete('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Buildings_and_structures_in_Midlothian')).
delete('skos:broader'('a26:Category:Solar_phenomena', 'a26:Category:Stellar_phenomena')).
delete('skos:broader'('a26:Category:Northwest_Territories_territorial_electoral_districts', 'a26:Category:Canadian_provincial_and_territorial_electoral_districts')).
delete('skos:broader'('a26:Category:Castles_in_Midlothian', 'a26:Category:Visitor_attractions_in_Midlothian')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Middle_Eastern_monarchs')).
delete('skos:broader'('a26:Category:British_adventure_films', 'a26:Category:British_films_by_genre')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Heads_of_state_in_the_Middle_East')).
delete('skos:broader'('a26:Category:Nama_people', 'a26:Category:Namibian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publishing_company_of_the_United_States')).
delete('skos:broader'('a26:Category:Member_states_of_the_United_Nations', 'a26:Category:History_of_the_United_Nations')).
delete('skos:broader'('a26:Category:Universities_and_colleges_in_Alameda_County_California', 'a26:Category:Universities_and_colleges_in_California_by_county')).
delete('skos:broader'('a26:Category:The_Independent_people', 'a26:Category:The_Independent')).
delete('skos:broader'('a26:Category:Films_shot_in_Hong_Kong', 'a26:Category:Hong_Kong_culture')).
delete('skos:broader'('a26:Category:People_from_the_Las_Vegas_Valley', 'a26:Category:People_by_populated_place_in_Nevada')).
delete('skos:broader'('a26:Category:Explosions_in_England', 'a26:Category:Disasters_in_England')).
delete('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:Racquetball_players_by_nationality')).
delete('skos:broader'('a26:Category:Redirects_with_possibilities', 'a26:Category:Redirects_from_subtopics')).
delete('skos:broader'('a26:Category:Italian_Romani_people', 'a26:Category:Romani_in_Italy')).
