add('skos:broader'('a26:Category:Commanders_of_the_Order_of_Franz_Joseph', 'a26:Category:Recipients_of_the_Order_of_Franz_Joseph')).
add('skos:broader'('a26:Category:French_chess_players', 'a26:Category:Chess_in_France')).
add('skos:broader'('a26:Category:Westminster_system', 'a26:Category:Political_systems')).
add('skos:broader'('a26:Category:Irish-American_culture_in_Omaha_Nebraska', 'a26:Category:Ethnic_groups_in_Omaha_Nebraska')).
add('skos:broader'('a26:Category:World_War_II_airfields_in_Belgium', 'a26:Category:World_War_II_airfields_by_country')).
add('skos:broader'('a26:Category:Titles_of_nobility', 'a26:Category:Nobility')).
add('skos:broader'('a26:Category:People_by_county_in_the_Republic_of_Ireland', 'a26:Category:People_by_first-level_administrative_country_subdivision')).
add('skos:broader'('a26:Category:Governors_of_the_Dutch_Cape_Colony', 'a26:Category:Dutch_colonial_governors_and_administrators')).
add('skos:broader'('a26:Category:Open_content', 'a26:Category:Crowdsourcing')).
add('skos:broader'('a26:Category:People_from_Far_Hills_New_Jersey', 'a26:Category:People_by_borough_in_New_Jersey')).
delete('skos:broader'('a26:Category:Political_parties_by_year_of_disestablishment', 'a26:Category:Disestablishments_by_year')).
delete('skos:broader'('a26:Category:Male_actors_by_city_or_town_in_the_United_Kingdom', 'a26:Category:British_male_actors')).
delete('skos:broader'('a26:Category:National_symbols_of_Russia', 'a26:Category:National_symbols_by_nation')).
delete('skos:broader'('a26:Category:Education_in_Alabama_by_county', 'a26:Category:Alabama_counties')).
delete('skos:broader'('a26:Category:Treaties_extended_to_the_Crown_Colony_of_Trinidad_and_Tobago', 'a26:Category:Trinidad_and_Tobago_United_Kingdom_relations')).
delete('skos:broader'('a26:Category:Buddhist_titles', 'a26:Category:Titles')).
delete('skos:broader'('a26:Category:Glaciers_of_Valais', 'a26:Category:Geography_of_Valais')).
delete('skos:broader'('a26:Category:Advaitin_philosophers', 'a26:Category:Scholars_and_academics_by_subject')).
delete('skos:broader'('a26:Category:Ufology', 'a26:Category:Extraterrestrial_life_in_popular_culture')).
delete('skos:broader'('a26:Category:Persian-language_surnames', 'a26:Category:Iranian-language_surnames')).
