add('skos:broader'('a26:Category:Science_fiction_novels', 'a26:Category:Science_fiction_literature')).
add('skos:broader'('a26:Category:Oil_and_gas_law', 'a26:Category:Petroleum_politics')).
add('skos:broader'('a26:Category:Animals_described_in_1988', 'a26:Category:Species_described_in_1988')).
add('skos:broader'('a26:Category:Literary_motifs', 'a26:Category:Elements_of_fiction')).
add('skos:broader'('a26:Category:Landforms_of_Østfold', 'a26:Category:Landforms_of_Norway_by_county')).
add('skos:broader'('a26:Category:Ancient_astronomy', 'a26:Category:Ancient_science')).
add('skos:broader'('a26:Category:Australian_Jews', 'a26:Category:Australian_people_of_Jewish_descent')).
add('skos:broader'('a26:Category:Former_Vivendi_subsidiaries', 'a26:Category:Vivendi_subsidiaries')).
add('skos:broader'('a26:Category:Defunct_Major_League_Baseball_venues', 'a26:Category:Major_League_Baseball_venues')).
add('skos:broader'('a26:Category:Concert_halls_in_New_Zealand', 'a26:Category:Concert_halls_by_country')).
delete('skos:broader'('a26:Category:Stanford_University_Graduate_School_of_Business_faculty', 'a26:Category:Stanford_University_faculty')).
delete('skos:broader'('a26:Category:Flora_of_the_Mediterranean', 'a26:Category:Flora_of_North_Africa')).
delete('skos:broader'('a26:Category:Compilation_albums', 'a26:Category:Album_types')).
delete('skos:broader'('a26:Category:Education_in_Dalian', 'a26:Category:Dalian')).
delete('skos:broader'('a26:Category:Applied_sciences', 'a26:Category:Scientific_disciplines')).
delete('skos:broader'('a26:Category:Deobandi', 'a26:Category:Saharanpur_district')).
delete('skos:broader'('a26:Category:Dresses_worn_on_the_red_carpet_at_the_Academy_Awards_ceremonies', 'a26:Category:Individual_dresses')).
delete('skos:broader'('a26:Category:Mexican_women_in_business', 'a26:Category:Women_in_business_by_nationality')).
delete('skos:broader'('a26:Category:Pakistan_federal_departments_and_agencies', 'a26:Category:Executive_branch_of_the_Pakistani_government')).
delete('skos:broader'('a26:Category:People_from_Jiuquan', 'a26:Category:Jiuquan')).
