add('skos:broader'('a26:Category:University_of_Bergen', 'a26:Category:Education_in_Bergen')).
add('skos:broader'('a26:Category:Digital_radio_in_Australia', 'a26:Category:Australian_radio')).
add('skos:broader'('a26:Category:Moroccan_emigrants_to_Belgium', 'a26:Category:Immigrants_to_Belgium')).
add('skos:broader'('a26:Category:Fragaria', 'a26:Category:Rosoideae')).
add('skos:broader'('a26:Category:Olympic_basketball_players_of_the_Soviet_Union', 'a26:Category:Olympic_basketball_players_by_country')).
add('skos:broader'('a26:Category:South_American_people', 'a26:Category:South_America')).
add('skos:broader'('a26:Category:Irish-language_writers', 'a26:Category:Writers_by_language')).
add('skos:broader'('a26:Category:Populated_coastal_places_in_North_Yorkshire', 'a26:Category:Populated_coastal_places_in_England')).
add('skos:broader'('a26:Category:2004_05_in_American_ice_hockey', 'a26:Category:2005_in_ice_hockey')).
add('skos:broader'('a26:Category:National_Heritage_Fellowship_winners', 'a26:Category:National_Endowment_for_the_Arts')).
delete('skos:broader'('a26:Category:17th-century_Islam', 'a26:Category:17th_century_in_religion')).
delete('skos:broader'('a26:Category:International_bodies_of_Reformed_denominations', 'a26:Category:International_bodies_of_Protestant_denominations')).
delete('skos:broader'('a26:Category:Airports_in_Klamath_County_Oregon', 'a26:Category:Airports_in_Oregon')).
delete('skos:broader'('a26:Category:Jewish_American_artists', 'a26:Category:American_Jews_by_occupation')).
delete('skos:broader'('a26:Category:13th-century_Byzantine_people', 'a26:Category:13th-century_Christians')).
delete('skos:broader'('a26:Category:Municipalities_of_Batangas', 'a26:Category:Populated_places_in_Batangas')).
delete('skos:broader'('a26:Category:19th-century_American_people', 'a26:Category:19th-century_people_by_nationality')).
delete('skos:broader'('a26:Category:Faroese_masculine_given_names', 'a26:Category:Scandinavian_masculine_given_names')).
delete('skos:broader'('a26:Category:Kings_of_Jaffna', 'a26:Category:Tamil_monarchs')).
delete('skos:broader'('a26:Category:1990_debut_albums', 'a26:Category:1990_albums')).
