add('skos:broader'('a26:Category:Tropical_cyclones', 'a26:Category:Types_of_cyclone')).
add('skos:broader'('a26:Category:Visitor_attractions_by_country', 'a26:Category:Visitor_attractions')).
add('skos:broader'('a26:Category:Lothian', 'a26:Category:Former_subdivisions_of_Scotland')).
add('skos:broader'('a26:Category:Palauan_women', 'a26:Category:Women_by_nationality')).
add('skos:broader'('a26:Category:Populated_places_in_Šumadija_District', 'a26:Category:Populated_places_in_Šumadija_and_Western_Serbia')).
add('skos:broader'('a26:Category:Animals_described_in_1819', 'a26:Category:Animals_described_in_the_19th_century')).
add('skos:broader'('a26:Category:FIBA_Africa_Championship', 'a26:Category:Basketball_competitions_between_national_teams')).
add('skos:broader'('a26:Category:Golden_Age_supervillains', 'a26:Category:Supervillains')).
add('skos:broader'('a26:Category:NYIT_Bears_baseball', 'a26:Category:NCAA_Division_I_baseball_independents')).
add('skos:broader'('a26:Category:Austro-Hungarian_World_War_I_pilots', 'a26:Category:Austro-Hungarian_aviators')).
delete('skos:broader'('a26:Category:French_chess_players', 'a26:Category:Chess_in_France')).
delete('skos:broader'('a26:Category:Visitor_attractions_in_Salzburg', 'a26:Category:Visitor_attractions_in_Austria_by_city')).
delete('skos:broader'('a26:Category:Sportspeople_from_Chicago_Illinois', 'a26:Category:Sportspeople_from_Cook_County_Illinois')).
delete('skos:broader'('a26:Category:Olympic_basketball_players_of_the_Soviet_Union', 'a26:Category:Olympic_basketball_players_by_country')).
delete('skos:broader'('a26:Category:Districts_of_Kazakhstan', 'a26:Category:Subdivisions_of_Kazakhstan')).
delete('skos:broader'('a26:Category:Irish-language_writers', 'a26:Category:Writers_by_language')).
delete('skos:broader'('a26:Category:1860s_in_South_Africa', 'a26:Category:1860s_by_country')).
delete('skos:broader'('a26:Category:French_anthropologists', 'a26:Category:French_people_by_occupation')).
delete('skos:broader'('a26:Category:Nepalese_refugees', 'a26:Category:Nepalese_people')).
delete('skos:broader'('a26:Category:North_Korean_military_personnel_by_war', 'a26:Category:North_Korean_military_personnel')).
