add('skos:broader'('a26:Category:Bridges_completed_in_1874', 'a26:Category:Transport_infrastructure_completed_in_1874')).
add('skos:broader'('a26:Category:New_Zealand_science_fiction_television_series', 'a26:Category:New_Zealand_science_fiction')).
add('skos:broader'('a26:Category:Airports_in_Greater_Houston', 'a26:Category:Transportation_in_Houston_Texas')).
add('skos:broader'('a26:Category:Census-designated_places_in_Tennessee', 'a26:Category:Populated_places_in_Tennessee')).
add('skos:broader'('a26:Category:1940s_in_Iceland', 'a26:Category:1940s_by_country')).
add('skos:broader'('a26:Category:Houses_in_Cambridge_Massachusetts', 'a26:Category:Houses_in_Massachusetts_by_city')).
add('skos:broader'('a26:Category:Visitor_attractions_in_Sullivan_County_New_York', 'a26:Category:Visitor_attractions_in_New_York_by_county')).
add('skos:broader'('a26:Category:English_ornithologists', 'a26:Category:British_ornithologists')).
add('skos:broader'('a26:Category:Italian_drama_films', 'a26:Category:Italian_films_by_genre')).
add('skos:broader'('a26:Category:Critically_endangered_species', 'a26:Category:Biota_by_conservation_status')).
delete('skos:broader'('a26:Category:New_York_Institute_of_Technology', 'a26:Category:Wikipedia_categories_named_after_universities_and_colleges_in_the_United_States')).
delete('skos:broader'('a26:Category:Turkish-language_works', 'a26:Category:Works_by_language')).
delete('skos:broader'('a26:Category:Television_shows_set_in_Poland', 'a26:Category:Television_shows_by_country_of_setting')).
delete('skos:broader'('a26:Category:Insects_of_New_Zealand', 'a26:Category:Arthropods_of_New_Zealand')).
delete('skos:broader'('a26:Category:Lothian', 'a26:Category:Former_subdivisions_of_Scotland')).
delete('skos:broader'('a26:Category:Preferential_electoral_systems', 'a26:Category:Voting_systems')).
delete('skos:broader'('a26:Category:Capacitors', 'a26:Category:Electrical_components')).
delete('skos:broader'('a26:Category:Historic_districts_in_Shenandoah_County_Virginia', 'a26:Category:Geography_of_Shenandoah_County_Virginia')).
delete('skos:broader'('a26:Category:People_from_Janesville_Wisconsin', 'a26:Category:People_from_Rock_County_Wisconsin')).
delete('skos:broader'('a26:Category:English_pop_singers', 'a26:Category:English_singers')).
