add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent135')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent97')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse19')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent6')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent9')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent39')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent84')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent272')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent198')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent387')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent146')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent102')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse1')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent115')).
delete('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor0')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse42')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent271')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent193')).
