add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent6')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent409')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent234')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse31')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent39')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent84')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent170')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor3')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor1')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse17')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent37')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent36')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent55')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent205')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse10')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent48')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent12')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent98')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent48')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent121')).
