add('skos:broader'('a26:Category:Publishing_companies_of_Hungary', 'a26:Category:Companies_of_Hungary_by_industry')).
add('skos:broader'('a26:Category:Buildings_and_structures_in_Dickinson_County_Iowa', 'a26:Category:Buildings_and_structures_in_Iowa_by_county')).
add('skos:broader'('a26:Category:Academics_of_the_University_of_Roehampton', 'a26:Category:People_associated_with_the_University_of_Roehampton')).
add('skos:broader'('a26:Category:Altötting_district', 'a26:Category:Upper_Bavaria')).
add('skos:broader'('a26:Category:Neoclassical_architecture_in_Iowa', 'a26:Category:Architecture_in_Iowa')).
add('skos:broader'('a26:Category:Gangsta_rappers', 'a26:Category:Gangsta_rap')).
add('skos:broader'('a26:Category:Parishes_of_Valka_District', 'a26:Category:Parishes_of_Latvia')).
add('skos:broader'('a26:Category:People_from_Kings_Lynn_and_West_Norfolk_district', 'a26:Category:People_from_Norfolk')).
add('skos:broader'('a26:Category:Provinces_of_South_Korea', 'a26:Category:Provinces_of_Korea')).
add('skos:broader'('a26:Category:Children_of_Prime_Ministers_of_the_United_Kingdom', 'a26:Category:British_children')).
add('skos:broader'('a26:Category:Politics_of_Shizuoka_Shizuoka', 'a26:Category:Shizuoka_Shizuoka')).
add('skos:broader'('a26:Category:New_York_metropolitan_area', 'a26:Category:Wikipedia_categories_named_after_regions_of_the_United_States')).
add('skos:broader'('a26:Category:1997_98_in_OFC_football', 'a26:Category:1997_in_association_football')).
add('skos:broader'('a26:Category:North_American_culture_by_country', 'a26:Category:North_American_culture')).
add('skos:broader'('a26:Category:Country_radio_stations_in_the_United_States', 'a26:Category:Country_radio_stations')).
add('skos:broader'('a26:Category:Theorems_in_plane_geometry', 'a26:Category:Theorems_in_geometry')).
add('skos:broader'('a26:Category:Ministers_of_Foreign_Affairs_of_the_Netherlands', 'a26:Category:Dutch_diplomats')).
add('skos:broader'('a26:Category:Westminster_system', 'a26:Category:Political_systems')).
add('skos:broader'('a26:Category:Freemasonry_in_Scotland', 'a26:Category:Organisations_based_in_Scotland')).
add('skos:broader'('a26:Category:Songwriters_from_Texas', 'a26:Category:Musicians_from_Texas')).
delete('skos:broader'('a26:Category:Maltese_archaeologists', 'a26:Category:Maltese_academics')).
delete('skos:broader'('a26:Category:Populated_places_in_Los_Angeles_County_California', 'a26:Category:Populated_places_in_California_by_county')).
delete('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:American_sportspeople')).
delete('skos:broader'('a26:Category:Roads_in_the_Russian_Far_East', 'a26:Category:Road_transport_in_the_Russian_Far_East')).
delete('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
delete('skos:broader'('a26:Category:School_districts_in_Erath_County_Texas', 'a26:Category:School_districts_in_Texas_by_county')).
delete('skos:broader'('a26:Category:Sports_venues_in_Punjab_India', 'a26:Category:Sport_in_Punjab_India')).
delete('skos:broader'('a26:Category:Video_albums', 'a26:Category:Music_videos')).
delete('skos:broader'('a26:Category:Senat_Marshals', 'a26:Category:Political_office-holders_in_Poland')).
delete('skos:broader'('a26:Category:2009_in_Catalan_sport', 'a26:Category:2009_in_Spanish_sport')).
delete('skos:broader'('a26:Category:Sources_on_Germanic_paganism', 'a26:Category:Historical_documents')).
delete('skos:broader'('a26:Category:Final_Fantasy_spin-offs', 'a26:Category:Final_Fantasy')).
delete('skos:broader'('a26:Category:Religion_in_Mongolia', 'a26:Category:Mongolian_society')).
delete('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1285_in_Europe')).
delete('skos:broader'('a26:Category:2013_Christmas_albums', 'a26:Category:2013_albums')).
delete('skos:broader'('a26:Category:University_of_Valencia', 'a26:Category:Wikipedia_categories_named_after_universities_and_colleges')).
delete('skos:broader'('a26:Category:TransLink_British_Columbia_bus_stations', 'a26:Category:TransLink_British_Columbia')).
delete('skos:broader'('a26:Category:Peruvian_sport_shooters', 'a26:Category:Peruvian_sportspeople')).
delete('skos:broader'('a26:Category:Soviet_Navy_personnel', 'a26:Category:Navy_personnel')).
delete('skos:broader'('a26:Category:Sportspeople_from_Knoxville_Tennessee', 'a26:Category:Sportspeople_from_Tennessee')).
