add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent34', 'http://www.Department2.University0.edu/Course13')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/Lecturer4', 'http://www.University303.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent90', '"UndergraduateStudent90@Department1.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent167', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent99', '"GraduateStudent99@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent75', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent369', 'http://www.Department1.University0.edu/Course24')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor4/Publication14', 'http://www.Department2.University0.edu/GraduateStudent44')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication1', 'http://www.Department1.University0.edu/AssociateProfessor4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent388', 'http://www.Department1.University0.edu/Course35')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent35', 'http://www.Department0.University0.edu/GraduateCourse21')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent5', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent12', 'http://www.Department2.University0.edu/AssociateProfessor2')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssociateProfessor10', 'http://www.Department2.University0.edu/GraduateCourse22')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent71', 'http://www.Department2.University0.edu/GraduateCourse43')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent165', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent418', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor1/Publication2', 'http://www.Department1.University0.edu/GraduateStudent40')).
add('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent27', '"GraduateStudent27@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication9', 'http://www.Department1.University0.edu/GraduateStudent129')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent216', '"UndergraduateStudent216@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor6/Publication4', 'http://www.Department2.University0.edu/AssistantProfessor6')).
add('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent12', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent329', '"UndergraduateStudent329@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent25', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent363', '"UndergraduateStudent363@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent164', 'http://www.Department2.University0.edu/Course6')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent113', 'http://www.Department2.University0.edu/Course27')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent105', 'http://www.Department1.University0.edu/Course46')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent69', 'http://www.Department0.University0.edu/Course20')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent115', 'http://www.Department1.University0.edu/Course19')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent290', '"UndergraduateStudent290@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent182', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent46', 'http://www.University723.edu')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent105', '"UndergraduateStudent105@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor8/Publication14', 'http://www.Department2.University0.edu/AssociateProfessor8')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor3/Publication5', 'http://www.Department1.University0.edu/GraduateStudent120')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent211', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent316', '"UndergraduateStudent316@Department0.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent17', '"UndergraduateStudent17@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor13/Publication2', 'http://www.Department0.University0.edu/GraduateStudent34')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor2/Publication0', 'http://www.Department2.University0.edu/AssociateProfessor2')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent69', 'http://www.Department0.University0.edu/GraduateCourse11')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent139', '"UndergraduateStudent139@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent284', '"UndergraduateStudent284@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent339', '"UndergraduateStudent339@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/Course39')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent343', 'http://www.Department2.University0.edu/Course34')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent10', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/AssistantProfessor6', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent40', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent77', 'http://www.Department1.University0.edu/Course18')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent13', 'http://www.Department0.University0.edu/FullProfessor3')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent179', 'http://www.Department0.University0.edu/Course1')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent54', 'http://www.Department1.University0.edu/GraduateCourse35')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent20', 'http://www.University294.edu')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent98', 'http://www.Department2.University0.edu/Course7')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent246', '"UndergraduateStudent246@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent109', '"UndergraduateStudent109@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor1/Publication4', 'http://www.Department1.University0.edu/FullProfessor1')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent49', 'http://www.Department0.University0.edu/GraduateCourse36')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent83', 'http://www.Department1.University0.edu/Course51')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent38', 'http://www.Department2.University0.edu/GraduateCourse30')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/AssistantProfessor1', 'http://www.Department1.University0.edu/GraduateCourse28')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent89', '"UndergraduateStudent89@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication13', 'http://www.Department1.University0.edu/GraduateStudent21')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent417', '"UndergraduateStudent417@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor4/Publication10', 'http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent342', 'http://www.Department2.University0.edu/Course32')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor0/Publication6', 'http://www.Department2.University0.edu/AssistantProfessor0')).
