add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent386', 'http://www.Department2.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent413', 'http://www.Department2.University0.edu/Course5')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent197', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent35', 'http://www.Department1.University0.edu/AssistantProfessor0')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent286', 'http://www.Department0.University0.edu/Course3')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent300', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent79', 'http://www.University741.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent247', 'http://www.Department0.University0.edu/Course42')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor5/Publication0', 'http://www.Department0.University0.edu/AssistantProfessor5')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent139', '"UndergraduateStudent139@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent106', 'http://www.Department1.University0.edu/GraduateCourse32')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent220', 'http://www.Department2.University0.edu/Course44')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor10/Publication13', 'http://www.Department0.University0.edu/GraduateStudent33')).
add('a1:emailAddress'('http://www.Department0.University0.edu/Lecturer2', '"Lecturer2@Department0.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent334', 'http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent25', 'http://www.Department2.University0.edu/Course36')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent103', 'http://www.Department2.University0.edu/FullProfessor4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent56', 'http://www.Department1.University0.edu/GraduateCourse16')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent370', 'http://www.Department1.University0.edu/AssistantProfessor6')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor4/Publication15', 'http://www.Department0.University0.edu/GraduateStudent97')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent239', 'http://www.Department2.University0.edu/Course17')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent303', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent149', 'http://www.Department2.University0.edu/Course32')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent27', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent230', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent60', 'http://www.University510.edu')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication6', 'http://www.Department1.University0.edu/GraduateStudent32')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication14', 'http://www.Department0.University0.edu/GraduateStudent13')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent223', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent127', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent242', '"UndergraduateStudent242@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor2/Publication2', 'http://www.Department2.University0.edu/GraduateStudent86')).
add('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent81', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent91', 'http://www.Department0.University0.edu/Course5')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent220', 'http://www.Department1.University0.edu/Course2')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent287', '"UndergraduateStudent287@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent204', '"UndergraduateStudent204@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent426', 'http://www.Department2.University0.edu/Course12')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent22', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent246', 'http://www.Department2.University0.edu/Course13')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent194', 'http://www.Department0.University0.edu/Course1')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent77', 'http://www.Department0.University0.edu/GraduateCourse29')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication5', 'http://www.Department0.University0.edu/AssistantProfessor6')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent26', 'http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent10', 'http://www.Department0.University0.edu/Course26')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent80', 'http://www.University43.edu')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent226', 'http://www.Department0.University0.edu/Course1')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent268', 'http://www.Department0.University0.edu/Course37')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent45', 'http://www.Department2.University0.edu/Course20')).
delete('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/AssociateProfessor10', 'http://www.University983.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent329', 'http://www.Department1.University0.edu/Course51')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent66', 'http://www.University141.edu')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent404', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent20', 'http://www.Department0.University0.edu/Course22')).
delete('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor3', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication11', 'http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication2', 'http://www.Department1.University0.edu/AssociateProfessor5')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent54', '"GraduateStudent54@Department0.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent252', '"UndergraduateStudent252@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication7', 'http://www.Department1.University0.edu/GraduateStudent50')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent12', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent259', 'http://www.Department0.University0.edu/AssociateProfessor9')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication3', 'http://www.Department2.University0.edu/GraduateStudent51')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent253', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent84', 'http://www.Department2.University0.edu/GraduateCourse46')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication0', 'http://www.Department2.University0.edu/AssistantProfessor8')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication7', 'http://www.Department2.University0.edu/GraduateStudent110')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent46', 'http://www.Department1.University0.edu/AssociateProfessor10')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent313', 'http://www.Department0.University0.edu/AssociateProfessor9')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication8', 'http://www.Department0.University0.edu/AssociateProfessor7')).
