add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor8/Publication7', 'http://www.Department1.University0.edu/GraduateStudent32')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent147', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent407', 'http://www.Department2.University0.edu/Course43')).
add('a1:telephone'('http://www.Department2.University0.edu/FullProfessor3', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent166', 'http://www.Department0.University0.edu/Course43')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent280', 'http://www.Department0.University0.edu/Course34')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication7', 'http://www.Department2.University0.edu/FullProfessor3')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication2', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent174', 'http://www.Department2.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent127', 'http://www.Department2.University0.edu/Course13')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent420', 'http://www.Department2.University0.edu/Course29')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent118', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor12', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication1', 'http://www.Department0.University0.edu/FullProfessor7')).
add('a1:telephone'('http://www.Department0.University0.edu/FullProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent290', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent51', 'http://www.Department0.University0.edu/GraduateCourse11')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor1/Publication6', 'http://www.Department0.University0.edu/GraduateStudent98')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent213', '"UndergraduateStudent213@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent5', 'http://www.Department1.University0.edu/GraduateCourse8')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent351', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication1', 'http://www.Department2.University0.edu/FullProfessor3')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent178', '"UndergraduateStudent178@Department2.University0.edu"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent66', 'http://www.University904.edu')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent373', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication12', 'http://www.Department2.University0.edu/GraduateStudent55')).
add('a1:telephone'('http://www.Department0.University0.edu/GraduateStudent24', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent103', 'http://www.Department0.University0.edu/GraduateCourse42')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor6', 'http://www.University944.edu')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent186', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent195', 'http://www.Department2.University0.edu/Course3')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent283', 'http://www.Department1.University0.edu/Course27')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent11', 'http://www.Department0.University0.edu/Course22')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent140', 'http://www.Department1.University0.edu/FullProfessor4')).
add('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/Lecturer4', 'http://www.University421.edu')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent183', 'http://www.Department2.University0.edu/Course10')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent321', 'http://www.Department1.University0.edu/Course7')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent254', 'http://www.Department1.University0.edu/Course36')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent395', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent43', 'http://www.Department2.University0.edu/Course46')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse41')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication1', 'http://www.Department0.University0.edu/GraduateStudent107')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent319', '"UndergraduateStudent319@Department0.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor11', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent88', 'http://www.University398.edu')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor7', 'http://www.Department0.University0.edu/GraduateCourse24')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent183', 'http://www.Department0.University0.edu/Course25')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent0', 'http://www.Department0.University0.edu/FullProfessor2')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent85', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent291', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent25', 'http://www.Department1.University0.edu/GraduateCourse10')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent16', '"GraduateStudent16@Department0.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent314', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent213', 'http://www.Department0.University0.edu/Course17')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent78', 'http://www.Department2.University0.edu/Course46')).
delete('a1:doctoralDegreeFrom'('http://www.Department2.University0.edu/AssociateProfessor8', 'http://www.University651.edu')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/Lecturer6', '"Lecturer6@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent37', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent136', 'http://www.Department0.University0.edu/Course13')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent339', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse45')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent372', '"UndergraduateStudent372@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent49', 'http://www.Department0.University0.edu/Course8')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication2', 'http://www.Department0.University0.edu/GraduateStudent15')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor0/Publication3', 'http://www.Department1.University0.edu/GraduateStudent11')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent85', 'http://www.Department0.University0.edu/Course41')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication1', 'http://www.Department0.University0.edu/GraduateStudent106')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent11', 'http://www.Department1.University0.edu/Course13')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent125', 'http://www.Department0.University0.edu/Course34')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/FullProfessor1', '"FullProfessor1@Department0.University0.edu"^^xsd:string')).
