add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent227', '"UndergraduateStudent227@Department0.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent204', '"UndergraduateStudent204@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor12/Publication1', 'http://www.Department2.University0.edu/AssociateProfessor12')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication14', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent125', 'http://www.Department1.University0.edu/Course6')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent401', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent13', 'http://www.Department0.University0.edu/GraduateCourse37')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent158', 'http://www.Department0.University0.edu/Course14')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent88', 'http://www.Department2.University0.edu/Course20')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent125', 'http://www.University885.edu')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent80', 'http://www.University43.edu')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent291', '"UndergraduateStudent291@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent321', '"UndergraduateStudent321@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication6', 'http://www.Department2.University0.edu/GraduateStudent101')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor11/Publication11', 'http://www.Department2.University0.edu/AssociateProfessor11')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent220', 'http://www.Department2.University0.edu/Course44')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication8', 'http://www.Department0.University0.edu/FullProfessor7')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent358', 'http://www.Department2.University0.edu/Course3')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent193', 'http://www.Department0.University0.edu/Course17')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent219', 'http://www.Department2.University0.edu/Course7')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent37', 'http://www.Department1.University0.edu/Course51')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent370', 'http://www.Department1.University0.edu/AssistantProfessor6')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication2', 'http://www.Department1.University0.edu/AssociateProfessor5')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent180', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent25', '"UndergraduateStudent25@Department0.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent54', '"GraduateStudent54@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent239', 'http://www.Department2.University0.edu/Course17')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent303', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent60', 'http://www.University510.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent84', 'http://www.Department0.University0.edu/GraduateCourse26')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent84', 'http://www.Department2.University0.edu/GraduateCourse46')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent223', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent242', '"UndergraduateStudent242@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication5', 'http://www.Department0.University0.edu/AssociateProfessor7')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent352', 'http://www.Department2.University0.edu/Course7')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent77', 'http://www.Department2.University0.edu/Course16')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent43', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent55', 'http://www.Department2.University0.edu/GraduateCourse39')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent286', 'http://www.Department0.University0.edu/Course3')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent66', 'http://www.Department1.University0.edu/FullProfessor7')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent194', 'http://www.Department0.University0.edu/Course1')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication13', 'http://www.Department1.University0.edu/GraduateStudent118')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent26', 'http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/FullProfessor1', '"FullProfessor1@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent143', 'http://www.Department0.University0.edu/Course50')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent45', 'http://www.Department2.University0.edu/Course20')).
delete('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent334', 'http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor1/Publication0', 'http://www.Department2.University0.edu/GraduateStudent13')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication7', 'http://www.Department2.University0.edu/GraduateStudent65')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent56', 'http://www.Department1.University0.edu/GraduateCourse16')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication11', 'http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication4', 'http://www.Department1.University0.edu/AssociateProfessor5')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent402', 'http://www.Department1.University0.edu/Course0')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent114', 'http://www.Department1.University0.edu/GraduateCourse26')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor4/Publication15', 'http://www.Department0.University0.edu/GraduateStudent97')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent17', 'http://www.Department1.University0.edu/GraduateCourse46')).
delete('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor6', 'http://www.University294.edu')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent174', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent412', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication6', 'http://www.Department1.University0.edu/GraduateStudent32')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication3', 'http://www.Department0.University0.edu/AssociateProfessor12')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication14', 'http://www.Department0.University0.edu/GraduateStudent13')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent199', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent89', '"UndergraduateStudent89@Department1.University0.edu"^^xsd:string')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/AssistantProfessor5', 'http://www.Department1.University0.edu/Course40')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor2/Publication2', 'http://www.Department2.University0.edu/GraduateStudent86')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent81', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication8', 'http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor4/Publication10', 'http://www.Department0.University0.edu/AssociateProfessor4')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent80', '"UndergraduateStudent80@Department1.University0.edu"^^xsd:string')).
