add('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent43', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent55', 'http://www.Department2.University0.edu/GraduateCourse39')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent249', 'http://www.Department1.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent194', 'http://www.Department0.University0.edu/Course1')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent247', 'http://www.Department0.University0.edu/Course42')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent86', '"UndergraduateStudent86@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent10', 'http://www.Department0.University0.edu/Course26')).
add('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor9', 'http://www.University376.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent143', 'http://www.Department0.University0.edu/Course50')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent106', 'http://www.Department1.University0.edu/GraduateCourse32')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent131', 'http://www.Department1.University0.edu/Course6')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication11', 'http://www.Department1.University0.edu/AssociateProfessor5')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent45', 'http://www.Department2.University0.edu/Course20')).
add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent334', 'http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent56', 'http://www.Department1.University0.edu/Course22')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent269', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor3', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent421', 'http://www.Department1.University0.edu/Course47')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent167', 'http://www.Department1.University0.edu/Course22')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent222', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent149', 'http://www.Department2.University0.edu/Course32')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication7', 'http://www.Department1.University0.edu/GraduateStudent50')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent63', 'http://www.University563.edu')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication3', 'http://www.Department0.University0.edu/AssociateProfessor12')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication6', 'http://www.Department1.University0.edu/GraduateStudent32')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor4/Publication14', 'http://www.Department0.University0.edu/GraduateStudent13')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent89', '"UndergraduateStudent89@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent374', 'http://www.Department1.University0.edu/Course40')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent46', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent8', '"UndergraduateStudent8@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication14', 'http://www.Department1.University0.edu/GraduateStudent113')).
add('a1:mastersDegreeFrom'('http://www.Department2.University0.edu/AssociateProfessor8', 'http://www.University513.edu')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor12/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor12')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor4/Publication10', 'http://www.Department0.University0.edu/AssociateProfessor4')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent80', '"UndergraduateStudent80@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent271', 'http://www.Department0.University0.edu/Course48')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent204', '"UndergraduateStudent204@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent217', 'http://www.Department2.University0.edu/Course31')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent21', 'http://www.Department0.University0.edu/Course33')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse40')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent22', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent401', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent158', 'http://www.Department0.University0.edu/Course14')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent173', '"UndergraduateStudent173@Department2.University0.edu"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent125', 'http://www.University885.edu')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent409', 'http://www.Department2.University0.edu/Course15')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent220', 'http://www.Department2.University0.edu/Course44')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent321', '"UndergraduateStudent321@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor0/Publication2', 'http://www.Department0.University0.edu/FullProfessor0')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/Lecturer2', '"Lecturer2@Department0.University0.edu"^^xsd:string')).
delete('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/AssociateProfessor10', 'http://www.University983.edu')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication5', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent339', '"UndergraduateStudent339@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent358', 'http://www.Department2.University0.edu/Course3')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent94', 'http://www.Department1.University0.edu/Course36')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor4', 'http://www.Department2.University0.edu/GraduateCourse34')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor2/Publication11', 'http://www.Department2.University0.edu/FullProfessor2')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent370', 'http://www.Department1.University0.edu/AssistantProfessor6')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication2', 'http://www.Department1.University0.edu/AssociateProfessor5')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent54', '"GraduateStudent54@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent265', 'http://www.Department1.University0.edu/Course10')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent230', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent84', 'http://www.Department0.University0.edu/GraduateCourse26')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent84', 'http://www.Department2.University0.edu/GraduateCourse46')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent242', '"UndergraduateStudent242@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent192', 'http://www.Department2.University0.edu/Course11')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent16', '"UndergraduateStudent16@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent352', 'http://www.Department2.University0.edu/Course7')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor5/Publication7', 'http://www.Department0.University0.edu/GraduateStudent90')).
