add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent2')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
add('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer2')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent174')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent52')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent110')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor5')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent38')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent297')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent89')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent123')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent8')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent101')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse28')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent14')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent103')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent20')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent183')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent113')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent42')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent61')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent316')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent248')).
add('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent42')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse26')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent264')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent90')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent92')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent303')).
delete('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer5')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent219')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent124')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent343')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent254')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent13')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent12')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent214')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse43')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent215')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent119')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent4')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent1')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent230')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent272')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent50')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent66')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent9')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent184')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent412')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent129')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent79')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent240')).
