add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent12')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent157')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent34')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent0')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent194')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent56')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent78')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent123')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent72')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent190')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent381')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent13')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent12')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse43')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse30')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent118')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent352')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent8')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent66')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent335')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent9')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent285')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent108')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent282')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent436')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent78')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent129')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent3')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent241')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent343')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent33')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent61')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent176')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent11')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent302')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent219')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent55')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent345')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent194')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent53')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent254')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse35')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent23')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent17')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent234')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent38')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent401')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent14')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent414')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent102')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent61')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent183')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent125')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent113')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent20')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent114')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent181')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
