add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent320')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent50')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent94')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent71')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent300')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent17')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent253')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent270')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent80')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor3')).
add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor2')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent250')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse17')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent122')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent354')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent417')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent148')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent105')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent313')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent112')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent267')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent224')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent21')).
add('a1:AssistantProfessor'('http://www.Department0.University0.edu/AssistantProfessor0')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse34')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent282')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse7')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent223')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent4')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent86')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent79')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent115')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent116')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse12')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent170')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent191')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent360')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent170')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent77')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent255')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent36')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent92')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent26')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent423')).
delete('a1:Department'('http://www.Department1.University0.edu')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse16')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent233')).
delete('a1:FullProfessor'('http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent165')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent22')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent69')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent65')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse21')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent227')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent67')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent43')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent220')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse41')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent206')).
