add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent98')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent135')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent112')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent21')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent4')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent198')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent84')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent426')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent99')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent51')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent11')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent94', 'http://www.Department1.University0.edu/FullProfessor7')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent57')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent70')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent48')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent258')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent258')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent92')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent118')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent212')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent62')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent188')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent374')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent358')).
add('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor8')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent205')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent40')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent82')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent142')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent266')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent268')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent224')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse22')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent14')).
add('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse6')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent410')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent87')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent106')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse39')).
add('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor4')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent178')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent116')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent405')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent31')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent172')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse32')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent70')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent303')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent34')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent257')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent278')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent18')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent259')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent10')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent94')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent32')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent237')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse36')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent101')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor3')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent274')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent272')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent331')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent98')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent104')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent416')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent128')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent129')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent88')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent47')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent63')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent52')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent439')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent161')).
delete('a1:FullProfessor'('http://www.Department0.University0.edu/FullProfessor1')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent266')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent225')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent16')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent431')).
