add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent344')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent403')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent428')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent155')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent173')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent218')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor11')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent174')).
add('a1:AssociateProfessor'('http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent101')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent32')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent74')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent38')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent4')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent292')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent45')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent401')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent49')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent398')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse28')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent46')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent122')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent207')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent6')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse24')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent229')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent314')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent91')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent163')).
add('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent21')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent330')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent220')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent244')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent117')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent43')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent108')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent36')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent86')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent129')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent121')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent21')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent33')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent21')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent366')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor11')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent56')).
delete('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer6')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent130')).
delete('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent54')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor2')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent128')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse42')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent421')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent425')).
delete('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor6')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent251')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent250')).
delete('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse27')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent27')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent274')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent146')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent14')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent8')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent22')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent167')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent313')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent67')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent312')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent49')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent265')).
delete('a1:AssistantProfessor'('http://www.Department1.University0.edu/AssistantProfessor1')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent224')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent29')).
delete('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor5')).
delete('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent14')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor13')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent0')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent283')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent28')).
