add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent112')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent93')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent79')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent81')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent153')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent286', 'http://www.Department1.University0.edu/Course30')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent62')).
add('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent51')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent348')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor10')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent303')).
add('a1:Lecturer'('http://www.Department1.University0.edu/Lecturer0')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent32')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent212')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse40')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent89')).
add('a1:GraduateCourse'('http://www.Department1.University0.edu/GraduateCourse21')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent19', 'http://www.Department1.University0.edu/Course0')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent139')).
add('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor3')).
add('a1:AssociateProfessor'('http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent18')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent419')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent8')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent84')).
add('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent77')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent1')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent189')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent313')).
add('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent183')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent313')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent83')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent20')).
add('a1:GraduateStudent'('http://www.Department0.University0.edu/GraduateStudent41')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent317')).
add('a1:Department'('http://www.Department0.University0.edu')).
add('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse44')).
add('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent205')).
add('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent285')).
add('a1:ResearchAssistant'('http://www.Department1.University0.edu/GraduateStudent32')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent98')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent386')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent177')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent403')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent136')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent72')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent193')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent132')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent38')).
delete('a1:GraduateStudent'('http://www.Department1.University0.edu/GraduateStudent15')).
delete('a1:ResearchAssistant'('http://www.Department2.University0.edu/GraduateStudent48')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent275')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent58')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent215')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent307')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent45')).
delete('a1:AssociateProfessor'('http://www.Department0.University0.edu/AssociateProfessor9')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor8/Publication5', 'http://www.Department1.University0.edu/GraduateStudent36')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent47')).
delete('a1:ResearchAssistant'('http://www.Department0.University0.edu/GraduateStudent107')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent374')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent14', 'http://www.Department1.University0.edu/Course45')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent66')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent71')).
delete('a1:GraduateCourse'('http://www.Department0.University0.edu/GraduateCourse3')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent145')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent25')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent229')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication1', 'http://www.Department1.University0.edu/AssociateProfessor5')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent84')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent0')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent68')).
delete('a1:UndergraduateStudent'('http://www.Department2.University0.edu/UndergraduateStudent311')).
delete('a1:UndergraduateStudent'('http://www.Department0.University0.edu/UndergraduateStudent142')).
delete('a1:FullProfessor'('http://www.Department1.University0.edu/FullProfessor3')).
delete('a1:GraduateStudent'('http://www.Department2.University0.edu/GraduateStudent100')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent319')).
delete('a1:UndergraduateStudent'('http://www.Department1.University0.edu/UndergraduateStudent202')).
delete('a1:GraduateCourse'('http://www.Department2.University0.edu/GraduateCourse48')).
delete('a1:AssistantProfessor'('http://www.Department2.University0.edu/AssistantProfessor4')).
