add('skos:broader'('a26:Category:British_alternative_rock_groups', 'a26:Category:Alternative_rock_groups_by_nationality')).
add('skos:broader'('a26:Category:Hellenistic_Egyptian_deities', 'a26:Category:Ptolemaic_Kingdom')).
add('skos:broader'('a26:Category:Chantilly_Racecourse', 'a26:Category:Wikipedia_categories_named_after_sports_venues')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs_in_Asia')).
add('skos:broader'('a26:Category:Bridge_disasters_in_the_United_States', 'a26:Category:Bridges_in_the_United_States')).
add('skos:broader'('a26:Category:Politics_of_Nepal', 'a26:Category:Nepal')).
add('skos:broader'('a26:Category:People_from_New_South_Wales', 'a26:Category:People_by_state_or_territory_in_Australia')).
add('skos:broader'('a26:Category:Mammals_of_Belize', 'a26:Category:Mammals_by_country')).
add('skos:broader'('a26:Category:Wars_by_country', 'a26:Category:Military_operations_by_country')).
add('skos:broader'('a26:Category:Turkish_Football_Federation_presidents', 'a26:Category:Turkish_Football_Federation')).
add('skos:broader'('a26:Category:Accidental_deaths_in_Brazil', 'a26:Category:Accidental_deaths_by_country')).
add('skos:broader'('a26:Category:1860s_in_South_Africa', 'a26:Category:19th_century_in_South_Africa')).
add('skos:broader'('a26:Category:Turkish_science_fiction_films', 'a26:Category:Science_fiction_films_by_country')).
add('skos:broader'('a26:Category:Buildings_and_structures_in_Grand_Casablanca', 'a26:Category:Buildings_and_structures_in_Morocco_by_region')).
add('skos:broader'('a26:Category:São_Tomé_and_Príncipe_footballers', 'a26:Category:São_Tomé_and_Príncipe_sportspeople')).
add('skos:broader'('a26:Category:Rosary', 'a26:Category:Sacramentals')).
add('skos:broader'('a26:Category:Charter_schools_in_the_United_States_by_state', 'a26:Category:Public_schools_in_the_United_States_by_state')).
add('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Analysis')).
add('skos:broader'('a26:Category:Areas_of_Dudley', 'a26:Category:Areas_of_the_West_Midlands_county')).
add('skos:broader'('a26:Category:Culture_ministries', 'a26:Category:Ministries_by_portfolio')).
add('skos:broader'('a26:Category:People_from_Dalarna', 'a26:Category:Dalarna')).
add('skos:broader'('a26:Category:Murals_in_the_United_States', 'a26:Category:Murals_by_country')).
add('skos:broader'('a26:Category:Boston_College', 'a26:Category:Universities_and_colleges_in_Massachusetts')).
add('skos:broader'('a26:Category:People_from_Newfoundland_island', 'a26:Category:Newfoundland_island')).
add('skos:broader'('a26:Category:Chevaliers_of_the_Order_of_Merit_Ukraine', 'a26:Category:Civil_awards_and_decorations_of_Ukraine')).
add('skos:broader'('a26:Category:Ethnic_groups_in_Arizona', 'a26:Category:Ethnic_groups_in_the_United_States_by_state')).
add('skos:broader'('a26:Category:History_books_about_countries', 'a26:Category:History_books')).
add('skos:broader'('a26:Category:Fictional_species_and_races', 'a26:Category:Species')).
add('skos:broader'('a26:Category:Cell_nucleus', 'a26:Category:Organelles')).
add('skos:broader'('a26:Category:Urban_quarters_in_the_United_States', 'a26:Category:Quarters')).
delete('skos:broader'('a26:Category:Telecommunications_companies_of_Singapore', 'a26:Category:Telecommunications_companies_by_country')).
delete('skos:broader'('a26:Category:Theatres_in_New_York_City', 'a26:Category:Theatre_in_New_York_City')).
delete('skos:broader'('a26:Category:Graphemes', 'a26:Category:Units_of_morphological_analysis')).
delete('skos:broader'('a26:Category:River_Ver', 'a26:Category:Rivers_of_England')).
delete('skos:broader'('a26:Category:Regions_of_Maharashtra', 'a26:Category:Geography_of_Maharashtra')).
delete('skos:broader'('a26:Category:Politics_of_Shizuoka_Shizuoka', 'a26:Category:Shizuoka_Shizuoka')).
delete('skos:broader'('a26:Category:Bodleian_Library_collection', 'a26:Category:Bodleian_Library')).
delete('skos:broader'('a26:Category:Defunct_cycling_teams', 'a26:Category:Cycling_teams')).
delete('skos:broader'('a26:Category:Scottish_Professional_Football_League', 'a26:Category:Wikipedia_categories_named_after_sports_leagues')).
delete('skos:broader'('a26:Category:South_African_people_of_Zimbabwean_descent', 'a26:Category:South_Africa_Zimbabwe_relations')).
delete('skos:broader'('a26:Category:Politics_of_the_Republic_of_Ireland', 'a26:Category:Politics_of_Europe')).
delete('skos:broader'('a26:Category:Forest_of_Dean', 'a26:Category:Non-metropolitan_districts_of_Gloucestershire')).
delete('skos:broader'('a26:Category:Towns_and_villages_in_Latvia', 'a26:Category:Towns_by_country')).
delete('skos:broader'('a26:Category:Mento', 'a26:Category:Jamaican_styles_of_music')).
delete('skos:broader'('a26:Category:Płock_County', 'a26:Category:Land_counties_of_Masovian_Voivodeship')).
delete('skos:broader'('a26:Category:Romanian_Christian_monks', 'a26:Category:Romanian_men_by_occupation')).
delete('skos:broader'('a26:Category:Government_of_Coahuila', 'a26:Category:Coahuila')).
delete('skos:broader'('a26:Category:1980s_establishments_in_Russia', 'a26:Category:1980s_establishments_in_the_Soviet_Union')).
delete('skos:broader'('a26:Category:Communities_on_the_Nile_River', 'a26:Category:Nile')).
delete('skos:broader'('a26:Category:The_Hart_Foundation_members', 'a26:Category:Independent_promotions_teams_and_stables')).
delete('skos:broader'('a26:Category:Parma_FC_players', 'a26:Category:Footballers_in_Italy_by_club')).
delete('skos:broader'('a26:Category:Populated_places_in_Galikash_County', 'a26:Category:Populated_places_in_Golestan_Province')).
delete('skos:broader'('a26:Category:Films_shot_in_Hong_Kong', 'a26:Category:Hong_Kong_culture')).
delete('skos:broader'('a26:Category:Companies_based_in_Los_Angeles_California', 'a26:Category:Organizations_based_in_Los_Angeles_California')).
delete('skos:broader'('a26:Category:Towns_and_villages_in_Latvia', 'a26:Category:Populated_places_in_Latvia')).
delete('skos:broader'('a26:Category:Scottish_rock_music_groups', 'a26:Category:Scottish_musical_groups_by_genre')).
delete('skos:broader'('a26:Category:Glamorgan_cricketers', 'a26:Category:Cricket_in_Glamorgan')).
delete('skos:broader'('a26:Category:Swimming_by_country', 'a26:Category:Categories_by_country')).
delete('skos:broader'('a26:Category:Radio_stations_in_Buffalo_New_York', 'a26:Category:Media_in_Buffalo_New_York')).
delete('skos:broader'('a26:Category:Invasive_plant_species', 'a26:Category:Invasive_species')).
