add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=455755&method=min&width=141&height=111')).
add('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/yarm_tepe')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=2015516')).
add('a1:E48_Place_Name'('http://arachne.uni-koeln.de/vocabulary/place#orchomenos-arkadien')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=647363')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1410074&method=min&width=141&height=111')).
add('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/spoleto')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1130108')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=1343041&method=min&width=141&height=111')).
add('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=3446091')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=488853')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=895543&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=475040')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=488710&method=min&width=141&height=111')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.php/key=941793')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=643839')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=3779717')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=473650')).
delete('a1:E48_Place_Name'('http://id.clarosnet.org/places/metamorphoses/placename/serres')).
delete('a1:E38_Image'('http://arachne.uni-koeln.de/arachne/images/image.phpKey=2092320')).
