add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent36', 'http://www.Department1.University0.edu/Course35')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor0/Publication3', 'http://www.Department1.University0.edu/FullProfessor0')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent85', '"GraduateStudent85@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent106', 'http://www.Department1.University0.edu/Course51')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent298', 'http://www.Department2.University0.edu/Course4')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent243', 'http://www.Department2.University0.edu/Course46')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent72', 'http://www.University979.edu')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent204', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor5/Publication0', 'http://www.Department2.University0.edu/AssistantProfessor5')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent27', 'http://www.University398.edu')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor1/Publication15', 'http://www.Department0.University0.edu/GraduateStudent72')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent130', '"UndergraduateStudent130@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent11', 'http://www.Department1.University0.edu/GraduateCourse46')).
delete('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent63', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent49', 'http://www.Department1.University0.edu/Course30')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent253', 'http://www.Department0.University0.edu/Course5')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent28', 'http://www.Department0.University0.edu/Course11')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor5/Publication16', 'http://www.Department2.University0.edu/AssociateProfessor5')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent36', 'http://www.Department1.University0.edu/AssistantProfessor5')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor3/Publication1', 'http://www.Department1.University0.edu/GraduateStudent123')).
