add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent132', '"UndergraduateStudent132@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent24', '"UndergraduateStudent24@Department1.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent118', 'http://www.Department1.University0.edu/AssociateProfessor7')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor2/Publication18', 'http://www.Department1.University0.edu/GraduateStudent110')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent141', '"UndergraduateStudent141@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent204', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent285', 'http://www.Department0.University0.edu/FullProfessor0')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent81', 'http://www.University26.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent28', 'http://www.Department0.University0.edu/Course11')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent70', '"GraduateStudent70@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent247', 'http://www.Department0.University0.edu/Course48')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent356', '"UndergraduateStudent356@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent69', 'http://www.Department1.University0.edu/Course33')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication0', 'http://www.Department2.University0.edu/AssistantProfessor8')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent5', 'http://www.Department1.University0.edu/Course15')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent69', 'http://www.Department0.University0.edu/AssociateProfessor0')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent139', 'http://www.Department0.University0.edu/Course15')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent27', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor1/Publication1', 'http://www.Department2.University0.edu/GraduateStudent32')).
delete('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent62', 'http://www.Department0.University0.edu/Course9')).
