add('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Ptolemaic_colonies')).
add('skos:broader'('a26:Category:International_water_polo_competitions_hosted_by_France', 'a26:Category:International_water_polo_competitions_by_host')).
add('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Topology')).
add('skos:broader'('a26:Category:People_from_the_Las_Vegas_Valley', 'a26:Category:People_by_populated_place_in_Nevada')).
add('skos:broader'('a26:Category:Neighbourhoods_of_Helsinki', 'a26:Category:Geography_of_Helsinki')).
add('skos:broader'('a26:Category:Buildings_and_structures_in_Teton_County_Wyoming', 'a26:Category:Buildings_and_structures_in_Wyoming_by_county')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Films_by_country')).
add('skos:broader'('a26:Category:Populated_places_in_Rio_Grande_do_Sul', 'a26:Category:Geography_of_Rio_Grande_do_Sul')).
add('skos:broader'('a26:Category:Geography_of_the_Northern_Territory', 'a26:Category:Geography_of_Australia_by_state_or_territory')).
delete('skos:broader'('a26:Category:Cyclists_from_Western_Australia', 'a26:Category:Sportspeople_from_Western_Australia_by_sport')).
delete('skos:broader'('a26:Category:1285_in_England', 'a26:Category:1280s_in_England')).
delete('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publisher')).
delete('skos:broader'('a26:Category:Austrian_Football_Bundesliga_players', 'a26:Category:Austrian_Football_Bundesliga')).
delete('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:18th-century_monarchs')).
delete('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Archaeological_sites_in_Egypt')).
delete('skos:broader'('a26:Category:Professional_Indoor_Football_League_teams', 'a26:Category:Indoor_American_football_teams_in_the_United_States_by_league')).
delete('skos:broader'('a26:Category:Turkish_Football_Federation_presidents', 'a26:Category:Turkish_Football_Federation')).
delete('skos:broader'('a26:Category:Visitor_attractions_in_Ulsan', 'a26:Category:Tourism_in_Ulsan')).
delete('skos:broader'('a26:Category:Companies_based_in_Atlanta_Georgia', 'a26:Category:Companies_based_in_Georgia_U.S._state_by_city')).
