add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent352', 'http://www.Department1.University0.edu/Course47')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent359', 'http://www.Department1.University0.edu/Course9')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor8/Publication7', 'http://www.Department1.University0.edu/GraduateStudent32')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent178', 'http://www.Department2.University0.edu/Course46')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication2', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent247', 'http://www.Department2.University0.edu/Course16')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent1', 'http://www.Department2.University0.edu/AssistantProfessor6')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor9/Publication7', 'http://www.Department2.University0.edu/AssociateProfessor9')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent186', 'http://www.Department0.University0.edu/Course45')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent171', '"UndergraduateStudent171@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent290', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication15', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor8/Publication10', 'http://www.Department2.University0.edu/GraduateStudent23')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor5/Publication15', 'http://www.Department0.University0.edu/FullProfessor5')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication1', 'http://www.Department2.University0.edu/FullProfessor3')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor8/Publication7', 'http://www.Department1.University0.edu/FullProfessor8')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent103', 'http://www.Department0.University0.edu/GraduateCourse42')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent92', 'http://www.Department0.University0.edu/AssistantProfessor1')).
add('a1:telephone'('http://www.Department0.University0.edu/AssociateProfessor5', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent15', 'http://www.Department0.University0.edu/GraduateCourse20')).
add('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor0', 'http://www.Department1.University0.edu/GraduateCourse0')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent283', 'http://www.Department1.University0.edu/Course27')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent309', 'http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor11/Publication2', 'http://www.Department0.University0.edu/GraduateStudent15')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent23', '"UndergraduateStudent23@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent301', 'http://www.Department1.University0.edu/Course20')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication14', 'http://www.Department1.University0.edu/GraduateStudent113')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor5/Publication8', 'http://www.Department2.University0.edu/GraduateStudent14')).
add('a1:teachingAssistantOf'('http://www.Department0.University0.edu/GraduateStudent44', 'http://www.Department0.University0.edu/Course45')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent304', 'http://www.Department0.University0.edu/Course32')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent410', 'http://www.Department2.University0.edu/Course16')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent279', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent407', 'http://www.Department2.University0.edu/Course43')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent124', 'http://www.Department2.University0.edu/Course16')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent102', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent39', '"GraduateStudent39@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent58', 'http://www.Department0.University0.edu/Course43')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent331', 'http://www.Department2.University0.edu/Course41')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor2', 'http://www.Department2.University0.edu/Course33')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent165', 'http://www.Department2.University0.edu/Course41')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor7/Publication4', 'http://www.Department0.University0.edu/GraduateStudent77')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent260', 'http://www.Department2.University0.edu/Course18')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent118', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/AssociateProfessor7', 'http://www.Department0.University0.edu/GraduateCourse24')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent291', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssistantProfessor5/Publication4', 'http://www.Department1.University0.edu/GraduateStudent78')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent191', 'http://www.Department2.University0.edu/Course45')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent415', '"UndergraduateStudent415@Department1.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent427', 'http://www.Department1.University0.edu/Course46')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent78', 'http://www.Department2.University0.edu/Course46')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent128', 'http://www.Department1.University0.edu/Course11')).
delete('a1:doctoralDegreeFrom'('http://www.Department2.University0.edu/AssociateProfessor8', 'http://www.University651.edu')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication5', 'http://www.Department2.University0.edu/AssociateProfessor3')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent136', 'http://www.Department0.University0.edu/Course13')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent1', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent195', 'http://www.Department2.University0.edu/Course3')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor3/Publication1', 'http://www.Department0.University0.edu/GraduateStudent106')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent241', '"UndergraduateStudent241@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/GraduateStudent4', '"GraduateStudent4@Department2.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/AssistantProfessor0')).
