add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor12/Publication1', 'http://www.Department2.University0.edu/AssociateProfessor12')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent13', 'http://www.Department0.University0.edu/GraduateCourse37')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent79', 'http://www.University741.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent194', 'http://www.Department0.University0.edu/Course1')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication5', 'http://www.Department0.University0.edu/AssistantProfessor6')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent77', 'http://www.Department0.University0.edu/GraduateCourse29')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent125', 'http://www.University885.edu')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent173', '"UndergraduateStudent173@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent378', 'http://www.Department1.University0.edu/Course35')).
add('a1:emailAddress'('http://www.Department0.University0.edu/Lecturer2', '"Lecturer2@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent269', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication5', 'http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent219', 'http://www.Department2.University0.edu/Course7')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent94', 'http://www.Department1.University0.edu/Course36')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication2', 'http://www.Department1.University0.edu/AssociateProfessor5')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent402', 'http://www.Department1.University0.edu/Course0')).
add('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent54', '"GraduateStudent54@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent303', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent174', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent27', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent252', '"UndergraduateStudent252@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor12/Publication3', 'http://www.Department0.University0.edu/AssociateProfessor12')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent127', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent84', 'http://www.Department2.University0.edu/GraduateCourse46')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication7', 'http://www.Department2.University0.edu/GraduateStudent110')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor2/Publication2', 'http://www.Department2.University0.edu/GraduateStudent86')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent91', 'http://www.Department0.University0.edu/Course5')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent424', 'http://www.Department2.University0.edu/Course21')).
add('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/AssistantProfessor0')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor12/Publication4', 'http://www.Department2.University0.edu/AssociateProfessor12')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent227', '"UndergraduateStudent227@Department0.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent167', '"UndergraduateStudent167@Department0.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication2', 'http://www.Department1.University0.edu/GraduateStudent64')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent426', 'http://www.Department2.University0.edu/Course12')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse40')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication14', 'http://www.Department1.University0.edu/AssociateProfessor10')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent125', 'http://www.Department1.University0.edu/Course6')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent286', 'http://www.Department0.University0.edu/Course3')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent401', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor3', 'http://www.Department1.University0.edu/Course7')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent344', 'http://www.Department2.University0.edu/Course23')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent252', 'http://www.Department1.University0.edu/Course36')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent26', 'http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent80', 'http://www.University43.edu')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor10/Publication13', 'http://www.Department0.University0.edu/GraduateStudent33')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent268', 'http://www.Department0.University0.edu/Course37')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent89', 'http://www.Department0.University0.edu/AssistantProfessor0')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent329', 'http://www.Department1.University0.edu/Course51')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent339', '"UndergraduateStudent339@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent358', 'http://www.Department2.University0.edu/Course3')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent193', 'http://www.Department0.University0.edu/Course17')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication7', 'http://www.Department2.University0.edu/GraduateStudent65')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent66', 'http://www.University141.edu')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent404', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/AssociateProfessor3', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent95', 'http://www.Department1.University0.edu/Course52')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent180', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent76', 'http://www.Department1.University0.edu/Course38')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent12', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
