add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent167', '"UndergraduateStudent167@Department0.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent125', 'http://www.Department1.University0.edu/Course6')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication14', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor2/Publication0', 'http://www.Department1.University0.edu/GraduateStudent37')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent111', 'http://www.Department1.University0.edu/GraduateCourse42')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent66', 'http://www.Department1.University0.edu/FullProfessor7')).
add('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor3', 'http://www.Department1.University0.edu/Course7')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent344', 'http://www.Department2.University0.edu/Course23')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent252', 'http://www.Department1.University0.edu/Course36')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent247', 'http://www.Department0.University0.edu/Course42')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent143', 'http://www.Department0.University0.edu/Course50')).
add('a1:undergraduateDegreeFrom'('http://www.Department0.University0.edu/GraduateStudent80', 'http://www.University43.edu')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor10/Publication13', 'http://www.Department0.University0.edu/GraduateStudent33')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent85', '"UndergraduateStudent85@Department1.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent89', 'http://www.Department0.University0.edu/AssistantProfessor0')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent34', '"UndergraduateStudent34@Department1.University0.edu"^^xsd:string')).
add('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/AssociateProfessor10', 'http://www.University983.edu')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent89', 'http://www.Department1.University0.edu/GraduateCourse1')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication8', 'http://www.Department0.University0.edu/FullProfessor7')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent339', '"UndergraduateStudent339@Department2.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication7', 'http://www.Department2.University0.edu/GraduateStudent65')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent193', 'http://www.Department0.University0.edu/Course17')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent133', '"UndergraduateStudent133@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent20', 'http://www.Department0.University0.edu/Course22')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent95', 'http://www.Department1.University0.edu/Course52')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent12', 'http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent89', '"UndergraduateStudent89@Department1.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication8', 'http://www.Department0.University0.edu/AssociateProfessor7')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent192', 'http://www.Department2.University0.edu/Course11')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent271', 'http://www.Department0.University0.edu/Course48')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/FullProfessor7', 'http://www.Department0.University0.edu/GraduateCourse11')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent53', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent21', 'http://www.Department0.University0.edu/Course33')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor12/Publication1', 'http://www.Department2.University0.edu/AssociateProfessor12')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent418', 'http://www.Department2.University0.edu/Course29')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent194', 'http://www.Department0.University0.edu/Course1')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent173', '"UndergraduateStudent173@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent378', 'http://www.Department1.University0.edu/Course35')).
delete('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor9', 'http://www.University376.edu')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent10', 'http://www.Department0.University0.edu/Course26')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent63', 'http://www.Department1.University0.edu/FullProfessor5')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent321', '"UndergraduateStudent321@Department0.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/Lecturer2', '"Lecturer2@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent163', 'http://www.Department0.University0.edu/Course18')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent269', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication11', 'http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent37', 'http://www.Department1.University0.edu/Course51')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication2', 'http://www.Department1.University0.edu/AssociateProfessor5')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication6', 'http://www.Department1.University0.edu/GraduateStudent103')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent114', 'http://www.Department1.University0.edu/GraduateCourse26')).
delete('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor6', 'http://www.University294.edu')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent174', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent230', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication6', 'http://www.Department1.University0.edu/GraduateStudent32')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent84', 'http://www.Department2.University0.edu/GraduateCourse46')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/AssistantProfessor5', 'http://www.Department1.University0.edu/Course40')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent8', '"UndergraduateStudent8@Department2.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent81', 'http://www.Department1.University0.edu/AssistantProfessor0')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent80', '"UndergraduateStudent80@Department1.University0.edu"^^xsd:string')).
