add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent271', 'http://www.Department0.University0.edu/Course48')).
add('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent53', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent217', 'http://www.Department2.University0.edu/Course31')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent418', 'http://www.Department2.University0.edu/Course29')).
add('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent197', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent83', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent137', '"UndergraduateStudent137@Department0.University0.edu"^^xsd:string')).
add('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor3', 'http://www.Department1.University0.edu/Course7')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent66', 'http://www.Department1.University0.edu/FullProfessor7')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent77', 'http://www.Department0.University0.edu/GraduateCourse29')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent173', '"UndergraduateStudent173@Department2.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent10', 'http://www.Department0.University0.edu/Course26')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent409', 'http://www.Department2.University0.edu/Course15')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent131', 'http://www.Department1.University0.edu/Course6')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent321', '"UndergraduateStudent321@Department0.University0.edu"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor10/Publication13', 'http://www.Department0.University0.edu/GraduateStudent33')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent268', 'http://www.Department0.University0.edu/Course37')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent45', 'http://www.Department2.University0.edu/Course20')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent329', 'http://www.Department1.University0.edu/Course51')).
add('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor4', 'http://www.Department2.University0.edu/GraduateCourse34')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication2', 'http://www.Department1.University0.edu/AssociateProfessor5')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent180', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/AssociateProfessor6', 'http://www.University294.edu')).
add('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent252', '"UndergraduateStudent252@Department0.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent174', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent412', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication6', 'http://www.Department1.University0.edu/GraduateStudent32')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent46', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication5', 'http://www.Department0.University0.edu/AssociateProfessor7')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent80', '"UndergraduateStudent80@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent43', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent35', 'http://www.Department1.University0.edu/AssistantProfessor0')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent286', 'http://www.Department0.University0.edu/Course3')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication13', 'http://www.Department1.University0.edu/GraduateStudent118')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent194', 'http://www.Department0.University0.edu/Course1')).
delete('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent26', 'http://www.Department2.University0.edu/FullProfessor0')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/FullProfessor1', '"FullProfessor1@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent139', '"UndergraduateStudent139@Department2.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/Lecturer3', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication11', 'http://www.Department1.University0.edu/AssociateProfessor5')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent226', 'http://www.Department0.University0.edu/Course1')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent414', 'http://www.Department1.University0.edu/Course40')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent85', '"UndergraduateStudent85@Department1.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department0.University0.edu/GraduateStudent89', 'http://www.Department0.University0.edu/AssistantProfessor0')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent163', 'http://www.Department0.University0.edu/Course18')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent20', 'http://www.Department0.University0.edu/Course22')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent293', 'http://www.Department0.University0.edu/Course25')).
delete('a1:advisor'('http://www.Department1.University0.edu/UndergraduateStudent370', 'http://www.Department1.University0.edu/AssistantProfessor6')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor4/Publication15', 'http://www.Department0.University0.edu/GraduateStudent97')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent76', 'http://www.Department1.University0.edu/Course38')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent54', '"GraduateStudent54@Department0.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent303', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent60', 'http://www.University510.edu')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent74', 'http://www.University663.edu')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication3', 'http://www.Department2.University0.edu/GraduateStudent51')).
delete('a1:mastersDegreeFrom'('http://www.Department0.University0.edu/FullProfessor7', 'http://www.University459.edu')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent242', '"UndergraduateStudent242@Department1.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent152', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent424', 'http://www.Department2.University0.edu/Course21')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor5/Publication7', 'http://www.Department0.University0.edu/GraduateStudent90')).
