add('skos:broader'('a26:Category:Monotypic_reptile_genera', 'a26:Category:Monotypic_tetrapod_genera')).
add('skos:broader'('a26:Category:Visitor_attractions_by_country', 'a26:Category:Visitor_attractions')).
add('skos:broader'('a26:Category:Communes_in_Galați_County', 'a26:Category:Communes_and_villages_in_Romania')).
add('skos:broader'('a26:Category:2010_novels', 'a26:Category:2010s_novels')).
add('skos:broader'('a26:Category:Fauna_of_the_Marquesas_Islands', 'a26:Category:Environment_of_the_Marquesas_Islands')).
add('skos:broader'('a26:Category:Neoclassical_architecture_in_Iowa', 'a26:Category:Architecture_in_Iowa')).
add('skos:broader'('a26:Category:Welsh_language', 'a26:Category:Welsh_society')).
add('skos:broader'('a26:Category:People_from_Liss', 'a26:Category:People_from_East_Hampshire_district')).
add('skos:broader'('a26:Category:Bahrain_Defence_Force', 'a26:Category:Wikipedia_categories_named_after_military_units_and_formations')).
add('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Mammal_breeds')).
add('skos:broader'('a26:Category:Columbine_High_School_massacre', 'a26:Category:Crimes_in_Colorado')).
add('skos:broader'('a26:Category:1863_in_Poland', 'a26:Category:1860s_in_Poland')).
add('skos:broader'('a26:Category:Teams_in_international_cricket', 'a26:Category:International_cricket_competitions')).
add('skos:broader'('a26:Category:Video_albums_by_artist_nationality', 'a26:Category:Albums_by_artist_nationality')).
add('skos:broader'('a26:Category:Wikipedia_categories_named_after_universities_and_colleges_in_the_United_States', 'a26:Category:Wikipedia_categories_named_after_universities_and_colleges')).
add('skos:broader'('a26:Category:Texas_AandM_University_people', 'a26:Category:Texas_AandM_University_System_people')).
add('skos:broader'('a26:Category:Medical_associations_based_in_the_United_Kingdom', 'a26:Category:Professional_associations_based_in_the_United_Kingdom')).
add('skos:broader'('a26:Category:Attorneys_General_for_England_and_Wales', 'a26:Category:Political_office-holders_in_the_United_Kingdom')).
add('skos:broader'('a26:Category:Ambassadors_of_the_United_States_to_Austria', 'a26:Category:Austria_United_States_relations')).
add('skos:broader'('a26:Category:Association_football_managers_by_competition', 'a26:Category:Association_football_competitions')).
add('skos:broader'('a26:Category:People_indicted_for_crimes_against_humanity', 'a26:Category:Crimes_against_humanity')).
add('skos:broader'('a26:Category:Princes_of_Lippe', 'a26:Category:House_of_Lippe')).
add('skos:broader'('a26:Category:Ambassadors_of_Russia_to_Fiji', 'a26:Category:Ambassadors_to_Fiji')).
add('skos:broader'('a26:Category:Documentary_films_about_British_royalty', 'a26:Category:Documentary_films_about_the_United_Kingdom')).
add('skos:broader'('a26:Category:Fauna_of_Micronesia', 'a26:Category:Fauna_of_Oceania')).
add('skos:broader'('a26:Category:City_councils', 'a26:Category:Cities')).
add('skos:broader'('a26:Category:Members_of_the_Jammu_and_Kashmir_Legislative_Assembly', 'a26:Category:Jammu_and_Kashmir_Legislative_Assembly')).
add('skos:broader'('a26:Category:Ghanaian_MPs_1997_2001', 'a26:Category:Members_of_the_Parliament_of_Ghana_by_Parliament')).
add('skos:broader'('a26:Category:College_football_rivalries_in_the_United_States', 'a26:Category:College_sports_rivalries_in_the_United_States')).
add('skos:broader'('a26:Category:Song_recordings_produced_by_Shizzi', 'a26:Category:Song_recordings_by_producer')).
add('skos:broader'('a26:Category:Former_districts_of_Hiroshima_Prefecture', 'a26:Category:Former_districts_of_Japan')).
add('skos:broader'('a26:Category:Yugoslavia', 'a26:Category:Former_countries_in_Europe')).
add('skos:broader'('a26:Category:Palaces_in_Malta', 'a26:Category:Palaces_in_Europe')).
add('skos:broader'('a26:Category:Culture_ministries', 'a26:Category:Ministries_by_portfolio')).
add('skos:broader'('a26:Category:Animals_described_in_1968', 'a26:Category:Species_described_in_1968')).
add('skos:broader'('a26:Category:Companies_based_in_Los_Angeles_California', 'a26:Category:Companies_based_in_Los_Angeles_County_California')).
add('skos:broader'('a26:Category:Theatre_in_the_Republic_of_Ireland', 'a26:Category:Theatre_in_Ireland')).
add('skos:broader'('a26:Category:River_islands_of_Virginia', 'a26:Category:Islands_of_Virginia')).
add('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
add('skos:broader'('a26:Category:English_first-class_cricket_teams', 'a26:Category:Sports_clubs_in_England')).
delete('skos:broader'('a26:Category:Grammy_Hall_of_Fame_Award_recipients', 'a26:Category:Music_hall_of_fame_inductees')).
delete('skos:broader'('a26:Category:Rivers_of_Botoșani_County', 'a26:Category:Rivers_of_Romania_by_county')).
delete('skos:broader'('a26:Category:Princes_of_Lippe', 'a26:Category:People_from_Lippe')).
delete('skos:broader'('a26:Category:13th-century_female_rulers', 'a26:Category:Women_rulers')).
delete('skos:broader'('a26:Category:EverQuest_games_and_expansions', 'a26:Category:Fantasy_video_games')).
delete('skos:broader'('a26:Category:Wars_involving_the_Peoples_Republic_of_China', 'a26:Category:Military_history_of_the_Peoples_Republic_of_China')).
delete('skos:broader'('a26:Category:Townships_in_Jewell_County_Kansas', 'a26:Category:Townships_in_Kansas_by_county')).
delete('skos:broader'('a26:Category:Austrian_Football_Bundesliga_players', 'a26:Category:Association_football_players_by_competition')).
delete('skos:broader'('a26:Category:Spiders_of_China', 'a26:Category:Spiders_by_country')).
delete('skos:broader'('a26:Category:Monasteries_in_Norfolk', 'a26:Category:Buildings_and_structures_in_Norfolk')).
delete('skos:broader'('a26:Category:Conservative_Democrats_of_Slovakia_politicians', 'a26:Category:Slovak_politicians_by_party')).
delete('skos:broader'('a26:Category:Jimmy_Reed_songs', 'a26:Category:Blues_songs')).
delete('skos:broader'('a26:Category:Austrian_people_of_Czech_descent', 'a26:Category:Austrian_people_by_ethnic_or_national_origin')).
delete('skos:broader'('a26:Category:Academics_of_London_South_Bank_University', 'a26:Category:Academics_by_university_in_England')).
delete('skos:broader'('a26:Category:People_educated_at_The_Perse_School', 'a26:Category:People_from_Cambridge')).
delete('skos:broader'('a26:Category:Azerbaijani_awards', 'a26:Category:Azerbaijani_culture')).
delete('skos:broader'('a26:Category:Ambient_music_groups', 'a26:Category:Ambient_musicians')).
delete('skos:broader'('a26:Category:Sportspeople_from_Chicago_Illinois', 'a26:Category:Sportspeople_by_city_in_the_United_States')).
delete('skos:broader'('a26:Category:Landforms_of_Mercer_County_Kentucky', 'a26:Category:Landforms_of_Kentucky_by_county')).
delete('skos:broader'('a26:Category:Caernarfonshire', 'a26:Category:Wikipedia_categories_named_after_counties_of_Wales')).
delete('skos:broader'('a26:Category:Stock_exchanges_in_South_America', 'a26:Category:Stock_exchanges_by_continent')).
delete('skos:broader'('a26:Category:National_Heritage_Fellowship_winners', 'a26:Category:National_Endowment_for_the_Arts')).
delete('skos:broader'('a26:Category:Maltese_archaeologists', 'a26:Category:Maltese_academics')).
delete('skos:broader'('a26:Category:Buildings_and_structures_in_Dickinson_County_Iowa', 'a26:Category:Buildings_and_structures_in_Iowa_by_county')).
delete('skos:broader'('a26:Category:Start-Class_Asia_articles', 'a26:Category:Asia_articles_by_quality')).
delete('skos:broader'('a26:Category:French_colonial_governors_and_administrators', 'a26:Category:Political_office-holders_in_France')).
delete('skos:broader'('a26:Category:Defunct_schools_in_Pennsylvania', 'a26:Category:Schools_in_Pennsylvania')).
delete('skos:broader'('a26:Category:Radio_stations_established_in_1990', 'a26:Category:Radio_stations_by_year_of_establishment')).
delete('skos:broader'('a26:Category:Revolutionary_Communist_League_France_politicians', 'a26:Category:French_Trotskyists')).
delete('skos:broader'('a26:Category:Animals_described_in_1873', 'a26:Category:Species_described_in_1873')).
delete('skos:broader'('a26:Category:People_from_Monrovia', 'a26:Category:People_from_Montserrado_County')).
delete('skos:broader'('a26:Category:Defunct_financial_services_companies', 'a26:Category:Defunct_companies_by_industry')).
delete('skos:broader'('a26:Category:Regional_airlines_of_the_Canadian_Territories', 'a26:Category:Regional_airlines_of_Canada')).
delete('skos:broader'('a26:Category:21st-century_Canadian_singers', 'a26:Category:21st-century_singers')).
delete('skos:broader'('a26:Category:Bulgarian_people', 'a26:Category:European_people')).
delete('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:Establishments_in_British_Columbia_by_year')).
delete('skos:broader'('a26:Category:Georgian_expatriates_in_France', 'a26:Category:Georgian_expatriates')).
delete('skos:broader'('a26:Category:Advanced_Micro_Devices', 'a26:Category:Manufacturing_companies_of_the_United_States')).
delete('skos:broader'('a26:Category:Scholarship_recipients', 'a26:Category:Award_winners')).
delete('skos:broader'('a26:Category:Interbank_networks', 'a26:Category:Financial_routing_standards')).
