add('skos:broader'('a26:Category:Indiana_politicians_by_party', 'a26:Category:Indiana_politicians')).
add('skos:broader'('a26:Category:Communist_parties_in_Russia', 'a26:Category:Socialist_parties_in_Russia')).
add('skos:broader'('a26:Category:Hospital_buildings_completed_in_1953', 'a26:Category:Hospital_buildings_by_year_of_completion')).
add('skos:broader'('a26:Category:Field_armies_of_Turkey', 'a26:Category:Army_units_and_formations_of_Turkey')).
add('skos:broader'('a26:Category:Roman_Catholic_parishes_of_Diocese_of_Springfield_in_Massachusetts', 'a26:Category:Roman_Catholic_Diocese_of_Springfield_in_Massachusetts')).
add('skos:broader'('a26:Category:1960s_in_Iceland', 'a26:Category:20th_century_in_Iceland')).
add('skos:broader'('a26:Category:Club_Libertad_footballers', 'a26:Category:Footballers_in_Paraguay_by_club')).
add('skos:broader'('a26:Category:Graphemes', 'a26:Category:Units_of_morphological_analysis')).
add('skos:broader'('a26:Category:Settlements_formerly_in_Klamath_County_California', 'a26:Category:Former_populated_places_in_California_by_county')).
add('skos:broader'('a26:Category:Accounting', 'a26:Category:Professional_studies')).
add('skos:broader'('a26:Category:1982_83_in_European_ice_hockey_leagues', 'a26:Category:1982_83_ice_hockey_leagues')).
add('skos:broader'('a26:Category:Monument_types', 'a26:Category:Archaeology_of_structures')).
add('skos:broader'('a26:Category:Bender_Moldova', 'a26:Category:Districts_of_Moldova')).
add('skos:broader'('a26:Category:Athletics_by_country', 'a26:Category:Athletics_sport')).
add('skos:broader'('a26:Category:Port_Phillip', 'a26:Category:Geography_of_Melbourne')).
add('skos:broader'('a26:Category:Dopamine_agonists', 'a26:Category:Antiparkinsonian_agents')).
add('skos:broader'('a26:Category:Politics_of_Austria', 'a26:Category:Politics_of_Europe')).
add('skos:broader'('a26:Category:Emerging_standards', 'a26:Category:Standards_by_type')).
add('skos:broader'('a26:Category:Populated_places_in_Morgan_County_Tennessee', 'a26:Category:Populated_places_in_Tennessee_by_county')).
add('skos:broader'('a26:Category:People_from_Montreal_by_occupation', 'a26:Category:People_from_Quebec_by_occupation')).
delete('skos:broader'('a26:Category:Pinacoteca_di_Brera', 'a26:Category:National_museums_of_Italy')).
delete('skos:broader'('a26:Category:Hungarian_nobility', 'a26:Category:Hungarian_people')).
delete('skos:broader'('a26:Category:People_from_Centereach_New_York', 'a26:Category:People_from_Brookhaven_New_York')).
delete('skos:broader'('a26:Category:County_routes_in_Passaic_County_New_Jersey', 'a26:Category:Transportation_in_Passaic_County_New_Jersey')).
delete('skos:broader'('a26:Category:Cities_in_Egypt', 'a26:Category:Cities_in_Africa')).
delete('skos:broader'('a26:Category:Populated_places_in_Al_Wahat_District', 'a26:Category:Populated_places_in_Libya')).
delete('skos:broader'('a26:Category:People_from_Dalarna', 'a26:Category:Dalarna')).
delete('skos:broader'('a26:Category:Populated_places_in_Morgan_County_Tennessee', 'a26:Category:Geography_of_Morgan_County_Tennessee')).
delete('skos:broader'('a26:Category:Football_clubs_in_Guanajuato', 'a26:Category:Football_in_Guanajuato')).
delete('skos:broader'('a26:Category:Five-year_plans', 'a26:Category:Economic_planning')).
delete('skos:broader'('a26:Category:Bilateral_relations_of_Finland', 'a26:Category:Bilateral_relations')).
delete('skos:broader'('a26:Category:Sources_on_Germanic_paganism', 'a26:Category:Historical_documents')).
delete('skos:broader'('a26:Category:Great_Officers_of_State_of_England', 'a26:Category:Great_Officers_of_State')).
delete('skos:broader'('a26:Category:Fencers_at_the_2011_Pan_American_Games', 'a26:Category:Competitors_at_the_2011_Pan_American_Games')).
delete('skos:broader'('a26:Category:American_racquetball_players', 'a26:Category:Racquetball_players_by_nationality')).
delete('skos:broader'('a26:Category:20th-century_American_sculptors', 'a26:Category:American_sculptors_by_century')).
delete('skos:broader'('a26:Category:Algebraic_logic', 'a26:Category:Mathematical_logic')).
delete('skos:broader'('a26:Category:Westminster_system', 'a26:Category:Government_of_the_United_Kingdom')).
delete('skos:broader'('a26:Category:Ice_hockey_people_from_Ontario', 'a26:Category:Sportspeople_from_Ontario')).
delete('skos:broader'('a26:Category:Open_content', 'a26:Category:Crowdsourcing')).
