add('skos:broader'('a26:Category:People_from_Dumbarton', 'a26:Category:People_by_city_or_town_in_Scotland')).
add('skos:broader'('a26:Category:Digital_radio_in_Australia', 'a26:Category:Australian_radio')).
add('skos:broader'('a26:Category:Editors_of_Latter_Day_Saint_publications', 'a26:Category:Latter_Day_Saint_writers')).
add('skos:broader'('a26:Category:TransLink_British_Columbia_bus_stations', 'a26:Category:Bus_stations_in_British_Columbia')).
add('skos:broader'('a26:Category:Dams_completed_in_1993', 'a26:Category:Dams_by_year_of_completion')).
add('skos:broader'('a26:Category:Dukes_of_Lennox', 'a26:Category:Dukes_in_the_Peerage_of_Scotland')).
add('skos:broader'('a26:Category:People_from_Centereach_New_York', 'a26:Category:People_from_Brookhaven_New_York')).
add('skos:broader'('a26:Category:University_of_Texas_at_Austin_alumni', 'a26:Category:Alumni_by_university_or_college_in_Texas')).
add('skos:broader'('a26:Category:American_musicians_of_Asian_descent', 'a26:Category:American_musicians_by_ethnic_or_national_origin')).
add('skos:broader'('a26:Category:Amino_acids', 'a26:Category:Biomolecules_by_chemical_classification')).
add('skos:broader'('a26:Category:Cricket_in_Sweden', 'a26:Category:Cricket_by_country')).
add('skos:broader'('a26:Category:Roadside_attractions_in_South_Dakota', 'a26:Category:Visitor_attractions_in_South_Dakota')).
add('skos:broader'('a26:Category:Oricon_Weekly_number-one_singles', 'a26:Category:Number-one_singles_in_Japan')).
add('skos:broader'('a26:Category:Islands_of_the_Irish_Sea', 'a26:Category:Irish_Sea')).
add('skos:broader'('a26:Category:Egyptological_collections_in_the_United_States', 'a26:Category:Egyptological_collections')).
add('skos:broader'('a26:Category:Caernarfonshire', 'a26:Category:History_of_Gwynedd')).
add('skos:broader'('a26:Category:Westminster_system', 'a26:Category:Government_of_the_United_Kingdom')).
add('skos:broader'('a26:Category:Invasive_plant_species', 'a26:Category:Invasive_species')).
add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Cinema_of_Brazil')).
add('skos:broader'('a26:Category:Solar_phenomena', 'a26:Category:Stellar_phenomena')).
delete('skos:broader'('a26:Category:Ancient_Greek_sites_in_Egypt', 'a26:Category:Ptolemaic_colonies')).
delete('skos:broader'('a26:Category:Glands', 'a26:Category:Organs')).
delete('skos:broader'('a26:Category:Presidents_of_Texas_AandM_University', 'a26:Category:Presidents_by_university_or_college_in_the_United_States')).
delete('skos:broader'('a26:Category:French_silent_short_films', 'a26:Category:Silent_short_films')).
delete('skos:broader'('a26:Category:People_from_Moradabad', 'a26:Category:People_from_Uttar_Pradesh')).
delete('skos:broader'('a26:Category:School_districts_in_Erath_County_Texas', 'a26:Category:School_districts_in_Texas_by_county')).
delete('skos:broader'('a26:Category:Long-distance_footpaths_in_Wales', 'a26:Category:Footpaths_in_Wales')).
delete('skos:broader'('a26:Category:History_of_Syrmia', 'a26:Category:History_of_Croatia_by_region_or_territory')).
delete('skos:broader'('a26:Category:Romanian_Christian_monks', 'a26:Category:Christian_monks_by_nationality')).
delete('skos:broader'('a26:Category:Endemic_flora_of_Yemen', 'a26:Category:Endemic_flora_by_country')).
delete('skos:broader'('a26:Category:Road_bridges_in_Maryland', 'a26:Category:Bridges_in_Maryland')).
delete('skos:broader'('a26:Category:Geography_of_Greene_County_New_York', 'a26:Category:Geography_of_the_Hudson_Valley')).
delete('skos:broader'('a26:Category:SI_derived_units', 'a26:Category:SI_units')).
delete('skos:broader'('a26:Category:TransLink_British_Columbia_bus_stations', 'a26:Category:TransLink_British_Columbia')).
delete('skos:broader'('a26:Category:Bodies_of_water_of_Europe', 'a26:Category:Landforms_of_Europe')).
delete('skos:broader'('a26:Category:Television_commercials', 'a26:Category:Advertising_by_type')).
delete('skos:broader'('a26:Category:Dog_breeds', 'a26:Category:Dogs')).
delete('skos:broader'('a26:Category:Literary_festivals_in_the_United_States', 'a26:Category:Festivals_in_the_United_States')).
delete('skos:broader'('a26:Category:Dams_completed_in_1994', 'a26:Category:Dams_by_year_of_completion')).
delete('skos:broader'('a26:Category:People_from_Montreal_by_occupation', 'a26:Category:People_from_Quebec_by_occupation')).
