add('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent53', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor2/Publication11', 'http://www.Department2.University0.edu/FullProfessor2')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication4', 'http://www.Department1.University0.edu/AssociateProfessor5')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent158', 'http://www.Department0.University0.edu/Course14')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent252', 'http://www.Department1.University0.edu/Course36')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent173', '"UndergraduateStudent173@Department2.University0.edu"^^xsd:string')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent174', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent106', 'http://www.Department1.University0.edu/GraduateCourse32')).
add('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent84', 'http://www.Department0.University0.edu/GraduateCourse26')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent131', 'http://www.Department1.University0.edu/Course6')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/AssistantProfessor8/Publication0', 'http://www.Department2.University0.edu/AssistantProfessor8')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor4/Publication14', 'http://www.Department1.University0.edu/GraduateStudent113')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent424', 'http://www.Department2.University0.edu/Course21')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent352', 'http://www.Department2.University0.edu/Course7')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent94', 'http://www.Department1.University0.edu/Course36')).
delete('a1:teacherOf'('http://www.Department0.University0.edu/FullProfessor7', 'http://www.Department0.University0.edu/GraduateCourse11')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent131', 'http://www.Department2.University0.edu/Course17')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent386', 'http://www.Department2.University0.edu/Course26')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent125', 'http://www.Department1.University0.edu/Course6')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor3', 'http://www.Department1.University0.edu/Course7')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent79', 'http://www.University741.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent76', 'http://www.Department1.University0.edu/Course38')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent77', 'http://www.Department0.University0.edu/GraduateCourse29')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssistantProfessor6/Publication5', 'http://www.Department0.University0.edu/AssistantProfessor6')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/FullProfessor1', '"FullProfessor1@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/AssociateProfessor3/Publication6', 'http://www.Department2.University0.edu/GraduateStudent101')).
delete('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent253', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/Lecturer2', '"Lecturer2@Department0.University0.edu"^^xsd:string')).
delete('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent313', 'http://www.Department0.University0.edu/AssociateProfessor9')).
delete('a1:doctoralDegreeFrom'('http://www.Department0.University0.edu/FullProfessor5', 'http://www.University926.edu')).
