add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent204', '"UndergraduateStudent204@Department1.University0.edu"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent293', 'http://www.Department0.University0.edu/Course25')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent95', 'http://www.Department1.University0.edu/Course52')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent22', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor10/Publication14', 'http://www.Department1.University0.edu/AssociateProfessor10')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent180', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent412', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent143', 'http://www.Department0.University0.edu/Course50')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor10/Publication13', 'http://www.Department0.University0.edu/GraduateStudent33')).
add('a1:emailAddress'('http://www.Department0.University0.edu/Lecturer2', '"Lecturer2@Department0.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department2.University0.edu/UndergraduateStudent334', 'http://www.Department2.University0.edu/AssociateProfessor4')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent102', 'http://www.Department2.University0.edu/FullProfessor6')).
add('a1:telephone'('http://www.Department1.University0.edu/GraduateStudent81', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent374', 'http://www.Department1.University0.edu/Course40')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent66', 'http://www.University141.edu')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent77', 'http://www.Department2.University0.edu/Course16')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/AssociateProfessor2', '"AssociateProfessor2@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent137', '"UndergraduateStudent137@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent114', 'http://www.Department1.University0.edu/GraduateCourse26')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent194', 'http://www.Department0.University0.edu/Course1')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent86', '"UndergraduateStudent86@Department1.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent321', '"UndergraduateStudent321@Department0.University0.edu"^^xsd:string')).
delete('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent103', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent159', '"UndergraduateStudent159@Department1.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication5', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication7', 'http://www.Department2.University0.edu/GraduateStudent65')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent192', 'http://www.Department2.University0.edu/Course11')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent193', 'http://www.Department0.University0.edu/Course17')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent219', 'http://www.Department2.University0.edu/Course7')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent424', 'http://www.Department2.University0.edu/Course21')).
