add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent109', 'http://www.Department1.University0.edu/AssistantProfessor6')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent123', 'http://www.Department0.University0.edu/Course29')).
add('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent9', 'http://www.University549.edu')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent323', 'http://www.Department0.University0.edu/Course8')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent109', '"UndergraduateStudent109@Department2.University0.edu"^^xsd:string')).
add('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/AssociateProfessor12', 'http://www.University459.edu')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent164', 'http://www.Department2.University0.edu/Course6')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent22', 'http://www.Department2.University0.edu/AssociateProfessor7')).
add('a1:takesCourse'('http://www.Department2.University0.edu/GraduateStudent111', 'http://www.Department2.University0.edu/GraduateCourse19')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent129', 'http://www.Department0.University0.edu/Course45')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor2/Publication4', 'http://www.Department0.University0.edu/AssociateProfessor2')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent362', 'http://www.Department1.University0.edu/Course35')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent258', 'http://www.Department0.University0.edu/Course31')).
add('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent51', '"GraduateStudent51@Department1.University0.edu"^^xsd:string')).
add('a1:doctoralDegreeFrom'('http://www.Department1.University0.edu/AssistantProfessor5', 'http://www.University911.edu')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent132', '"UndergraduateStudent132@Department2.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent305', '"UndergraduateStudent305@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent343', 'http://www.Department2.University0.edu/Course34')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor5/Publication9', 'http://www.Department1.University0.edu/GraduateStudent129')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent75', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent301', 'http://www.Department2.University0.edu/Course24')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent2', '"GraduateStudent2@Department0.University0.edu"^^xsd:string')).
delete('a1:teachingAssistantOf'('http://www.Department1.University0.edu/GraduateStudent79', 'http://www.Department1.University0.edu/Course34')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor13/Publication2', 'http://www.Department0.University0.edu/GraduateStudent34')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/GraduateStudent70', '"GraduateStudent70@Department1.University0.edu"^^xsd:string')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/AssistantProfessor1', 'http://www.Department1.University0.edu/GraduateCourse28')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent24', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent98', 'http://www.Department2.University0.edu/Course47')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent105', '"UndergraduateStudent105@Department0.University0.edu"^^xsd:string')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent52', '"GraduateStudent52@Department0.University0.edu"^^xsd:string')).
