add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent271', 'http://www.Department0.University0.edu/Course48')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent421', 'http://www.Department1.University0.edu/Course47')).
add('a1:telephone'('http://www.Department2.University0.edu/GraduateStudent83', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication2', 'http://www.Department1.University0.edu/GraduateStudent64')).
add('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent225', 'http://www.Department0.University0.edu/AssociateProfessor11')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent167', 'http://www.Department1.University0.edu/Course22')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent265', 'http://www.Department1.University0.edu/Course10')).
add('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent291', '"UndergraduateStudent291@Department2.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent85', '"UndergraduateStudent85@Department1.University0.edu"^^xsd:string')).
add('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent34', '"UndergraduateStudent34@Department1.University0.edu"^^xsd:string')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent102', 'http://www.Department2.University0.edu/FullProfessor6')).
add('a1:advisor'('http://www.Department0.University0.edu/UndergraduateStudent313', 'http://www.Department0.University0.edu/AssociateProfessor9')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent152', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent424', 'http://www.Department2.University0.edu/Course21')).
add('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent219', 'http://www.Department2.University0.edu/Course7')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor8', 'http://www.Department2.University0.edu/GraduateCourse40')).
delete('a1:telephone'('http://www.Department1.University0.edu/UndergraduateStudent197', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent319', 'http://www.Department2.University0.edu/Course8')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent249', 'http://www.Department1.University0.edu/Course26')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent79', 'http://www.University741.edu')).
delete('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor3', 'http://www.Department1.University0.edu/Course7')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent114', 'http://www.Department1.University0.edu/GraduateCourse26')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent125', 'http://www.University885.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent106', 'http://www.Department1.University0.edu/GraduateCourse32')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent8', '"UndergraduateStudent8@Department2.University0.edu"^^xsd:string')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication8', 'http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:telephone'('http://www.Department2.University0.edu/UndergraduateStudent269', '"xxx-xxx-xxxx"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent358', 'http://www.Department2.University0.edu/Course3')).
delete('a1:takesCourse'('http://www.Department2.University0.edu/UndergraduateStudent25', 'http://www.Department2.University0.edu/Course36')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent94', 'http://www.Department1.University0.edu/Course36')).
