add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent95', 'http://www.Department1.University0.edu/Course52')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent125', 'http://www.Department1.University0.edu/Course6')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor2/Publication0', 'http://www.Department1.University0.edu/GraduateStudent37')).
add('a1:publicationAuthor'('http://www.Department1.University0.edu/FullProfessor5/Publication6', 'http://www.Department1.University0.edu/GraduateStudent103')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent66', 'http://www.Department1.University0.edu/FullProfessor7')).
add('a1:teacherOf'('http://www.Department1.University0.edu/FullProfessor3', 'http://www.Department1.University0.edu/Course7')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent252', 'http://www.Department1.University0.edu/Course36')).
add('a1:advisor'('http://www.Department2.University0.edu/GraduateStudent26', 'http://www.Department2.University0.edu/FullProfessor0')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent247', 'http://www.Department0.University0.edu/Course42')).
add('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent143', 'http://www.Department0.University0.edu/Course50')).
add('a1:advisor'('http://www.Department1.University0.edu/GraduateStudent12', 'http://www.Department1.University0.edu/AssociateProfessor0')).
add('a1:telephone'('http://www.Department0.University0.edu/UndergraduateStudent253', '"xxx-xxx-xxxx"^^xsd:string')).
add('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor10/Publication13', 'http://www.Department0.University0.edu/GraduateStudent33')).
add('a1:publicationAuthor'('http://www.Department2.University0.edu/FullProfessor3/Publication7', 'http://www.Department2.University0.edu/GraduateStudent65')).
add('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent419', 'http://www.Department1.University0.edu/Course44')).
delete('a1:teacherOf'('http://www.Department2.University0.edu/AssistantProfessor4', 'http://www.Department2.University0.edu/GraduateCourse34')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/FullProfessor7/Publication11', 'http://www.Department0.University0.edu/FullProfessor7')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/UndergraduateStudent137', '"UndergraduateStudent137@Department0.University0.edu"^^xsd:string')).
delete('a1:undergraduateDegreeFrom'('http://www.Department2.University0.edu/GraduateStudent79', 'http://www.University741.edu')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/UndergraduateStudent76', 'http://www.Department1.University0.edu/Course38')).
delete('a1:emailAddress'('http://www.Department0.University0.edu/GraduateStudent54', '"GraduateStudent54@Department0.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/GraduateStudent77', 'http://www.Department0.University0.edu/GraduateCourse29')).
delete('a1:undergraduateDegreeFrom'('http://www.Department1.University0.edu/GraduateStudent125', 'http://www.University885.edu')).
delete('a1:emailAddress'('http://www.Department2.University0.edu/UndergraduateStudent291', '"UndergraduateStudent291@Department2.University0.edu"^^xsd:string')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent268', 'http://www.Department0.University0.edu/Course37')).
delete('a1:takesCourse'('http://www.Department1.University0.edu/GraduateStudent89', 'http://www.Department1.University0.edu/GraduateCourse1')).
delete('a1:publicationAuthor'('http://www.Department0.University0.edu/AssociateProfessor7/Publication8', 'http://www.Department0.University0.edu/AssociateProfessor7')).
delete('a1:publicationAuthor'('http://www.Department1.University0.edu/AssociateProfessor0/Publication5', 'http://www.Department1.University0.edu/AssociateProfessor0')).
delete('a1:takesCourse'('http://www.Department0.University0.edu/UndergraduateStudent193', 'http://www.Department0.University0.edu/Course17')).
delete('a1:emailAddress'('http://www.Department1.University0.edu/UndergraduateStudent80', '"UndergraduateStudent80@Department1.University0.edu"^^xsd:string')).
