add('skos:broader'('a26:Category:Brazilian_films', 'a26:Category:Works_by_Brazilian_people')).
add('skos:broader'('a26:Category:Privy_councils', 'a26:Category:Oligarchs')).
add('skos:broader'('a26:Category:18th-century_monarchs_in_the_Middle_East', 'a26:Category:Middle_Eastern_monarchs')).
add('skos:broader'('a26:Category:People_from_Perth-Andover', 'a26:Category:People_from_Victoria_County_New_Brunswick')).
add('skos:broader'('a26:Category:2012_television_films', 'a26:Category:2012_films')).
add('skos:broader'('a26:Category:Mythological_sword_fighters', 'a26:Category:Mythological_characters')).
add('skos:broader'('a26:Category:Historic_districts_in_Adams_County_Pennsylvania', 'a26:Category:Buildings_and_structures_in_Adams_County_Pennsylvania')).
add('skos:broader'('a26:Category:19th_century_in_Yorkshire', 'a26:Category:Centuries_in_Yorkshire')).
add('skos:broader'('a26:Category:1977_establishments_in_British_Columbia', 'a26:Category:Establishments_in_British_Columbia_by_year')).
add('skos:broader'('a26:Category:Screenshots_of_Windows_Server', 'a26:Category:Windows_Server')).
delete('skos:broader'('a26:Category:Analytical_chemistry', 'a26:Category:Chemistry')).
delete('skos:broader'('a26:Category:Algebraic_topology', 'a26:Category:Abstract_algebra')).
delete('skos:broader'('a26:Category:Random_House_books', 'a26:Category:Books_by_publisher')).
delete('skos:broader'('a26:Category:Graphical_user_interface_testing', 'a26:Category:Software_testing_tools')).
delete('skos:broader'('a26:Category:Clarinetists', 'a26:Category:Woodwind_musicians')).
delete('skos:broader'('a26:Category:South_Somerset', 'a26:Category:Non-metropolitan_districts_of_Somerset')).
delete('skos:broader'('a26:Category:Duroch_Islands', 'a26:Category:Trinity_Peninsula')).
delete('skos:broader'('a26:Category:The_Football_League_representative_players', 'a26:Category:The_Football_League_players')).
delete('skos:broader'('a26:Category:Solar_phenomena', 'a26:Category:Stellar_phenomena')).
delete('skos:broader'('a26:Category:Bender_Moldova', 'a26:Category:Districts_of_Moldova')).
